### ISSUE TITLE
Users can dynamically sort records in a subform grid

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1159]
Requested by Borror lab and a few other collections
They would like to be able to change the sort order of the records displayed in subform grids on forms dynamically, so they can change it according to the field they need for that particular moment

**Comment by maxxxxxdlp** [comment]
Fixed in 73a6990d
The default sort field and sort direction can be set in the form definition (more details: https://github.com/specify/specify7/issues/1213#issuecomment-1086441675). Setting default sort order may affect the order in which records are stored in the database.
Additionally, user may click on the column header to manually change sort order. Changing sort by clicking on the header does not affect the order in which records are saved in the database.
