### ISSUE TITLE
Collecting Event Authorization subform not appearing

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1198]
**Describe the bug**
The Collecting Event Authorization subview is not displaying in 7. When you use the button on a new record a new window does not appear.

**To Reproduce**
1. Go to the freshfish database
2. Create a collecting event form
3. Try to use the CeAu button:
![image](https://user-images.githubusercontent.com/37256050/159044768-aee899d9-0c73-4e87-929f-7fa13513f359.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/37256050/159044817-e781df9f-6dee-4de0-abed-a98d34645575.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Reported By**
CSIRO

**Comment by grantfitzsimmons** [comment]
This may be another part of this bug, but the number for the count of CollectingEventAuthorization is not increasing.

![image](https://user-images.githubusercontent.com/37256050/159057411-8445e7b0-4ad9-4d21-b935-f8044c2e27ad.png)

This same thing is seen in the freshfish database.

**Reported by:** CSIRO

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/164055302-8e882fa6-7154-4c6f-b8f9-02d927ba8418.png)

I am unable to add any Collecting Event Authorizations in `a11y`.

Still `freshfish` and CE form

**Comment by maxxxxxdlp** [comment]
The issue is present in the current sp7 release too.
Can replicate it here: https://sp7demofish.specifycloud.org/specify/view/collectingevent/new/
Seems like if trying to render a subview for a non-dependent field, it is rendered as readonly.
@benanhalt can I remove this line?
https://github.com/specify/specify7/blob/ffbd9f89ccc7aed4852f2770c0e1d535983b8af6/specifyweb/frontend/js_src/lib/subview.js#L53

**Comment by benanhalt** [comment]
I think CEA just needs to be set to be a dependent relationship.

**Comment by maxxxxxdlp** [comment]
I can't do that on the front-end because of this:

![Screen Shot 2022-04-20 at 11 26 16](https://user-images.githubusercontent.com/40512816/164278191-f67a1930-49cc-44c3-86a5-e90a4f22f023.png)


Also, does anyone know why SubView definition referenced an AccessionAuthorization view?
![Screen Shot 2022-04-20 at 11 24 14](https://user-images.githubusercontent.com/40512816/164278262-48f17c65-8bee-4e5c-8d9f-dd2fec81862c.png)
In this release, I made front-end force relationship resource model and form classname to match.
@benanhalt Should I relax that restriction to allow such intermingling?

**Comment by benanhalt** [comment]
I'll set it on the backend.

**Comment by benanhalt** [comment]
The reference to the AccessionAuthorization view might just be a mistake in the form. I suppose it might work if form only had fields that occur in both objects.

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168889342-eb07317e-7025-4b43-a842-5a9970b91020.png)

Still not working- probably will be next release

**Comment by maxxxxxdlp** [comment]
Confirmed fixed

**Comment by grantfitzsimmons** [comment]
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/37256050/177813654-c32d023b-130c-4032-b6ff-17c55374b70a.png">

Loads endlessly

db: `cleanfish`
form: Collecting Event

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons In cases like this please attach a screenshot of the console log

**Comment by grantfitzsimmons** [comment]
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/177815559-95825833-9da4-49ed-9032-8610306156d6.png">

**Comment by maxxxxxdlp** [comment]
This is becase of a typo in the form definition in that database. See my previous reply:

Me:
> Also, does anyone know why SubView definition referenced an AccessionAuthorization view? ![Screen Shot 2022-04-20 at 11 24 14](https://user-images.githubusercontent.com/40512816/164278262-48f17c65-8bee-4e5c-8d9f-dd2fec81862c.png) In this release, I made front-end force relationship resource model and form classname to match. @benanhalt Should I relax that restriction to allow such intermingling?


Ben:
> The reference to the AccessionAuthorization view might just be a mistake in the form. I suppose it might work if form only had fields that occur in both objects.
