### ISSUE TITLE
Number float(20,10) datatype is not preserving entered values

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1208]
**Describe the bug**
Vivek from CSIRO found that there is an issue in various tables caused by the floating-point rounding.

"This behavior is seen when data is entering through the form, eg enter 2.20 in the form which is mapped to Numberx float(20,10) data type in any of the specify tables, when you reload the form after saving, the value is 2.2000000477 

update collectingeventattribute set Number1 = 9999999999.9999999999  where  CollectingEventAttributeID = 1;
SELECT CollectingEventAttributeID, Number1 FROM collectingeventattribute where CollectingEventAttributeID = 1;

result 1000000000.0000000000

Solution might be to change all float(20,10) data types to decimal(20,10)"

**Expected behavior**
The entered value should be preserved.

**Reported By**
Vivek at CSIRO

**Additional context**
"We use (4,2) format (at least for the fish collection) still value such as 99.99 are rounded and stored in  db as 99.98, this would be misrepresentation of data and the original data is completely lost..  
I gave it a brief test changing the db type to decimal(20,10), code seems to be happy and working as expected, not sure if there would be any side effects as mapped java types are floats in s6."

**Comment by benanhalt** [comment]
I'm not sure why Specify is using mostly `float(n,m)` types rather than `decimal(n,m)`. All of the tables are created by Specify 6 according to it's own obscure proclivities. I had hoped that there would be some generic fields that were realized as `decimal(n,m)` in the database that could be used, but that does not seem to be the case. 

It might be possible to add some *Decimal1* -- *DecimalN* generic fields that are of the `decimal(n,m)` type. Specify is known to support them as they are used for the latitude and longitude fields. However, it would require a Specify 6 schema change release to occur.

It would also be interesting to investigate what would happen if all the `float` fields were changed to `decimal` wholesale.

There is another issue which would not be addressed by the changing the`float` fields. This issue has plagued the coordinate fields for ages. Namely, the database doesn't capture the precision of entered values. There is currently no way to distinguish, say, 2.20 from 2.2000000000 despite these having very different meanings as measured values.

**Comment by benanhalt** [comment]
Next step: Try changing the datatype at the database level and see how Specify 6 reacts. If badly, what happens if the java type is changed from float -> big decimal. That is maybe hard because the type is probably repeat throughout the code base?

**Comment by benanhalt** [comment]
I have completed the following experiments:

Changing the column type of a numberN field which contains existing data from `float(20,10)` to `decimal(20,10)` using the following DDL:

`alter table collectingeventattribute change column number12 number12 decimal(20, 10);`

The command succeeds and preserves existing values though with possibly some rounding in the final digits.

After this change, in Specify 7 values from the database are correctly represented as Python Decimal types within the server and are returned via the main API as string values to prevent casting to JS floating point values in JSON. Values returned via the query API are returned as JSON number (so floating point) types. In the other direction, values sent from the front end to the server were expressed incorrectly as JS number types but were accepted and recorded correctly. I suspect the JSON number values are represented as doubles in Python then converted to Decimal values either by Django or the mysqlclient library. I didn't investigate further because I would prefer not to trust this mechanism and instead serialize decimal values as strings rather than JSON numbers.

Unmodified Specify 6 was able to retrieve the decimal data from the database though it exhibited the expected rounding due to passing through the Java Float type. It was also able to save values back to the modified columns with the same caveat. Presumably the ORM is able to convert back and forth between the database decimal type and the Java Float type albeit with the expected rounding effects. I did not try loading a record and saving it back without modifying an altered field to see whether Specify 6 would preserve the decimal value in that case or overwrite it with the value that had passed through the Float conversion.

Next, I modified (https://github.com/specify/specify6/commit/24b1e7dd2e0216481d8628a4703466715c633f11) the Specify 6 source code to change all Float type fields in CollectingEventAttribute to BigDecimal and added the Hibernate annotations to indicate a precision of 20 and a scale of 10. Surprisingly, the code compiled cleanly and ran without any obvious errors. Data was retrieved and saved to the database correctly both for the field which had been altered to `decimal(20,10)` and those that remained as `float(20,10)`. I tried "forcing" a schema update by setting back the schema version in the spversion table. This did not result in Hibernate automatically altering the column types in the database, nor did I expect it to do so.

Finally, I used the generated specify_datamodel.xml from the modified Specify 6 in Specify 7 to make it aware of the changed data types. This resulted in decimal values in query results being correctly represented with strings by the server. The front end continued to incorrectly represent the values as JS numbers when sending them to the server.

**Comment by maxxxxxdlp** [comment]
Should front-end be modified to send all decimals as strings?

**Comment by benanhalt** [comment]
Yes. Any value that is indicated to be `java.math.BigDecimal` by the data model should never be converted to a JS number. The only number type in JS is some sort of double precision floating point type. The developer tools in browsers apparently do some kind of voodoo so that when you type `0.1` it appears to stay `0.1` but try `0.1 + 0.2` and you will see that it is a base-two value behind the scenes that cannot correctly represent base-ten decimal values.

**Comment by benanhalt** [comment]
The exception would be within the LatLong UI where it has to do computations with the values to convert between DMS and decimal representations.

**Comment by benanhalt** [comment]
So the question becomes, do we want to modify Specify 6 to introduce a schema change to convert all the Float fields to Decimal fields? Specify 6 would need to be tested fairly thoroughly, I think. Beyond just the basic forms and queries that I tried. But it does seem at least possible at this point.

**Comment by benanhalt** [comment]
I am going to produce a branch of Specify 6 as described above.

**Comment by maxxxxxdlp** [comment]
From @tlammer:

> Discovered by a user (Paul Larson?).
When a number is entered into a float field (number 1, number 2, etc.), MySQL saves the value to the 7th (I think) decimal. Generally, users either enter a whole number or to the tenth or hundreds value, nothing near the specificity of 7 decimal points.
In Specify 6, that value is masked to appear as it was originally entered in the query results, data entry forms, and what is exported.
Specify 7 displays the value as it is saved in MySQL, not as it was entered.

**Comment by grantfitzsimmons** [comment]
https://github.com/specify/specify6/issues/1149

**Comment by grantfitzsimmons** [comment]
Solved in 6.8.02
