### ISSUE TITLE
[a11y] Redundant colons appearing in some forms titles

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1234]
**Describe the bug**
Extra colons!

**To Reproduce**
1. See Collecting Event form title
2. See Collecting Trip form title

**Screenshots**
<img width="394" alt="image" src="https://user-images.githubusercontent.com/37256050/163511385-33738876-9dc4-47e5-b7b0-6840a7c67b00.png">

**Comment by maxxxxxdlp** [comment]
The cause for this is the same as https://github.com/specify/specify7/issues/1227
The title is built by converting the record to text according to a user-defined formatter. If the object is new and many fields are empty, the formatter is mostly empty, but the separators are still visible.
I can't really fix this issue because formatters are user-defined.

Other than not looking nice, I don't think this is an issue as usually formatters contain only the fields that have some value most of the time (with exception of records that are just being created, of course).

**Comment by grantfitzsimmons** [comment]
I guess it would require some logic to have it only display a separator if preceded by some value. Understood

**Comment by maxxxxxdlp** [comment]
That is possible. You can make formatter change itself based on values of some fields, but again, formatters are user-defined, I can't change them.
