### ISSUE TITLE
[a11y] Changing CatNo formatter doesn't change field requirements

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1277]
**Describe the bug**
I modified the catalog number to be an unformatted string but the formatting requirements are still visible. Switching to another computer led to the same issue.

![image](https://user-images.githubusercontent.com/37256050/164049181-ed799b51-ecd1-44da-8fd3-ba7f131b4327.png)

macOS, Edge

db: newmexico

**Comment by maxxxxxdlp** [comment]
It looks like the formatter for catalogNumber is taken from the Collection resource (it has a field called `catalogNumFormatName`). Only if Collection.catalogNumFormatName is empty, the formatter from the schema config is used.

I imagine it was made this way so that different collections could have different catalog number formatters.

You can run a query on the `collection` table to see the collection in a form view. Note though, that field is not present on the form in my database, so you may have to edit the form definition to add it first.
