### ISSUE TITLE
Permissions checkboxes not visible in light mode

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1292]
**Describe the bug**
The checkboxes for permissions are not visible in light mode

**To Reproduce**
1. Go to Security panel
2. Click on a collection and then a user
3. Note the checkboxes

**Expected behavior**
I would expect them to look like the checkboxes for access in the screenshot below

**Screenshots**
![security panel](https://user-images.githubusercontent.com/7501989/164307717-a9a45b98-f36f-4b14-b7d4-5e821e43e9e4.JPG)
![security panel2](https://user-images.githubusercontent.com/7501989/164307943-36d62057-791a-4171-814a-2a8b11f642c2.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by acbentley** [comment]
They ARE checked.  They have a white checkmark in them that is barely visible.  They should be more visible than that.

**Comment by maxxxxxdlp** [comment]
Fixed in c229548c

For reference, these are checkbox and radio styles for all possible situations/variations:
![Screen Shot 2022-04-27 at 11 08 01](https://user-images.githubusercontent.com/40512816/165563124-2c43690c-b97e-443e-8a12-100fc0764da1.png)
![Screen Shot 2022-04-27 at 11 08 18](https://user-images.githubusercontent.com/40512816/165563130-5d23e6b6-60f4-4c69-b282-3f108630495f.png)
