### ISSUE TITLE
[a11y] Query not pulling the same results

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1349]
**Describe the bug**
a11y is not querying and finding all the results

**To Reproduce**
1. Go to freshfish `/specify/query/108/`
2. Run the query
3. See discrepency

## a11y

![image](https://user-images.githubusercontent.com/37256050/165806336-d884bd09-9cc4-4f1a-9654-d97cba1f060c.png)
![image](https://user-images.githubusercontent.com/37256050/165806221-cfe06970-3bc6-436d-ae98-d1c2fa3ffe9a.png)

## Edge
![image](https://user-images.githubusercontent.com/37256050/165806248-2d4eabfb-7233-483e-a0fc-d2783ae3fb5f.png)

**Comment by maxxxxxdlp** [comment]
Ha!
Here the bug turns out to be on `edge`
Front-end on `edge` sends dates to the back-end in the wrong format (see https://github.com/specify/specify7/issues/1348#issuecomment-1112715654), and back-end just ignores that, thus you get back results for all dates.

On `a11y`, the date is sent in a proper format, thus you get fewer results
