### ISSUE TITLE
Schema config returns to base table list after each save

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1387]
**Describe the bug**
After each save operation in the schema config you are returned to the base table list and have to reselect the table to make more changes

**To Reproduce**
1. Go to Schema config
2. Click on a base table
3. Change any value and save
4. You will be sent back to the base table list

**Expected behavior**
I would expect to stay on the current page so that I can make more changes if necessary rather than having to reselect the table again after each save

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Why would you want to make more changes after you saved?
Just make all changes to a given table, then save

Though, perhaps a better alternative would be to make the table selection list always visible on the side, like in sp6 (https://github.com/specify/specify7/issues/1252):
![image](https://user-images.githubusercontent.com/40512816/166740724-eed0acfc-caae-43be-abff-4ead7951d408.png)
There are some technical challenges with that solution, which is why it wasn't implemented in the first interaction, but it's something to consider for 2nd gen.

**Comment by acbentley** [comment]
There may be instances where you save one change and forget that you have other changes to make.  I agree that a better alternative would be to have the tables listed in a left-hand menu but before that I would suggest to just leave people on the current page rather than redirect them to the table list by default.

Andy
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V
Andy Bentley
Ichthyology Collection Manager
University of Kansas
Biodiversity Institute
Dyche Hall
1345 Jayhawk Boulevard<x-apple-data-detectors://9/>
Lawrence, KS, 66045-7561<x-apple-data-detectors://9/>
USA<x-apple-data-detectors://9/>

Tel: (785) 864-3863<tel:%28785%29%20864-3863>
Fax: (785) 864-5335<tel:%28785%29%20864-5335>
Email: ***@***.******@***.***>
ORCID: https://orcid.org/0000-0002-3093-1258
http://ichthyology.biodiversity.ku.edu<http://ichthyology.biodiversity.ku.edu/>
    A  :             A  :             A  :
 }<(((_°>.,.,.,.}<(((_°>.,.,.,.}<)))_°>
    V                V                V

**Comment by grantfitzsimmons** [comment]
Closing in favor of implementing https://github.com/specify/specify7/issues/1252
