### ISSUE TITLE
[a11y] A "select all" option for query results

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1406]
![image](https://user-images.githubusercontent.com/37256050/167177731-17555361-f79e-48e9-ad15-2698ce5771c8.png)

If I want to select all records and only remove a handful, there is no easy way to do this currently.

**Comment by maxxxxxdlp** [comment]
We did that intentionally.
There are several reasons:
- If a query returns a million records, and you want to uncheck a few, it would have to load all million records first, which would be SLOW. The current solution allows you to select only records that are visible, thus ensuring that they are loaded already.
- If you have many query results, it is unlikely you would want to uncheck a handful of them, because a better solution is to just adjust your filter conditions. Instead, you would want to uncheck a handful of results happen if you have only ~30 results, which is not hard to do under current design: check first checkbox, scroll to the end, and shift click on the last checbox

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Maybe there should be a drag down option...

https://cross-browser.com/x/examples/clickndrag_checkboxes.php

**Comment by grantfitzsimmons** [comment]
https://github.com/specify/specify7/issues/1414
