### ISSUE TITLE
[a11y] Not preserving home page settings

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1465]
Accessing the same database with both `edge `and `a11y`, the home screen does not display taxon tiles if it was previous enabled. User preferences work in the new version but old setups are not preserved.

**Comment by maxxxxxdlp** [comment]
In edge you can only enable taxon tiles globally (for all users), and you can only do that if you are an admin.
On a11y everyone can enable those for themself.
Since that preference is stored in different places, the behavior is different between the branches

It might be nice to be able to set default user preferences for all users (https://github.com/specify/specify7/issues/1337). Probably in next release
