### ISSUE TITLE
Agent Query Errors

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#152]
I've run into a few errors when trying to create agent queries. Because they seem to be really specific queries, I'm putting all of them in one bug for now.

Error 1: When doing the following query: Agent -> Collectors -> (aggregated)
You get this error:
Warning at /stored_query/ephemeral/
Row 45 was cut by GROUP_CONCAT()

Error 2: When doing the following query: Agent -> catalogerof -> Cataloger -> (formatted)
                              OR this query: Agent -> catalogerof -> Accession # -> (formatted)
                              OR this query: Agent -> catalogerof -> Collecting Events -> (formatted)
You get this error:
AttributeError at /stored_query/ephemeral/
'NoneType' object has no attribute 'is_relationship'

Error 3: When doing the following query: Agent -> Agent Attachments -> (aggregated)
You get this error:
AttributeError at /stored_query/ephemeral/
'NoneType' object has no attribute 'getiterator'

**Comment by benanhalt** [comment]
Error 1 is caused by the aggregated value becoming too large. Some agents may be collectors of thousands of items, so aggregating those into a single field produces a value that gets truncated by [mysql](http://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_group_concat_max_len) resulting in a warning. I'm not sure why Django then treats the warning as an error.

**Comment by benanhalt** [comment]
Moving *Error 1* to #183.
