### ISSUE TITLE
[a11y] User Invite Link not functioning

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1568]
![image](https://user-images.githubusercontent.com/37256050/168137177-0a208688-728f-4b13-a1ce-ee3aa3cb0541.png)

Say you have an invite link such as the following:
http://a11y.test.specifysystems.org/accounts/use_invite_link/?token=eyJ1c2VyaWQiOiAxMiwgInVzZXJuYW1lIjogImpvZSIsICJzZXF1ZW5jZSI6IG51bGwsICJleHBpcmVzIjogMTY1Mjk4MjQzM30%3D&mac=hrNyEjmW7IAUme4izgXKLITu1sryjiew3s7Qy0iBAVk%3D

This brings you to a blank log in screen and has no function. The **Copy** button should also visually indicate that the text has been copied (like the master key generation)

**Comment by maxxxxxdlp** [comment]
That's because there are no third-party identity providers configured on the test server.
I should probably remove that button in such cases.
The UI issues are fixed though

Here is how that page looks like when I follow it:

<img width="1800" alt="Screen Shot 2022-05-12 at 20 55 08" src="https://user-images.githubusercontent.com/40512816/168195895-98e96c12-b2e1-4e31-bce8-82a5e1ae621c.png">

And here is a regular login page:

<img width="1800" alt="Screen Shot 2022-05-12 at 20 56 22" src="https://user-images.githubusercontent.com/40512816/168196018-6744b4db-3011-4861-a7de-66320e202277.png">

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/168334849-37166910-697c-484d-bbe5-bc3739b37378.png)
