### ISSUE TITLE
Ability to modify Locality Preferences

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#159]
You have to do this through the Specify 6 database

**Comment by tlammer** [comment]
A bit more information might be helpful, sorry, The coordinates plugin has its own preferences you can set (default n, default e, coordinate format default) from the locality page

**Comment by maxxxxxdlp** [comment]
From @grantfitzsimmons:

> > In S6 you have the functionality to set Preferences default settings for Locality, there is no option to do this in Specify 7. Our researchers may need to un-tick the "Default to Latitude North" and "Default to Longitude West" as majority of the locations will be in the southern hemisphere.
> 
> ![image](https://user-images.githubusercontent.com/37256050/177610336-37dd4cbe-887b-4586-b7f0-ad752b4f3f83.png)
> 
> **Requested By:** Don Balmaceda at CSIRO

**Comment by maxxxxxdlp** [comment]
Added ability to change default type from Point to Line or Rectangle

Documentation: https://github.com/specify/specify7/wiki/Form-System#:~:text=and%20Long2Text%20fields.-,latLongType,-(%27Point%27%20%7C%20%27Line%27%20%7C%20%27Rectangle

As far as customizing "Default to Latitude North" and "Default Longitude West", I am not sure how these are supposed to work. Sp7 recognizes positive coordinates as west and negative coordinates as east. Is this checkbox supposed to swap that so that the negative coordinate becomes west?

For the "Default Format" option:
It is not as applicable in Specify 7 as it interprets the coordinate format automatically. Or do you want to change the format of the parsed coordinate (in the last column of the latitude/longitude table)?

And if we allow changing the format of the formatted coordinate, should this change persist in the database, or should it be just formatted on the UI. If it should persist, what would happen to records that were created previously in a different format?
