### ISSUE TITLE
Inconsistent buttons on forms

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1607]
**Describe the bug**
The buttons are not consistent across all forms.  There are a couple of issues (see screenshots below):

1. Some forms have Cancel others have Close
2. The Cancel button turns red when there is an invalid selection but should not as it is still valid to cancel
3. On some forms the cancel button is sometimes not a button but just a word
4. On some forms there is no save button (which perpetuates the same issue in Sp 6 - it just says done)

**To Reproduce**
5. Click on '....'
6. Scroll down to '....'
7. See error

**Expected behavior**

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/168648040-f5f3cf62-3723-4b71-9638-98b328692fc4.JPG)
![Capture2](https://user-images.githubusercontent.com/7501989/168648048-32ba7b45-c086-4b8e-99a8-352fcaec6b13.JPG)
![Capture3](https://user-images.githubusercontent.com/7501989/168648059-b521278f-b909-48c7-a984-45a466d2e691.JPG)
![Capture4](https://user-images.githubusercontent.com/7501989/168648070-c6efc820-2724-4b32-a857-bd28588a42c0.JPG)
![Capture5](https://user-images.githubusercontent.com/7501989/168648078-499ac47b-a05d-438c-b591-34a3ec9e5086.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Blue "Close" button is shown when you open a dialog
Blue "Close" button is replaced by red "Cancel" when you make changes.
This conveys the message that there are unsaved changes and that closing the dialog would mean loosing them
See more: https://github.com/specify/specify7/issues/1272 and https://github.com/specify/specify7/issues/903

We also talked in the meeting abut the cancel button having no background:
The cancel button is a word rather than a button in places where that button is unlikely to be needed. From your example, if you open a list of data sets, "cancel" is the least likely, so it should be the least prominent.

The save button is missing for dependent records, as they don't get saved when the dialog is closed. They only get saved when you press "Save" on the parent form.
See more: https://github.com/specify/specify7/issues/675
I had a fake "Save" button for dependent records at one point, but we decided to remove it during one of our meetings. I can bring it back easily.
