### ISSUE TITLE
Tree level Title not showing despite having one in Specify 6

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1641]
![image](https://user-images.githubusercontent.com/12532430/168915583-83fc2ee1-c366-4222-a500-fcaaad0adf90.png)

**Comment by maxxxxxdlp** [comment]
Please provide URL of the deployment on the test server or database name

**Comment by tlammer** [comment]
that's the picture I meant.  Ignore the previous one.  it is colorado_paleo on server 2

**Comment by maxxxxxdlp** [comment]
Most tree ranks in that definition really don't have a title:

![Screen Shot 2022-05-17 at 16 51 10](https://user-images.githubusercontent.com/40512816/168916041-eb69ffd1-4652-4219-993f-7946532a031c.png)

They only have a name. It seems like specify 6 may be automatically using `name` as title in that dialog box.

Outside the dialog box it shouldn't matter as both sp6 and sp7 use `name` if `title` is blank

**Comment by tlammer** [comment]
Specify 6 auto populates the Title field with the Name field but allows it to be editable, so in 6 it is always filled in.  What happens if someone changed the title when creating it?  Can 7 tell if it was auto populated or someone entered it by hand?

**Comment by maxxxxxdlp** [comment]
It looks like specify 6 doesn't fill out the `title` field when it auto-populates it. It is filled out on the form, but not saved in the data model.
This is not a problem because `name` is used in cases where `title` is blank
If user changes the title, the `title` field won't be empty any more and thus it would be used in place of `name`.
Thus, everything will work fine both in sp6 and sp7 and the only difference is that the tree definition item form has `title` field empty in sp7 for "auto-populated" ranks, but not empty in sp6
