### ISSUE TITLE
Editing Institution or Collection record does not allow you to return to permissions panel.

### ISSUE THREAD

**Issue by acbentley** [specify/specify7#1688]
**Describe the bug**
When editing the institution or collection record from the permissions panel, there is no button to return to the permissions panel and so have to go back through menu.

**To Reproduce**
1. Go to Permissions panel
2. Click on Institution or Collection in left-hand panel
3. Click the pencil to edit

**Expected behavior**
I would expect to be able to return to the permissions panel after making edits rather than being left in limbo and having to go back through the menu.  maybe a Close button like on other forms in the permissions panel.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/7501989/170073154-422e3c21-2d67-4b06-97d7-13ed8d7d747e.JPG)
![Capture2](https://user-images.githubusercontent.com/7501989/170073166-fe5fbc8d-85d7-49e6-906d-70507658bd58.JPG)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
 - Specify 7 Version [e.g. 7.6.1]

**Reported By**
Name of your institution

**Additional context**

**Comment by maxxxxxdlp** [comment]
Like on all other pages in specify, you can use the browser back arrow to go to the previous page.
The form does not have an idea which page you came from nor should it care.
Jim and I discuss that the best solution, in this case, would be to open the collection/institution form in a dialog rather than a full form.
Thus, when the dialog gets closed, the user is back in the security panel.
See: https://github.com/specify/specify7/issues/1656 (I will close this issue in favor of #1656)
