### ISSUE TITLE
When error message pops up, there is no option to go back to record to fix the issue

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1699]
when an error message pops up, you have the option to copy the error and/or go back to homepage, meaning you lose the record you were working on.  So all the work you did on that record is lost without even knowing what the issue was in the first place.  This is a problem not only for workflow but also for testing as I can't go back to the record and change things to figure out what caused the error.

**Comment by maxxxxxdlp** [comment]
In user preferences, there is an option "Allow dismissing error messages" (under General -> Application).
Check the checkbox and save the preferences.
Now, all error dialogs would be dismissable.

This is not turned on by default because continuing to use the app after it had an error may leave it in an unstable state. Experienced users who know what kind of error messages can be safely dismissed can turn on that preference for themself.

Also, keep in mind that not every user can check the "Allow dismissing error messages" checkbox for themself. They can only do that if they have the `Preferences -> User -> Edit Protected` permission
