### ISSUE TITLE
One to many tables can no longer be viewed as grid

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1717]
Tested in KUBirds
On the Collection Object form, the option to view determinations and preparations in a grid is no longer available.  they can only be viewed as a subform

**Comment by maxxxxxdlp** [comment]
The cell definition explicitly tells to display it as a form, rather than a formTable (the defaulttype attribute):

```xml
<cell colspan="16" defaulttype="form" id="8" name="preparations" rows="5" type="subview" viewname="Preparation" />
```

As an example, in KUFish Voucher collection, Preparations are displayed as a formTable:

<img width="1800" alt="Screen Shot 2022-06-02 at 21 33 23" src="https://user-images.githubusercontent.com/40512816/171775377-a90dc575-8aa9-4154-ace6-45543e9a99c3.png">

The cell definition looks like this:

```xml
<cell colspan="12" defaulttype="table" id="8" initialize="sortField=countAmt" name="preparations" rows="3" type="subview" viewname="Preparation" />
```
