### ISSUE TITLE
Browse in Forms does not like jumping to the end of the view set

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1721]
Found in KUBirds
I created a query that consisted of Specific Locality (locality name) and GeodeticDatum (datum), added the criteria contains "Lawrence" for the locality name, and clicked query.
I clicked to Brose results in form.  there were 1155 results
It jumps from one record to the next easily but when you click to go to the end, you can see the bouncing logo for minutes at a time.  I stopped the timer at 10 minutes waiting for it to get to the end.

**Comment by maxxxxxdlp** [comment]
The issue is that it has to fetch all 1155 query results before it can display the last one. It is rather inefficient in that regard. The record sets in comparison have a bit more complex logic to fetch only what is needed and to leave "holes" where not-yet-fetched records should be.
I didn't yet add that login in query builder because of the added complications, which can inherently lead to more bugs (the record sets have that feature, and have had lots of bugs discovered in them in the last 4 weeks)
Another reason I didn't implement this feature yet is that if someone wants to go to the last record, just reverse the sort order in the query fields, after all, query results are sortable!

**Comment by grantfitzsimmons** [comment]
Still waiting for a long... long... long time. Jumping through 91,260 records. How does this fix work?

https://freshfish-testability.test.specifysystems.org/specify/query/43/

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons This ia bug.
Happens because of a race condition (if you click on the `>>` button while query results are already being fetched)

**Comment by chanulee1** [comment]
Able to go to last record without waiting for a long time.
db: `freshfish`
