### ISSUE TITLE
maximum recursion depth exceeded, Python

### ISSUE THREAD

**Issue by museonacionalcr** [specify/specify7#1757]
**Describe the bug**

**To Reproduce**
1. Go to Data Entry, New Collection Object
2. Click on 'Agent'
3. Start writting something 

**Expected behavior**
A list of agents

**Screenshots**

<img width="530" alt="image" src="https://user-images.githubusercontent.com/82953677/174117157-1d11d6f0-4a47-4ef3-8bb6-81ae4990e088.png">

**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Browser edge
 - Specify 7.6.1 

**Reported By**
National Museum of Costa Rica

**Comment by benanhalt** [comment]
Please send the data that is returned by the following:

http://specify.museocostarica.go.cr:8085/context/app.resource?name=TypeSearches

**Comment by museonacionalcr** [comment]
Thanks, I don't know how to send you the required information, now what I noticed is that the error occurs in a specific collection, but not in the other collections.

**Comment by benanhalt** [comment]
I suspect the problem is related to how the agent search is defined for that collection. If you copy the URL given above into your browser location bar while logged in to the affected collection, it should return some XML data that contains the search definition.  It should look like this:
![image](https://user-images.githubusercontent.com/287254/174333899-4ae7c04a-9c71-482c-9986-23d0f8ebc2d1.png)

You can save the XML by right-clicking on the page and selecting "Save page as.." Sending us that XML data by attaching it to this issue may help diagnose the problem. Thanks!

**Comment by museonacionalcr** [comment]
Thanks Ben,  This is what the XML return : 

<img width="677" alt="image" src="https://user-images.githubusercontent.com/82953677/174341790-980f88db-cb89-4422-8a40-15da82716a83.png">

<img width="666" alt="image" src="https://user-images.githubusercontent.com/82953677/174341904-207532ba-4c20-4a5c-aeb5-cd6a5b540af6.png">

**Comment by museonacionalcr** [comment]
It´s look like thi
[DataObjFormatters.txt](https://github.com/specify/specify7/files/8929696/DataObjFormatters.txt)
s :

**Comment by museonacionalcr** [comment]
Hi Ben, I managed to correct the error, in the bird DataObjFormatters in the agent configuration I changed the last line

<fields value="3">
                <field format="Agent">organization.organization</field>
            </fields>

to lastname and it worked

Thanks for your Help
