### ISSUE TITLE
Databases from Specify 7 can't be restored into MySQL

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1763]
I backed up a database from the test server (shell museum and kubirds) and tried to restore them into another instance for testing and got the same error message with both (different line for the issue though)
ERROR 1071 (42000) at line 9936: Specified key was too long; max key length is 3072 bytes
When I look at the line, in the appropriate database it says is the problem, it says "CREATE TABLE 'spuserexternalid'

**Comment by maxxxxxdlp** [comment]
This is a bug in the test-panel, not Specify 7.
See https://github.com/specify/specify7-test-panel/issues/50
As a workaround until that bug is fixed, you can download the databases from the test-server using MySQL Workbench

**Comment by benanhalt** [comment]
Nope. It's a MySQL / Mariadb inconsistency. MySQL doesn't support uniqueness constraints on fields longer than 3072 bytes. Mariadb does. Since we've only tested extensively on Mariadb so far, it just now came up. I think it would probably also happen if you tried to update a database to 7.7.0 in MySQL. Although Django might detect that it is MySQL and change the index somehow. I haven't tried it. For now I'm just going to drop the uniqueness constraint on external user ids.

**Comment by benanhalt** [comment]
Okay after the new build is appiled on the test server, the automatic migrations should drop the constraint, and affected databases should be restorable under mysql.

**Comment by grantfitzsimmons** [comment]
Verified this is working properly with KUBirds and Shell Museum.
