### ISSUE TITLE
Title field should fill in automatically when attaching a file

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1764]
It is filled in automatically by 6 and is the main field in the default forms and required in the XML

**Comment by maxxxxxdlp** [comment]
Fixed by using fileName as title to match Specify 6 behavior.

Note, the attachments table also has a `origFileName` field, which is populated in Specify 6 with the full path to the file on the user's computer. Specify 7 won't be able to replicate that behavior because modern browsers don't expose the original file path when user uploads file.
