### ISSUE TITLE
Checkboxes should have all labels to the right

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1780]
![image](https://user-images.githubusercontent.com/37256050/176456212-add59457-6ec5-4855-a16a-9391fc6cd2cd.png)

In 7.6.1 this behavior is already present. It looks messier on the new update.

**Comment by grantfitzsimmons** [comment]
![image](https://user-images.githubusercontent.com/37256050/176456808-c2ea3090-9267-464b-a2e4-22dd8fd585b8.png)

**Comment by maxxxxxdlp** [comment]
The new form rendering engine automatically associates a label with a field if:
- Label is not associated with any other field
- Label immediately proceeds the field
- Field has an ID
- Field type is not `command`

This is done to prevent having fields that don't have any associated label, in case the person who edited the form forgot to associate a label with that field.

In this case, the form definition has a label cell adjustent to the checkbox, so the form system uses it as a label for the checkbox, instead of creating a new label to the right of the checkbox:

<img width="722" alt="Screen Shot 2022-06-29 at 20 41 24" src="https://user-images.githubusercontent.com/40512816/176574382-0f2cd7ee-d5cd-4f32-ac0a-03aded0f49ef.png">

I belive the form definition is done this way to imitate a blank cell, as sp6 has no support for blank cells.

This is not needed in the new release since Sp7 now has support for blank cells - https://github.com/specify/specify7/wiki/Form-System#blank.

Alternatively, they can make that cell have `colspan="2"` and `align="right"`, which would have the same visual result.


Still, I think I should fix this in the rendering engine so that the forms look consistent after the update. Fixed by disabling the label auto-linking behavior for checkboxes.
