### ISSUE TITLE
User roles on an institution level not appearing under users

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1787]
![chrome_iqvwGnrL5S](https://user-images.githubusercontent.com/37256050/176781475-d220c32e-b4a0-4cb7-a704-1f22220743a0.gif)

db: `kufish`
user: `abentley`

**Comment by maxxxxxdlp** [comment]
The roles from the role library can not be assigned to a user directly.

Roles can only be assigned at the collection level.

To assign a role to a user, you have to create that role in a given collection.

The purpose of the role library is that it can be used as a template when creating new roles at the collection level.

Additional use case is that some account might have a permission to create a new role from a role library, but not to edit it, which would essentially mean that this user can only give some predefined permissions to people, rather than arbitrary permissions.
