### ISSUE TITLE
Allow front-end to send notifications

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1816]
It would be useful to have a back-end endpoint for sending arbitrary notifications to arbitrary users.

The endpoint would keep track of who sent the message and to whom.

This would allow the front-end to send notifications for things like transfer of ownership (#1146), dataset upload completed, and etc.

**Comment by benanhalt** [comment]
My concern with this is one of scope creep. The notifications were intended just for alerting users to the completion of long running tasks. Allowing notifications to be produced by the activities of another user is edging into chat system territory. I think the main motivation for this feature is to support "transfer of ownership" of resources. But I think we should explore a sharing/copy mechanism instead. For instance, you can already share a query with another user by giving them the link. I think this is better because the user can then use the communication channel of their choice to send the link.

**Comment by maxxxxxdlp** [comment]
Good call.
I will try to enable "URL sharing" and cloning for all resources.
Will reopen this if neede
