### ISSUE TITLE
Add ability to configure shown tables in Data Entry

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#1817]
Similar to #607 but for data entry

**Comment by melton-jason** [comment]
The Selected Tables column on the custom settings page seems to always load with a specific set of tables, regardless of what the visibility for tables currently is (See attachment below). 
![isssue_1817](https://user-images.githubusercontent.com/64045831/189358315-5239fbec-c935-4967-b366-7ece51ffb7cf.png)

(Tested on the botany and Invertpaleo databases)

---
Steps to Reproduce:
1. Click on Data Entry
2. Click on Edit (Pencil Icon)
3. Use custom settings
4. The Selected Tables column will now "reset" to the specific set of tables (as shown above)

Specify should store the user's custom settings (or current table visibility) and use that to populate the Selected Tables column, rather than a static set

**Comment by grantfitzsimmons** [comment]
I was able to recreate @melton-jason's discovery. This should be resolved before release!

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp I'm not seeing this fix

**Comment by maxxxxxdlp** [comment]
Sorry, it wasn't pushed yet. Should be there now (or after the test panel rebuilds 🙂 )

**Comment by grantfitzsimmons** [comment]
I'm seeing it now. Great work!
