### ISSUE TITLE
attr tables are showing up in the query builder

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1846]
Attr tables (collection object attr and preparation attr) are showing up both as tables and fields in the query builder.  Neither should be showing up.

**Comment by maxxxxxdlp** [comment]
Can you elaborate more on the "neither should be showing up" part? Do you mean the fields should be completely removed, or simply hidden unless the "Reveal hidden fields" checkbox is checked?

And also, what do you mean by "showing up both as tables and fields"? By showing up as a table, you mean it can be selected as a base table for a query?

You also did not mention the database. Looking at `kufish`, I see that the relationship from Collection Object to Collection Object Attribute is not marked as hidden, which is why it is showing up:

<img width="1800" alt="Screen Shot 2022-07-18 at 20 40 44" src="https://user-images.githubusercontent.com/40512816/179645657-ad847212-98ca-482f-8f0f-22b147858e28.png">

**Comment by grantfitzsimmons** [comment]
I am not seeing this Attr table issue anywhere. I unhid these in the schema on `kufish`, therefore it might appear to be a bug without that in mind. Should these two tables be banned from the QB? It seems if they are hidden there should not be any issues with them.
