### ISSUE TITLE
Mix the tables and fields in the query builder

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#1847]
Do not separate the related tables and fields in the query builder.  It makes it harder to find the correct fields because you mentally have to do two step processing to find a field and users may not realize at first that the field is actually a table.
Makes it more user intuitive

**Comment by maxxxxxdlp** [comment]
We made this decision initially for WorkBench.

Some of the reasons:
- Since fields are relationships are separated, each group is smaller in size, making it easier to find what you are looking for, if you know whether you are looking for a field or a relationship
- Since fields and relationships are visually distinct (relationships have a table icon and an arrow right), separating them increases consistency.

There were probably more reasons, but I don't remember at this point.

Reversing this decision is possible, but should be done both for the WorkBench and the Query Builder for consistency
