### ISSUE TITLE
Use more muted colors for the taxon tiles

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1859]
![image](https://user-images.githubusercontent.com/37256050/179847426-1c737677-8af8-4e28-8d9c-6b0f94e7e506.png)

`testability` on the left, `7.7.0` on the right

This is subjective and my opinion. In light mode, the colors are very bold after the tiles were rewritten.

Please close if you believe I am wrong in this.

**Comment by grantfitzsimmons** [comment]
Since this is low priority, will close.

**Comment by maxxxxxdlp** [comment]
those colors are one of the default color schemes
maybe add a `saturation(0.9)` CSS filter?

**Comment by grantfitzsimmons** [comment]
This has been asked about by Sarah at VIMS today.

> One more questions about tiles. Is it possible to edit the color scheme of the tiles? I love the colors on the Specify 7 website: https://www.specifysoftware.org/products/specify-7/
> 
> But my colors are different:
> ![image](https://github.com/specify/specify7/assets/37256050/1c6635b0-7c86-462a-ac3b-c3c6faa7c856)

**Comment by maxpatiiuk** [comment]
If I remember correctly, the color scheme changed because when I update the library (d3 - we were using almost a decade old version), the previous color scheme was no longer offered.

the color scheme is used here:
https://github.com/specify/specify7/blob/b5cea855b6a36c4ddaf1d22d674f6f42d2940ef7/specifyweb/frontend/js_src/lib/components/HomePage/taxonTileHelpers.ts#L135

it's just an array of hex strings - we can easily customize it (or a bit less easily, let users customize it, though I would rather we come up with good defaults on this one, than shift responsibility for fixing this to the user)
