### ISSUE TITLE
Save crash report as a JSON

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1866]
The file is saved as a .txt currently. The only way to make this file intelligible is to have it be a JSON file by default.

**Comment by maxxxxxdlp** [comment]
This was intentional. JSON files can't be attached to a GitHub issue (I know. It's crazy). 

See https://github.com/isaacs/github/issues/1130

Another solution is to produce a zipped json file, but browsers can't create a zip archive natively (not without some 3rd party giant library)

We could also produce `.gz` archives though - https://developer.mozilla.org/en-US/docs/Web/API/Compression_Streams_API, but those can be opened easily only on mac os and linux, not on windows


See more - https://github.com/specify/specify7/blob/532441f16ffdf376e85f4ba2971042ad9bc64b08/specifyweb/frontend/js_src/lib/components/errorboundary.tsx#L85-L93

**Comment by maxxxxxdlp** [comment]
I don't think it is a big loss. The file is not really meant to be editable or readable by the user.

It's only meant for them to send it to us.

And even if they need to edit it, a `.txt` file is still editable in any text editor. Once they open it, they would see that it's a `.json` file and would be able to change the syntax highlighting in the text editor.
