### ISSUE TITLE
[Sp.77] - when using European date format, aggregated dates are broken for any day over the 12th of the month

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#1908]
**Describe the bug**
I'm assuming this is to do with EU (DD/MM/YYYY) vs US (MM/DD/YYYY) formats.  

what I see is that for dates that i'm trying to display aggregated, they display correctly if the day is between the 1st and 12th of the month.  
any higher, and they display todays date instead, instead of displaying the collected date.  

screenshot below illustrates - compare the aggregated, to the separated out fields:
![image](https://user-images.githubusercontent.com/8005676/181207223-70c38dee-83c1-42b9-a8ec-fd9305675e2b.png)

This feels like an important one to fix in the upcoming patch - especially as it results in incorrect data being shown - we see todays date, not an error.  

**Reported By**
RBGE

**Additional context**

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Is this related to the other date issues you have been working on?

**Comment by grantfitzsimmons** [comment]
I am able to recreate- we definitely need to fix this.

![Uploading image.png…]()

**Comment by benanhalt** [comment]
This appears to be a front end issue. The data coming back from the server is correct. NB that the response has the date format selected for the database pre-applied.

![image](https://user-images.githubusercontent.com/287254/181380854-f3a9557a-bc84-48a9-8456-b243aab2a02a.png)

**Comment by maxxxxxdlp** [comment]
Same cause as https://github.com/specify/specify7/issues/1875 - there is a bug in our date parsing library - it doesn't support `mm/dd/yyyy` format.

#1875 was fixed by adding a workaround in date picker. I forgot to add the same workaround in other places where the date parsing is used.

Though, Ben is correct - the date should not be formatted by the front-end at all, as it is already formatted by the back-end

**Comment by benanhalt** [comment]
Ordinarily it would make sense for the dates to be formatted by the front end to allow more user customization. But in this case, because the query engine handles object formatting and aggregation of records which can also entail date formatting, it is more consistent to apply the date formatting as part of the same process. The reason for the query engine to handle data object formatting and aggregation instead of the UI is avoiding the "N + 1" query problem where formatting each row of the query results requires the front end to make subsequent requests of the back end / RDBMS to provide the extra info needed to format or aggregate.
