### ISSUE TITLE
Generate Label on Save not working

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#191]
In the demo database, I checked the Generate Label on Save checkbox, made a change to the record, and clicked Save.  It did not generate a label or pop up a dialog asking which label template I wanted to  populate, as it should have done since there is more than one label template it could have used.

**Comment by timo11** [comment]
Should work for any form if a check control named 'printOnSave' is added, with other attributes similar to the generateLabelChk control on the loan form.
If more than one report based on the table is available a chooser dialog will appear
If a report has parameters a parameter setting dialog will appear
The checked state of the controls is saved in a cookie per user/per table.

**Comment by yvonneekanim** [comment]
The button works, however, no reports/ labels are created. Upon saving, a pop up field appears containing "reports" and "labels" but clicking on either does nothing.

**Comment by yvonneekanim** [comment]
Tested this in a test database. A pop up showing label templates appears upon saving but quickly disappears right after. No labels are printed or created.

**Comment by yvonneekanim** [comment]
Tested this, works with no errors

**Comment by garrettgirard** [comment]
This may not be fixed totally. I just tried to generate a loan invoice on save and got the following error (in developer tools):
resourceapi.js:278 unhandled setting of relationship field workbenchtemplate on SpReportResource {specifyModel: s…a.Model, dependentResources: {…}, cid: "c641", attributes: {…}, collection: SpReportLazyCollection, …} value is null
  | _handleInlineDataOrResource | @ | resourceapi.js:278
-- | -- | -- | --
  | _handleField | @ | resourceapi.js:225
  | (anonymous) | @ | resourceapi.js:204
  | iterator | @ | underscore.js:184
  | (anonymous) | @ | underscore.js:199
  | set | @ | resourceapi.js:203
  | Backbone.Model | @ | backbone.js:244
  | constructor | @ | resourceapi.js:66
  | ResourceBase | @ | VM3988:5
  | SpReportResource | @ | VM4830:5
  | _prepareModel | @ | backbone.js:865
  | add | @ | backbone.js:600
  | update | @ | backbone.js:767
  | options.success | @ | backbone.js:816
  | options.success | @ | backbone.js:1430
  | fire | @ | jquery.js?27d9:3232
  | fireWith | @ | jquery.js?27d9:3362
  | done | @ | jquery.js?27d9:9834
  | callback | @ | jquery.js?27d9:10300
  | XMLHttpRequest.send (async) |   |  
  | send | @ | jquery.js?27d9:10243
  | ajax | @ | jquery.js?27d9:9732
  | Backbone.ajax | @ | backbone.js:1448
  | Backbone.sync | @ | backbone.js:1441
  | sync | @ | backbone.js:584
  | fetch | @ | backbone.js:819
  | fetch | @ | collectionapi.js:140
  | getReport | @ | reports.js:117
  | initialize | @ | reports.js:53
  | Backbone.View | @ | backbone.js:1236
  | ReportListDialog | @ | VM4057:5
  | (anonymous) | @ | reports.js:549
  | fire | @ | jquery.js?27d9:3232
  | fireWith | @ | jquery.js?27d9:3362
  | (anonymous) | @ | jquery.js?27d9:3418
  | fire | @ | jquery.js?27d9:3232
  | fireWith | @ | jquery.js?27d9:3362
  | done | @ | jquery.js?27d9:9834
  | callback | @ | jquery.js?27d9:10300
  | XMLHttpRequest.send (async) |   |  
  | send | @ | jquery.js?27d9:10243
  | ajax | @ | jquery.js?27d9:9732
  | Backbone.ajax | @ | backbone.js:1448
  | Backbone.sync | @ | backbone.js:1441
  | sync | @ | backbone.js:584
  | fetch | @ | backbone.js:819
  | fetch | @ | collectionapi.js:140
  | module.exports | @ | reports.js:548
  | (anonymous) | @ | specifyapp.js:90
  | triggerEvents | @ | backbone.js:98
  | trigger | @ | backbone.js:187
  | saved | @ | resourceview.js:131
  | triggerEvents | @ | backbone.js:102
  | trigger | @ | backbone.js:187
  | fire | @ | jquery.js?27d9:3232
  | fireWith | @ | jquery.js?27d9:3362
  | done | @ | jquery.js?27d9:9834
  | callback | @ | jquery.js?27d9:10300
  | XMLHttpRequest.send (async) |   |  
  | send | @ | jquery.js?27d9:10243
  | ajax | @ | jquery.js?27d9:9732
  | Backbone.ajax | @ | backbone.js:1448
  | Backbone.sync | @ | backbone.js:1441
  | sync | @ | resourceapi.js:522
  | save | @ | backbone.js:470
  | save | @ | resourceapi.js:440
  | doSave | @ | savebutton.js:99
  | _fulfilled | @ | q.js:834
  | (anonymous) | @ | q.js:863
  | Promise.promise.promiseDispatch | @ | q.js:796
  | (anonymous) | @ | q.js:556
  | runSingle | @ | q.js:137
  | flush | @ | q.js:125
  | onNextTick | @ | main.js:64
  | Item.run | @ | browser.js?6f0e*:64
  | drainQueue | @ | browser.js?6f0e*:34
  | setTimeout (async) |   |  
  | process.nextTick | @ | browser.js?6f0e*:54
  | exports.setImmediate | @ | main.js:57
  | nextTick | @ | q.js:180
  | Promise.then | @ | q.js:856
  | submit | @ | savebutton.js:84
  | dispatch | @ | jquery.js?27d9:5227
  | elemData.handle | @ | jquery.js?27d9:4879

**Comment by timo11** [comment]
works for me.
What database and invoice is crashing?

**Comment by garrettgirard** [comment]
Bishop, loan invoice. 
 
  On Wed, Jun 13, 2018 at 1:13 PM, timo11<notifications@github.com> wrote:   
works for me.
What database and invoice is crashing?

**Comment by timo11** [comment]
It works for me with the bishop db also; entomology collection. 
I had to remove all the font specifications because I did not have the fonts in my java path. 
But no problems with SpReportResource.workbenchtemplate

**Comment by yvonneekanim** [comment]
I'm getting this error with loan invoices specifically. Labels work fine 

Request Method: | POST
-- | --
http://db1.biwebdbtest.nhm.ku.edu/report_runner/run/
1.10.2
ReportException
<html> <head> <meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1"/> <title>Error 500 Server Error</title> </head> <body><h2>HTTP ERROR 500</h2> <p>Problem accessing /report. Reason: <pre>    Server Error</pre></p><h3>Caused by:</h3><pre>net.sf.jasperreports.engine.JRException: Byte data not found at: undefined?coll=&amp;type=O&amp;filename=02065077-d83d-49d2-b370-99975c703d73.jpg&amp;downloadname=&amp;token=. 	at net.sf.jasperreports.repo.RepositoryUtil.getBytesFromLocation(RepositoryUtil.java:210) 	at net.sf.jasperreports.renderers.util.RendererUtil.getNonLazyRenderable(RendererUtil.java:145) 	at net.sf.jasperreports.engine.fill.JRFillImage.evaluateImage(JRFillImage.java:534) 	at net.sf.jasperreports.engine.fill.JRFillImage.evaluate(JRFillImage.java:478) 	at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:381) 	at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:500) 	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillTitle(JRVerticalFiller.java:311) 	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:247) 	at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:115) 	at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:580) 	at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:414) 	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:121) 	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:667) 	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:983) 	at edu.ku.brc.specify.reports.ReportServlet.doPost(ReportServlet.java:47) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684) 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503) 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557) 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086) 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429) 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020) 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255) 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) 	at org.eclipse.jetty.server.Server.handle(Server.java:370) 	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494) 	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982) 	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043) 	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865) 	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) 	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696) 	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53) 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) 	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) 	at java.lang.Thread.run(Thread.java:748) </pre> <hr /><i><small>Powered by Jetty://</small></i><br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                 <br/>                                                  </body> </html>
/home/anhalt/specify7-develop/specifyweb/report_runner/views.py in run, line 46
/usr/bin/python
2.7.3
['/home/anhalt/specify7-develop/virtualenv/lib/python2.7/site-packages',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-linux2',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/home/anhalt/specify7-develop']

**Comment by benanhalt** [comment]
That is bug #482. The invoice must be referencing an image.
