### ISSUE TITLE
[sp7.7] query Combo Box search algorithm ignored for some search boxes.  

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#1935]
Sp7.7 adds a new preference to choose QueryCbx search algorithm.  I have it set to starts with:
![image](https://user-images.githubusercontent.com/8005676/182833843-5b91a8b4-77fb-4afb-b127-a0e35d678c6c.png)

for some QueryCbx this seems to be applied correctly, and we only see searches on the start of the field.  great!
As an example, this is the behaviour of the QBX in the new collection object qindow, determination subform for selecting taxon:
![image](https://user-images.githubusercontent.com/8005676/182834387-f4f89475-1205-4c7d-aa42-298ab7d41682.png)

other QueryCbx seem to ignore this setting.  e.g. when selecting the parent of a new taxon:
![image](https://user-images.githubusercontent.com/8005676/182834644-4bdadade-2430-468d-a396-7e44bbe5a431.png)

I've altered the XML of the new taxon parent QueryCbx to be as similar as possible to that used in the wrking ones, and still see this behaviour.  
XML is:
                        <cell type="field" id="parent"  uitype="querycbx" colspan="7" initialize="name=Taxon" name="parent"/>

Thanks.

**Comment by benritchie** [comment]
I've not been able to spot a convincing pattern of when this is and isn't broken.  my only theory is that its possibly broken for required fields?

**Comment by maxxxxxdlp** [comment]
There was an overwrite to always use a "Contains" algorithm when searching for a tree record.
There was also a bug, where instead of checking whether the query combo box is connecting to a tree table, it was instead checking whether the query combo box is rendered in a tree table.

Fixed the bug.
Also, added an independent user preference for specifying the query combo box search algorithm for tree tables.
