### ISSUE TITLE
Bulk-assign users roles

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1943]
There should be an option to bulk assign roles to a group of users. There are times when a group of 20 or more users are coming in and must be added to the institution, but assigning roles to all of them under each collection can be extremely tedious.

**Requested By:** Dan from CSIRO

**Comment by maxxxxxdlp** [comment]
Fixed in #1708

**Comment by maxxxxxdlp** [comment]
#1708 allows to assign several users to a role at once.

Assigning roles to several users between several corrections at once is a much harder UI challenge. If that's indeed that desired feature, feel free to reopen this issue

**Comment by grantfitzsimmons** [comment]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/37256050/182975259-13e8e347-15e8-44c6-b953-c0d0c650420f.png">

On `edge`, `KU_Fish`. I am not able to select multiple users- is this what you are talking about?

**Comment by maxxxxxdlp** [comment]
It's not on edge
It's on testability
For future reference, you can find out what branch the issue is fixed on in two ways:
If issue has a pull request, the pull request will say the current branch
Otherwise, on the issue page there would be a link to the commit(s) that fixed this issue. Click on any of them and you will see the branch name right under the commit message

**Comment by grantfitzsimmons** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/37256050/183150228-aa66ea0c-159a-4535-a405-1d87cfdd07e1.png">

Great!
