### ISSUE TITLE
Support advanced DataObjFormatter features

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#1961]
There are a number of DataObjFormatter features supported by Sp6 that are not available in Sp7:
- ~~Nested `<switch>`~~  **not supported as they aren't supported in sp6 either**
- Relationship in `<switch>` definition
- External formatter (reference to a different formatter)

**Comment by maxxxxxdlp** [comment]
External formatters are not going to be supported in sp7 as they are a hacky solution even in sp6 (there is no UI for editing external formatters - they literally reference a java class name that has custom logic)

**Comment by maxxxxxdlp** [comment]
To test:
- Open the Formatter editor
- Set a relationship field for a "Condition"
- Test that it works like expected
  - Related resource (-to-one) will be converted to a string using default formatter
  - Related resources (-to-many) will be converted to a string using default aggregator
  - In either case, the condition value will be compared against the formatted/aggregated resource string

**Comment by chanulee1** [comment]
Condition field for -to-many relationships not working.

https://user-images.githubusercontent.com/103299204/232591760-a3480e33-f00d-46d6-9577-0af8a8d4e89c.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/190/formatter/CollectionObject/17

Should nested `<switch>` be tested as well? If so, how?

**Comment by maxxxxxdlp** [comment]
> Should nested <switch> be tested as well? If so, how?

They are not supported in sp7 as they weren't implemented in sp6 either. Updated the issue description to mention that

> Condition field for -to-many relationships not working.

This is not a bug in the XML Editor. The problem is that when you aggregated determinations in the query builder, query builder returns wrong results. This is because aggregator for determination table has `limit="1"`, but query builder ignores that limit (see https://github.com/specify/specify7/issues/1144). Front-end does not ignore that limit.

That is why in the query results you see `Hexanchiformes, Lamniformes`, but the XML editor is actually looking for `Hexanchiformes`

It all works correctly after that:

![Screenshot 2023-05-01 at 08 49 22](https://user-images.githubusercontent.com/40512816/235461036-df4e6ed2-0c24-4c97-9373-69cca7ca4c1e.png)
