### ISSUE TITLE
[testability] Cannot view Locality

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1969]
![image](https://user-images.githubusercontent.com/37256050/184886022-bf8abb3b-d282-4887-b827-ff78e58e1f80.png)

I get the following error when viewing a locality:
`can't traverse into a collection using dot notation`

db: `KU_Fish`

**Comment by maxxxxxdlp** [comment]
The `CollectionObjectSub` view definition, which is used as a sub form on the `CollectingEvent` form has a mistake.

It has a field with fieldName of `determinations.taxon.fullName`.

Since `CollectionObject --> Determinations` is a -to-many relationship, this field name is not supported.

Previously, this was just logged as an error in the console. Now, it throws a modal dialog. I will return it to it's previous behavior.

@grantfitzsimmons can you please check how Specify 6 handles this case? It does not seem valid, and I am quite sure it was never supported in Sp7
