### ISSUE TITLE
Collection access should be required when a role is selected

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1994]
![image](https://user-images.githubusercontent.com/37256050/185408687-e32317d8-448e-4dde-92fd-55a79393b490.png)

> Then I tried again and saw that there is an ‘enable collection access’ button, which you have to check before selecting ‘full access user’.
> 
> Perhaps the design of this interface just needs to be improved a bit.

**Reported By:** Willem

**Comment by maxxxxxdlp** [comment]
It was made this way intentionally (though, we could make it more clear in the UI)

The primary use case is that you have a user with lots of roles, policies and collection access.

Then, if you need to temporary disable the user (they go into a leave, or on vocation), instead of removing all of their permissions and setting them all back when the user returns, you simply uncheck "Collection Access" in each collection they have access too.
Withough collection access, the user won't even be able to log in, and is, pretty much disabled.
When the user returns, you check "Collection Access" again, and they have all of the previous permissions back.

If they don't like having to remember to check "Collection Access" in each user, they can add the "System -> Sp7 -> Collection -> Access" policy in a role, and then each user that has that role would also have collection access.

**Comment by maxxxxxdlp** [comment]
But, we should consider adding a warning message when trying to save a user with roles/policies, but without collection access, so as to explain the situation better.

**Comment by grantfitzsimmons** [comment]
I think the solution would be to make the list of roles read-only if they lack collection permissions.

**Comment by maxxxxxdlp** [comment]
The collection access policy may be coming from a role.

Do you see a use case for someone to create a role that gives that policy through a role rather than directly to a user?

I.e, collect a role "2022 interns". After summer, remove "Collection Access" policty from the role, and everyone from that role loses collection access.

**Comment by grantfitzsimmons** [comment]
Well, how about this:

- To select roles in the first place, you must have collection access given
- If there are already roles selected and you remove collection access, keep those roles checked and applied (just the user does not have collection access)

I see the second option being a better solution as there are likely users who have given collection access through a role already (I think I recall at least once instance of this)

<img width="910" alt="image" src="https://user-images.githubusercontent.com/37256050/229136673-b9524047-5211-41f4-8b0e-9a70d80ec3ba.png">

**Comment by maxxxxxdlp** [comment]
Can you clarify this a bit?
Do you mean that selecting roles when creating a user requires collection access, but if roles are already selected, removing collection access still allows editing the roles?

**Comment by maxxxxxdlp** [comment]
or should we just add a message next to roles section saying something like "Roles apply only if collection access was given" if collection access is not checked?

**Comment by CarolineDenis** [comment]
> or should we just add a message next to roles section saying something like "Roles apply only if collection access was given" if collection access is not checked?

This seems to be more clear.

**Comment by grantfitzsimmons** [comment]
Slack:

>You can grant collection access via a role
>
> And people have caused issues when they assign roles without granting collection access in that role
> 
> So the idea would be to require the user creating/assigning permissions to check the collection access role before selecting any roles
> 
> After they have assigned roles, they could remove collection access from the user by unchecking that box in the form, then the role check boxes would become read-only
> 
> This would make it so that existing setups won’t break but for new users it is clear how it should work. Ideally collection access would not be specified in a role very often…

Just add that message!
