### ISSUE TITLE
Collapsible subviews are missing

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#1995]
> The initialize="collapse=true" command in the form xml doesn’t appear to be working in S7. We have a subform in the collectionobject table that we’d like to open in a collapsed way. This works fine in S6, but not in S7.
>  
> `<cell type="subview" id="88" viewname="CollectionObjectProperty" name="collectionObjectProperties" colspan="14" initialize="collapse=true"/>`

In Specify 6, subviews could be collapsed. In Specify 7, this does not seem to be supported.

Apologies if this has already been mentioned.

**Reported By:** Corinna at CSIRO

**Comment by maxxxxxdlp** [comment]
This is a rather advanced issue and requires knowledge about specify 7 form system. If you are still interested in this, here is the information on how to get started fixing it:

---

On a front-end, this is what a SubView looks like (example shows Determinaion SubView on a Collection Object form):

<img width="1172" alt="Screenshot 2023-03-01 at 19 26 00" src="https://user-images.githubusercontent.com/40512816/222306900-2ba8a044-b566-437e-9e4c-3bea0ac91499.png">


> User Tools > App Resouces > Form Definitions and edit XML files

Yes, you are in a correct place. That's where form definitions are stored. The tricky is that forms are defined by users, and so Specify has to handle all kinds of form scenarios.

We have extensive documentation on the form definition XML - https://github.com/specify/specify7/wiki/Form-System

In particular, the section this issue talks about is this one - https://github.com/specify/specify7/wiki/Form-System#subview

That details which attributes are currently supported. The support needs to be added for making sub view be collapsed using the following XML attribute: `initialize="collapse=true"`

`initialize` is a special attribute from Specify 6 that allows to specify multiple configuration options at once (i.e, `collapse=true;btn=false;icon=test`).

To fix this issue, you need to:
- Add new attribute to this TypeScript type - https://github.com/specify/specify7/blob/89b4ba9d309a0b5440a15dd1edead42be0e9d174/specifyweb/frontend/js_src/lib/components/FormParse/cells.ts#L87 (it defines which properties are used by <SubView> when being rendered on the form)
- Add a new property to the sub view - https://github.com/specify/specify7/blob/89b4ba9d309a0b5440a15dd1edead42be0e9d174/specifyweb/frontend/js_src/lib/components/FormParse/cells.ts#L227 (i.e, `isCollapsed: getProperty('collapse')?.toLowerCase() === 'true',`)
- Then, you will be able to use the new prop here - https://github.com/specify/specify7/blob/89b4ba9d309a0b5440a15dd1edead42be0e9d174/specifyweb/frontend/js_src/lib/components/FormCells/index.tsx#L107 (it will be available in `cellData`)
- Finally, modify `<SubView>` itself to react in some way to `isCollapsed` being true. Here, youl would be to do research on how `initialize="collapse=true"` behaves in Specify 6 so that we can replicate the same behavior in Specify 7.
- Next, Modify the subview parsing tests to include the new prop - https://github.com/specify/specify7/blob/89b4ba9d309a0b5440a15dd1edead42be0e9d174/specifyweb/frontend/js_src/lib/components/FormParse/__tests__/cells.test.ts#L353-L389
- Don't forget to also add a new bullet point after https://github.com/specify/specify7/wiki/Form-System#subview:~:text=The%20default%20sort,or%20id. to describe what `collapse=true` does


There might be an additional difficulty in implementing this in Specify 7 - default values are not going to be set if the form is collapsed (because defaults are only set when the field becomes visible). @grantfitzsimmons How does sp6 handle this?

**Comment by cdamyx** [comment]
Wow, thanks for all the helpful info! I'll give it a shot - might take me a while :grin: Or do you think my efforts would be more worthwhile on a different issue first?

**Comment by maxxxxxdlp** [comment]
We are working on posting a long front-end overview video that will cover all of this in detail.
Until then, issues labeled with `good-first-issue` require less context knowledge about the inner workings of specify 7

**Comment by grantfitzsimmons** [comment]
> There might be an additional difficulty in implementing this in Specify 7 - default values are not going to be set if the form is collapsed (because defaults are only set when the field becomes visible). @grantfitzsimmons How does sp6 handle this?

Collapsed subviews default values are maintained. Maybe it renders the entire form and just makes it invisible?

**Comment by maxxxxxdlp** [comment]
Have to solve https://github.com/specify/specify7/issues/3094#issuecomment-1466907081 before this can be implemented

**Comment by grantfitzsimmons** [comment]
> Have to solve [#3094 (comment)](https://github.com/specify/specify7/issues/3094#issuecomment-1466907081) before this can be implemented

I may be wrong, but didn't we discuss a way to implement this without fixing that issue? Something involving rendering the form but hiding it from the user.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/option-to-collapse-form-sections-in-s7-like-you-can-in-s6/1162/2

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons yes, setting visibility:hidden might be the best solution

But, even that is not fullproof. Some edge cases to handle:
If field is rendered with visibility:hidden and has a validation error, it will prevent saving the form, but the error is not displayed on the screen. Also, the browser emits this error message (at least in Chrome):
![Screenshot 2023-05-10 at 08 30 40](https://github.com/specify/specify7/assets/40512816/37164de4-e0cf-4e0e-9844-63421979f641)

So we have to catch and properly handle that case (i.e, uncollapse the section or if it's a subview button, open the subview dialog)

**Comment by grantfitzsimmons** [comment]
Embarrassingly, I am supposed to review the associated PR. Sorry @CarolineDenis for not getting to this sooner.
