### ISSUE TITLE
Grid Format in forms not respecting align command

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#2013]
tested in the rbge database in the dashboard because they have an alternate view specifically for their preparation grid.

I added initialize="align=left" to the barcode label and initialize="align=right" to the storage field then selected a short storage value.  Neither aligned the way I said it should in the code.  I hadn't opened the forms for that database in 7 before editing the code, so I couldn't have been seeing a cached form.

**Comment by grantfitzsimmons** [comment]
Can we verify this is still an issue?

**Comment by CarolineDenis** [comment]
@specify/ux-testing

**Comment by emenslin** [comment]
Fixed

**Comment by melton-jason** [comment]
This issue had the same underlying issue as https://github.com/specify/specify7/issues/4737. 

That is, prior to https://github.com/specify/specify7/pull/4740 and https://github.com/specify/specify7/pull/4888 (both in `v7.9.4`), Specify would _always_ use the view name specified in the datamodel instead of the user-defined view to render subviews in table/grid mode.
