### ISSUE TITLE
Paleocontext should have an accepted field for lithostrat of chronostrat

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2016]
Lithostrat and chronostrat should have a field like `acceptedTaxon` for each respective tree. The default forms should be updated with this field visible. Currently, the only way to see whether it is accepted is to look at in the tree.

**Comment by tlammer** [comment]
More information from the user (Leslie Skibinski from PRIpaleo)
There is going to be a big, new Devonian strat chart update in the next little while.  We have two of the author’s collections and we haven’t assigned paleocontext to their material yet because of this new update.  We have some tentative, unpublished, but in proof charts that we would like to enter in the litho tree.  What we were wondering was if we could enter the new things into the tree and synonymize some of the old litho names in the tree?

**Comment by grantfitzsimmons** [comment]
Fixed in https://github.com/specify/specify7/commit/9afc9883657ee9d0b7079ac4d9048ccbd1f1c20b
