### ISSUE TITLE
Permission error when Collection Admin tries to create a new user

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#2019]
<img width="1200" alt="Screen Shot 2022-08-23 at 12 42 01" src="https://user-images.githubusercontent.com/40512816/186227788-5481530c-39ff-4f9d-b5a5-947b869dc923.png">

**Comment by maxxxxxdlp** [comment]
@benanhalt Is `/permissions/list_admins [update]` enforced on the collection level or institution level?

How can I check what level it is enforced at when looking in the back-end code?

This is the list of policies that the front-end currently treats as being institutional only. Can you double-check if the list is exhaustive?

```js
  '/admin/user/password',
  '/admin/user/agents',
  '/admin/user/sp6/is_admin',
  '/admin/user/invite_link',
  '/admin/user/oic_providers',
  '/admin/user/sp6/collection_access',
  '/export/feed',
  '/permissions/library/roles',
```

**Comment by benanhalt** [comment]
I need to come up with a way to indicate which are institution resources... You can tell in the code if it is checking for institutional level if it has *None* for the collectionid in the permissions check:
```
        check_permission_targets(None, request.specify_user.id, [ListAdminsPT.read])
```
If it is enforcing it at the collection level it will look like:
```
        check_permission_targets(collectionid, request.specify_user.id, [PoliciesUserPT.read])
```

The list admins permission was added at the last minute because Jim requested it. I think it is a bit much. I made it institution wide because the admins are system wide. I can change it to enforce at the collection level.

OTOH it doesn't seem like adding a new user should require listing the admins.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-7-4-release-announcement/807/1
