### ISSUE TITLE
Weblink button only configurable through forms.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#202]
It should look at the schema localization, too.

**Comment by tlammer** [comment]
I tested it in KUHerps (record 55904) clicked the weblink button and it doesn't launch the page.  I logged into the 6 version on the bitestdb server and I was able to launch the weblink.

**Comment by tlammer** [comment]
tested in kuherps.  Was able to launch the webpage

**Comment by tlammer** [comment]
When I try to upload or validate a dataset that just has cat #, cataloger last name, and cataloger first name, with two records that have agents that match more than one existing record in the database, I get these messages:
pid = 10525
2016-03-25T22:27:58Z: starting with args [Suppressed]...
2016-03-25T22:27:58Z: Got master
2016-03-25T22:27:59Z: logged in
2016-03-25T22:27:59Z: Versions OK
2016-03-25T22:27:59Z: good user
2016-03-25T22:27:59Z: got collection name
2016-03-25T22:28:03Z: context established
2016-03-25T22:28:03Z: UploadCmdLine.LoadedWB
uploading row 0
uploading row 1
2016-03-25T22:28:04Z: UploadCmdLine.UploadFailed
2016-03-25T22:28:04Z: ...exiting UN-successfully.
17:28:03 ERROR specify.config.SpecifySchemaI18NService:168 - Couldn't find field[collectionMemberId] for table [paleocontext]
17:28:03 ERROR specify.config.SpecifySchemaI18NService:244 - Couldn't find field[collectionMemberId] for table [paleocontext]
17:28:04 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@68f776ee : 2016-03-25 17:28:04.532 was null
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderMatchSkipException: Row 1: Not uploaded due to multiple matches (Cataloger First Name = Ben, Cataloger Last Name = Miller)
17:28:04 ERROR datamodel.busrules.CollectingEventBusRules:131 - The PC null was null or the CE edu.ku.brc.specify.datamodel.CollectingEvent@277bc3a5 : 2016-03-25 17:28:04.679 was null
17:28:04 ERROR datamodel.busrules.CollectionObjectBusRules:731 - The CE null was null or the CO 400002 was null
17:28:04 ERROR datamodel.busrules.CollectionObjectBusRules:765 - The PC null was null or the CO 400002 was null
17:28:04 ERROR hibernate.util.JDBCExceptionReporter:78 - Cannot add or update a child row: a foreign key constraint fails (`KUHerps`.`collectionobject`, CONSTRAINT `FKC1D4635DB237E2BC` FOREIGN KEY (`CollectingEventID`) REFERENCES `collectingevent` (`CollectingEventID`))
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.exception.ConstraintViolationException: could not insert: [edu.ku.brc.specify.datamodel.CollectionObject]
17:28:04 ERROR org.hibernate.AssertionFailure:22 - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.AssertionFailure: null id in edu.ku.brc.specify.datamodel.CollectionObject entry (don't flush the Session after an exception occurs)
Caused by: edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.AssertionFailure: null id in edu.ku.brc.specify.datamodel.CollectionObject entry (don't flush the Session after an exception occurs)

I created this data set after the 248 bug was marked as closed by you, in case this is related.

**Comment by tlammer** [comment]
I did my test in KUHerps as testuser with the data set agent2 and testagent

**Comment by benanhalt** [comment]
This looks like the same thing as #247, but definitely not to do with the web link button.
