### ISSUE TITLE
[sp7.7] Specify crashes when entering duplicate barcode

### ISSUE THREAD

**Issue by benritchie** [specify/specify7#2061]
**Describe the bug**
If create a new preparation, with the same barcode as an existing prep, and hit save, then specify crashes.  
crash diags attached.   
Desired behaviour would be to display a useful popup to user explaining issue.  

Note, we are using preparations based workflow.  not sure if that's related?

**To Reproduce**
see above

**Expected behavior**
see above

**Desktop:**
seen on multiple browsers, windows 10 and 11
**Database Name:** rbge_herb

**Reported By**
RBGE

**Comment by benritchie** [comment]
[Specify 7 Crash Report - 2022-08-30T11_59_44.850Z.txt](https://github.com/specify/specify7/files/9452999/Specify.7.Crash.Report.-.2022-08-30T11_59_44.850Z.txt)
here's the crash report.  
datestamp was 30/8 at 12.13pm BST

**Comment by maxxxxxdlp** [comment]
@melton-jason related to what you are working on right now. We need to gradually make all errors on save dismissible starting with the ones that are safest.
Can you check if this is already caught by the front-end? Is it just a problem of user clicking "Save" before uniqueness checks were completed? In that case, we should make "Save" button wait for all uniqueness checks to pass before calling `.save()`

**Comment by melton-jason** [comment]
This is not already caught on the frontend, and it is not a uniqueness rule on the backend either. The error is a SQLAlchemy Integrity Error. 
The frontend only respected Uniqueness Rules defined on the frontend. If a rule was missing on the frontend, but existed on the backend, then the backend BusinessRuleException would be thrown. If the value is unique at a database level but missing in both front and backend, then a SQLAlchemy error would be thrown. 
 
> ... Is it just a problem of user clicking "Save" before uniqueness checks were completed? In that case, we should make "Save" button wait for all uniqueness checks to pass before calling .save()

This is highly unlikely, as it updates the save blockers as soon as it detects the field change and runs the checks. I will concede this is a possibility, however,  and an implementation should (hopefully) not be to hard.

**Comment by melton-jason** [comment]
The `Preparation.barCode` field is unique in the way it handles uniqueness (although there may be more cases I am unaware of), and will either require a separate system to be implemented to handle cases such as it, or be specifically hardcoded.

All other uniqueness constraints (save for a few on the `many` side of a `-to-many` relationship) are handled through a relationship (usually: collection, discipline, etc.) and the rules check all other records through the relationship and ensures a unique value in a field across all of a single model on 'this' side of the relationship--- like `CollectionObject.catalogNumber` must be unique to Collection (The specific Collection is defined through CollectionObject's relationship called `collection`). 

Another step needs to be added specifically for cases like `Preparation.barCode`. See my breakdown in https://github.com/specify/specify7/issues/2886#issuecomment-1409145291 for more information, but Preparation.barCode is handled through a _field_ rather than a relationship. The intermediate step will have to associate the field to a table in the database and then perform a query, after which the standard uniqueness rule process can be applied.

**Comment by maxxxxxdlp** [comment]
If it would be simpler, here is a different solution:
- Make resource save errors dismissible
- Continue the work you begun with pretty-printing back-end error messages and extend it to Integrity Errors

**Comment by melton-jason** [comment]
Fixed as of #4215 which will be included as part of the `v7.9.3` release. 
Additionally, this issue is the same as #2886 

![image](https://github.com/specify/specify7/assets/64045831/a5990ad1-b066-4c99-b1c1-f60c6ff98bff)
