### ISSUE TITLE
Cannot create a loan from preparations if catalogNumber has a space character in it

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2166]
https://user-images.githubusercontent.com/37256050/190781948-61849044-b4d1-429d-80b7-2cbab2cec337.mov

https://anfc-v772.test.specifysystems.org/specify/view/collectionobject/3/

catalogNumber: 
`287 Hel sp B (Indian Ocean) 01`

user: `pae008`
db: `ANFC`

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons can you set the appropriate priority for this (i.e, is this an actual user issue or a potential user issue)

**Comment by grantfitzsimmons** [comment]
There is a workaround, but this is going to affect CSIRO using Specify when they move to production in October.

_Current workaround is to create a record set from a query, then create a loan based on the record set._

**Comment by maxxxxxdlp** [comment]
This happens because their catalog number formatter has a regex like `.{1,31}`.

The interactions dialog checks if the regex includes the space or the comma symbols and excludes those from the list of possible separators.

`.` in regex stands for any character, but sp7 does not detect that.

Untill this is fixed properly, the short term workaround would be for them to modify the formatter to include a space character (i.e `(.| ){1,31}`)
