### ISSUE TITLE
Backspacing in the det.taxonname field triggers autocomplete

### ISSUE THREAD

**Issue by ianengelbrecht** [specify/specify7#2169]
**Describe the bug**
After selecting a name in the taxon name field of a determination, if I back space in the field, it takes a few backspaces then puts the name back again. For example, from an empty taxon name field, I add 'Gerrhosaurus flav', which gives me two picklist options. I select 'Gerrhosaurus flavigularis flavigularis'. Then if I backspace a few times it removed the characters, but then 'Gerrhosaurus flavigularis flavigularis' is added in again, and the cursor jumps back to the end of the string. This only happens with the backspace key, I don't get the same behaviour if I select part of the name and hit the delete key. 

**To Reproduce**
1. Select a taxon name in the det taxon field, and then hit the backspace key a few times.

**Expected behavior**
After backspacing, the picklist should appear again, and the name that was in the full string that was in the field should not be added back automatically.

**Screenshots**

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Specify 7 Version: 7.7.2

**Reported By**
Natural Science Collections Facility

**Additional context**
None

**Comment by chanulee1** [comment]
Seems to have same behavior. Compared `7.7.3` and `issue-2169`. Noticed that after the first autocomplete, backspacing again does not trigger autocomplete again.

https://user-images.githubusercontent.com/103299204/194125311-7b64dea9-723d-4caa-aefb-2cae6bb69ec3.mp4

**Comment by maxxxxxdlp** [comment]
So the fix is not working correctly?

If so, can you reject this pull request - https://github.com/specify/specify7/pull/2203 (Assign yourself as a "Reviewer", reload the page, add a review and select the option `Request Changes`)

Also, please specify the database in which this happened, as that would make it easier to replicate the issue (or, you could include the URL in your video captures, as URL includes database name)
