### ISSUE TITLE
[testability] Paginator buttons are showing as disabled 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2193]
![image](https://user-images.githubusercontent.com/37256050/191356086-5c163139-e7f8-4ce3-8d8e-d372f1b183fe.png)

The paginator button is showing as disabled but it works. This is the case for both the left and right arrows.

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/37256050/191356230-b63e1ba1-3db6-4476-bd4c-9326a96ff499.png">

**Comment by maxxxxxdlp** [comment]
I don't think this is a testability bug. It's confusing because we wanted to have different colors for the `>` and the `>>` buttons to make them easier to differentiate.

I reverted that to make them look the same (in light mode only). @grantfitzsimmons can you check if the new style is less confusing?

**Comment by grantfitzsimmons** [comment]
This is much less confusing!
