### ISSUE TITLE
[testability] Unable to export data set with pipe delimiter

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2244]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/37256050/192678801-94505af6-ab17-425c-bc03-2a2ef17b499b.png">

https://freshfish-testability.test.specifysystems.org/specify/workbench/2/

[Specify 7 Crash Report - 2022-09-28T03_10_29.790Z.txt](https://github.com/specify/specify7/files/9661119/Specify.7.Crash.Report.-.2022-09-28T03_10_29.790Z.txt)

<img width="849" alt="image" src="https://user-images.githubusercontent.com/37256050/192678868-5f27b965-c407-4d02-8140-25cf7c2714c8.png">

user: `abentley`

**Comment by maxxxxxdlp** [comment]
FYI, bug happened regardless of what delimiter was set

**Comment by chanulee1** [comment]
![image](https://user-images.githubusercontent.com/103299204/195892276-c06a3329-c271-4d3e-9e3c-096a52b2e7a7.png)

[Specify 7 Crash Report - 2022-10-14T16_10_46.329Z.txt](https://github.com/specify/specify7/files/9788104/Specify.7.Crash.Report.-.2022-10-14T16_10_46.329Z.txt)

<a href="https://user-images.githubusercontent.com/103299204/195892811-cf10c857-7132-43c0-a3df-4bb4cd768e5c.png">Console</a>

Happens when try to export with any delimiter.

**Comment by maxxxxxdlp** [comment]
Sorry, I did not push the fix yet. It is pushed now and will be available on the test server once it rebuilds

**Comment by chanulee1** [comment]
Able to export data set with pipe delimiter.
db: `freshfish`
user: `abentley`
