### ISSUE TITLE
[testability] System information is excessive

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2245]
https://user-images.githubusercontent.com/37256050/192680483-e9991e6d-78e7-4632-b3e0-2ae0599db061.mp4

[Specify 7 System Information - 2022-09-28T03_21_04.598Z.txt](https://github.com/specify/specify7/files/9661185/Specify.7.System.Information.-.2022-09-28T03_21_04.598Z.txt)

**Comment by maxxxxxdlp** [comment]
Is this a bug?

Most of the size comes from https://github.com/specify/specify7/issues/2184 (the HTML of the page is included in there)

The HTML is very useful in cases where people did not provide a screenshot, as I can recreate the way the page looked like from the HTML.

If it's not causing any problems, this should be closed

**Comment by grantfitzsimmons** [comment]
I created this issue before I saw #2184. After reviewing that change, I left this bug open because I still feel like it adds more than is necessary. It's not causing any problem, it just complicates it. I will close as it is not problematic. Thanks!

**Comment by grantfitzsimmons** [comment]
There is no value in the HTML in this instance. During error reports, I love the HTML feature!

The system information sharing only needs the info present in the dialog right?

**Comment by maxxxxxdlp** [comment]
Ah, you meant that the HTML is not useful for the system information dialog in particular. I would agree with you.
The reason it is still included is because the `Download Error Message` and `Download Information` generate the same file.

Making the output separate is possible but adds complication, while not adding much benefit (as file being a bit larger is not causing issues)

**Comment by grantfitzsimmons** [comment]
No need to complicate things. This is fine as it is :smile:
