### ISSUE TITLE
Agent Query Combo Box adding space before short names

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2333]
**Describe the bug**
The Agent Query Combo Box seems to be adding a space to the box after an agent has been selected with a small(see below video). This then messes with the search algorithms (regardless of what the user is using) and the text has to be entirely removed to make a similar query. 
I am not sure what the effective cutoff is for name length, but this bug is seemingly not occurring for long names.

**Screenshots**

https://user-images.githubusercontent.com/64045831/196284139-70a6ab65-c827-463f-944c-093a95d14aa2.mp4

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Specify 7 Version: testability

**Database Name:**
willemcatno

**Comment by maxxxxxdlp** [comment]
That's because first name is empty, and last name has a space before it according to the DataObjFormatter for Agent table:

<img width="1201" alt="Screen Shot 2022-10-24 at 19 37 11" src="https://user-images.githubusercontent.com/40512816/197655639-044f4552-5a6c-4095-b270-05ff09080535.png">

@benanhalt Do you see any problem with me trimming all formatted strings?

**Comment by benanhalt** [comment]
I don't see a problem with trimming the result. Probably the **sep** value should only be included if the preceding value is not null or empty, though.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
