### ISSUE TITLE
Record does not detect it has been saved

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2360]
![image](https://user-images.githubusercontent.com/37256050/198313659-7013dbb9-6c30-4d29-ae62-78e614e04663.png)

Correct behavior is being exhibited in `v7.7.3` (right), incorrect behavior in `v7.7.4` and `v7.7.5` (left).

After saving the CO record, the Clone and Add buttons are not functional.

![image](https://user-images.githubusercontent.com/37256050/198314191-28ff9928-4a5a-4972-9e25-92dc2cf3c161.png)

I suspect this is due to Specify believing that the form has an unsaved element. Not sure exactly why this is occuring, but it was introduced in `v7.7.4`. Probably related to the form in the `os` database.

user: `petek`

https://os-v773.test.specifysystems.org/specify/view/collectionobject/27541/

https://os-v774.test.specifysystems.org/specify/view/collectionobject/27541/

**Comment by maxxxxxdlp** [comment]
Their date field in the Preparation form has a wrong precision field name:

![Screen Shot 2022-10-27 at 11 03 48](https://user-images.githubusercontent.com/40512816/198341286-d72f7475-b58c-488a-ab67-b5232e534a24.png)

Changing `preparedDateDatePrecision` to `preparedDatePrecision` should fix it.

Let this bug stay open because specify needs to handle errors like this better

**Comment by CarolineDenis** [comment]
@grantfitzsimmons is this still an issue?

**Comment by maxxxxxdlp** [comment]
This is fixed in xml editor by displaying a validation error on invalid field name.
Let's keep this issue open until someone get's a chance to test the fix

**Comment by grantfitzsimmons** [comment]
This needs to be tested during `xml-editor` evaluation

**Comment by CarolineDenis** [comment]
Fixed in xml-editor
