### ISSUE TITLE
Navigating to an app resource has them unsaved by default

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2384]
<img width="1800" alt="image" src="https://user-images.githubusercontent.com/37256050/199320151-eaff3a23-6e05-4fd4-bd75-10878011da93.png">

**Comment by grantfitzsimmons** [comment]
Seems to be inconsistent. Once saved, doesn't happen again.

https://kufishnotests-testability.test.specifysystems.org/specify/resources/app-resource/90/

**Comment by chanulee1** [comment]
DwCA file is unsaved upon navigation.
<img width="700" alt="image" src="https://user-images.githubusercontent.com/103299204/201436418-9ece37bd-5826-44c6-89cf-e064488f57ad.png">
https://kufishnotests-testability.test.specifysystems.org/specify/resources/app-resource/137/

**Comment by maxxxxxdlp** [comment]
Actually, it is not marked as unsaved (because the "Clone" button is still enabled, and there is no unload plotect dialog when trying to navigate away from this page).
The reason the save button is not disabled is because the resource is invalid - there is a syntax error at the end of the xml file (you can see it by clicking on the "Save" button)
The "Save" button becomes enabled in cases like this so that you can click on it and see the error message

**Comment by chanulee1** [comment]
Ah, I see. App resources are saved by default.
