### ISSUE TITLE
Turning auto-numbering off and on creates an issue for Cat #

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2385]
https://user-images.githubusercontent.com/37256050/199320782-73b90c9f-37f0-429b-8bbb-e41e6c477560.mov

After switching auto numbering off, creating a new record, and switching it back on again, I was able to create a record with the catalog number "#########" in the forms. After searching for that string in the QB, I was able to verify Specify identified it as catalogNumber '0'. This happens whenever you recreate those steps.

Once you refresh the page, you can once again create catalog numbers and COs normally.

**Comment by maxxxxxdlp** [comment]
When you switched off auto numbering and saved the Collection Object, you created a Collection Object without a catalog number.
Since catalog number must be unique, there can only be one Collection Object without a catalog number.
Marking that field as required in the forms would fix this issue.

That's one issue. The other is that front-end should not populate the field with `#######` for existing resources, as back-end only treats that as a special value for new resources - fixed.

**Comment by chanulee1** [comment]
Cat # field not populated with `######` for existing records when auto-numbering is on.
db: `freshfish`
