### ISSUE TITLE
Specify crashes on record set with no collection objects

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2406]
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/37256050/200046438-128bab77-4daa-4884-ba00-74df0e4d3356.png">

`/specify/view/collectionobject/274877/?recordsetid=724`

https://willemcatno-edge.test.specifysystems.org/specify/view/collectionobject/274877/?recordsetid=724
https://willemcatno-testability.test.specifysystems.org/specify/view/collectionobject/274877/?recordsetid=724

`edge` on left, `testability` on right

**Comment by maxxxxxdlp** [comment]
There are two issues here:
It displays an error dialog rather than a "Page Not Found" message (it should replace 404 dialog with the page when in production) - fixed
But also, the data set is a bit corrupted. Did they edit their database?

For example, the first record set item (https://willemcatno-testability.test.specifysystems.org/api/specify/recordsetitem/?limit=1&recordset=724) refers to a collection object by ID `273800`

```json
{
  "objects": [
    {
      "id": 272349,
      "order": 0,
      "recordid": 273800,
      "recordset": "/api/specify/recordset/724/",
      "resource_uri": "/api/specify/recordsetitem/272349/"
    }
  ],
  "meta": {
    "limit": 1,
    "offset": 0,
    "total_count": 6682
  }
}
```

But, collection object with ID 273800 does not exist.

Did someone delete it from the database directly, instead of though the API?

If you try to delete it through the front-end, the record set item is cleaned up to

**Comment by chanulee1** [comment]
@maxxxxxdlp "Page not found" message is displayed. Does this issue need further investigation or should I close it?

**Comment by maxxxxxdlp** [comment]
> "Page not found" message is displayed.

Good

> Does this issue need further investigation or should I close it?

@grantfitzsimmons Do you know how this broken record set got created? Did someone manually delete the collection objects from the database?

**Comment by grantfitzsimmons** [comment]
The records were manually deleted from the database. Record sets can exist with no records inside.

**Comment by maxxxxxdlp** [comment]
Record sets without record is fine.
In this case you have a `RecordSet` with `RecordSetItem` records, but those `RecordSetItem` refer to non-existing Collection Objects.
When manually deleting Collection Objects, you also have to clean them up from the `RecordSetItem` table
