### ISSUE TITLE
Subviews not displaying correctly in grid view

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2412]
https://user-images.githubusercontent.com/37256050/200058692-19b83c8d-2e43-4f94-aa61-a6caf2b644c9.mov

https://herbrbge-edge.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178

https://herbrbge-testability.test.specifysystems.org/specify/view/collectionobject/349648/?recordsetid=178

Chrome, macOS

user: `britchie`

**Comment by grantfitzsimmons** [comment]
This can be replicated in `KU_FISH_NO_TESTS` as well

**Comment by grantfitzsimmons** [comment]
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/37256050/200606982-f9e1cbe8-4921-4ff8-a378-5a84fea8d49a.png">

**Comment by grantfitzsimmons** [comment]
I take it this is the same underlying issue as the Collection subview display one:

<img width="2491" alt="image" src="https://user-images.githubusercontent.com/37256050/201428043-dbabd6c5-ae89-4103-aa23-e602ba007a2f.png">

Expanded it does not display properly.

https://unitecnov22-edge.test.specifysystems.org/specify/view/division/2/

**Comment by grantfitzsimmons** [comment]
https://user-images.githubusercontent.com/37256050/201965744-db0d673f-ebee-4c1e-bd37-904d6dbe9125.mov

Another instance of an issue. This case, Collection Objects associated with a Collecting Event record

https://kuento-edge.test.specifysystems.org/specify/view/collectingevent/124453/

`kuento`, user `jbissen`, `KUEntoPinned` collection

**Comment by chanulee1** [comment]
https://kufishnotests-edge.test.specifysystems.org/specify/view/agent/new/

https://user-images.githubusercontent.com/103299204/202811056-cbd575f4-d7ef-4bbf-8265-e68760b57613.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/view/agent/new/

https://user-images.githubusercontent.com/103299204/202811100-fa7d78d0-cf15-428a-90d9-75eba9e08a40.mp4

Members associated with an agent in `kufishnotests`
user: `spfishadmin`
col: `KU Fish Voucher Collection`

**Comment by maxxxxxdlp** [comment]
Caused by the fix for https://github.com/specify/specify7/issues/2366/

Here is why this happens:
You can specify `viewName` in the FormTable definition.
If FormTable should only use that `viewName` when collapsed, but use the default view for that form when in expanded mode, then this issue is fixed, but it breaks #2366

In #2366, I made FormTable use `viewName` both in expanded and collapsed mode. That fixed the issue there because `FishAttributes` view was defined, but `CollectionObjectAttribute` wasn't

```xml
<cell type="subview" id="15" viewname="FishAttributes" name="collectionObjectAttribute" colspan="14" />
```

@grantfitzsimmons Should I revert the fix for #2366, or make it use default view name by default, but fallback to custom view name if default view does not exist?

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp  I think you should use view name by default but fall back to the default view if it does not exist. Will this solve all instances where this issue is occuring?

**Comment by maxxxxxdlp** [comment]
Fixed. I tested both issues and now they both have desired behavior.

### Algorithm

#### When collapsed
Use provided view name if provided and found a view by that name. Otherwise, use default view name.
If no default view, use auto generated view.

#### When expanded
Use default view name (just the table name). If there is no view for the default name, use the custom view name if provided and there is view by that name.
Else, use auto generated view.

As part of testing this, please test [relationship.relatedModel.view](https://github.com/specify/specify7/issues/2366) again
