### ISSUE TITLE
Carrying forward a single rel not working correctly

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2427]
https://user-images.githubusercontent.com/37256050/201100934-42d0e2e8-27a2-4569-88b2-7f7b6928e2cd.mp4

This is being done inside of a record set:
https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/new/?recordsetid=97

When I attempt to clone only the "Preparation" relationship, I see that the Col Obj Attribute is cloned as well. When attempting to save, I recieve the following error:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/37256050/201101070-4f0e20a9-7bba-4c60-b5db-e500fc6b901c.png">

[Specify 7 Crash Report - 2022-11-10T13_14_37.149Z.txt](https://github.com/specify/specify7/files/9980954/Specify.7.Crash.Report.-.2022-11-10T13_14_37.149Z.txt)

If these are separate issues, please let me know.

**Comment by maxxxxxdlp** [comment]
> When I attempt to clone only the "Preparation" relationship, I see that the Col Obj Attribute is cloned as well.

This was fixed in #2376

The other bug is that it isn't executing the object initialization code when using clone. Object initialization is responsible for setting the `collection` field for Collection Object, among other things - fixed.

FYI: this bug has been in specify 7 for 7 years, but we didn't find it out before because there was no UI for saying you don't want to clone collection field.

Please do more testing on the clone functionality.

**Comment by chanulee1** [comment]
Able to carry forward a single relationship. Also able to save with or without carrying forward `collection` field.
