### ISSUE TITLE
View Sets and App Resource editing should only show the name, not the other details

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2460]
When editing the name of an app resource or view set, you see all fields as they are all hidden by default.

This should be remedied somehow, be it a forced schema update in 7 or an override to stop this behavior.

**Comment by grantfitzsimmons** [comment]
<img width="655" alt="Screenshot 2022-11-15 at 2 56 23 PM" src="https://user-images.githubusercontent.com/37256050/202025704-93edabcc-8c33-4900-8528-0d9d7eaba072.png">

**Comment by maxxxxxdlp** [comment]
Meta Data and Mime Type are quite important.
Meta Data is used for reports and dwca resources.
Mime type is used for filtering, syntax highlighting and determines the file type when downloading.
I could see Timestamp Created and Description being useful too, but users are free to hide them if they fell otherwise

**Comment by grantfitzsimmons** [comment]
@benanhalt , @acbentley , and @tlammer said in yesterday's meeting that these were not intended to be user-facing. I do not see value in these being editable for the initial resource creation as they can be edited later– in what regular use case would I want to manually add a value to those fields?

**Comment by maxxxxxdlp** [comment]
Ah, I see. I didn't notice that this is for resource creation dialog.
Thus, I shall do the same thing we did for SpViewSetObj: hide these on resource creation, but display them on resource editing

**Comment by maxxxxxdlp** [comment]
Fixed.

FYI: it is fixed in a devious manner.
Instead of hardcoding SpViewSetObj and SpAppResoure form to display just one field, the code instead says to look for a view called `_SpViewSetObj_name` and `_SpAppResource_name` (instead of just `SpViewSetObj`), and if it is not found, fallback to the hardcoded view that has just the name field.

This way, you can still see all the other unhidden fields by going into Form Meta and checking "Use Auto Generated Form", or define a view called `_SpViewSetObj_name`.

Specify 7 is very much pro-choice 🙂
