### ISSUE TITLE
[testability] Guid fields appear in carry-over config

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2492]
Guid fields for determination and preparation subviews of CO form are available for carry over. However, newly created determination and preparation records are always assigned unique guids. A little misleading, but the user could always just hide the field. Is this an issue that needs fixing?

<img alt="img" width="600px" src="https://user-images.githubusercontent.com/103299204/203874935-32009914-3bfc-4aa0-815e-22fd7c93dad7.png"/>

<img alt="img" width="600px" src="https://user-images.githubusercontent.com/103299204/203874970-a2744463-cee5-4132-8651-b079a50d72d4.png"/>

https://freshfish-testability.test.specifysystems.org/specify/view/collectionobject/61139/

**Comment by chanulee1** [comment]
In the same vein, the "Collection Object" fields for `collectionobjectattribute` and `collectionobjectattachment` are available for carry-over, but these fields are always assigned to the newly created CO.

<img alt="img" width="600px" src="https://user-images.githubusercontent.com/103299204/203878487-ffb6cc33-a86c-4db7-99b2-e59ff35ca1d3.png"/>

<img alt="img" width="600px" src="https://user-images.githubusercontent.com/103299204/203878536-a0c671eb-9b27-48e0-acf2-ebe33efae291.png"/>

**Comment by maxxxxxdlp** [comment]
It looks like sp7 is only enforcing guid uniqueness for Collection Object GUIDs.
I think the reason is that we want to give users control over how they define GUIDs for other resources, but we do control Collection Object GUIDs, because those get uploaded to international data aggregators and must be unique.

Regarding the `Attachment` field in `Collection Object Attachment`:
That relationship must be unique. I made it unique. (as per https://github.com/specify/specify7/issues/1754#issuecomment-1157794164)

Regarding the `Collection Object` field in `Collection Object Attachment`:
You are right, circular relationships should be hidden from this list. The back-end is smart enough to overwrite the old relationship with the new one automatically on save, but I should hide it from the front end too

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons do you remember if we ever got to the bottom of whether we should enforce uniqueness for GUIDs that we **do** automatically assign a value for?

**Comment by grantfitzsimmons** [comment]
I think the conclusion was that if we automatically assign a value for it, it should be unique. The main idea was to prevent an issue when reconciling data later. Ideally, _all_ auto-generated GUIDs should be unique, as they are meant to be unique identifiers that will be shared with other data aggregators. Ideally you would never want to carry over a GUID.

**Comment by maxxxxxdlp** [comment]
I don't know if we can turn a previously non-unique field into a unique field without creating problems for people.

But, disabling carry over for ALL guids (even if not unique), sounds like an easy solution

**Comment by grantfitzsimmons** [comment]
`gUID` should not be carried over. That's a good solution to me.

**Comment by maxxxxxdlp** [comment]
For reference, we have GUID fields in these tables:

![Screenshot 2022-11-25 at 12 46 57](https://user-images.githubusercontent.com/40512816/204041258-9246b45b-1680-40cd-a712-4ad74647db01.png)

Of those, only Collection Object GUID is unique for now

**Comment by chanulee1** [comment]
Circular relationships seem to be hidden. Attachment fields made unique. Carry over appears to be disabled for GUID fields.
db: `freshfish`, `kufishnotests`, `pripaleo`
