### ISSUE TITLE
[testability] View sets in User Type level do not apply in select databases

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2516]
View sets at the User Type level do not seem to apply in `kufishnotests` and `freshfish`. Not sure if I am missing something. Used CO form as reference. "Edit Form Definition" option shows that the user type level view set is not used.

`kufishnotests`: https://kufishnotests-testability.test.specifysystems.org/specify/resources/view-set/35/

col: `KU Fish Voucher Collection`
user: `spfishadmin`
user type: `manager`

`freshfish`: https://freshfish-testability.test.specifysystems.org/specify/resources/view-set/11/

col: `KU Fish Voucher Collection`
user: `spfishadmin`
user type: `manager`

**Comment by maxxxxxdlp** [comment]
Good catch! This would have been a nasty bug

Looks like the app resources front-end in 7.8 was saving user types as capitalized, where as back-end expected them to be in lower case

To test:
This particular user type won't work as this database now has a record in the `SpAppResource` table with `userType` of `Manager`, rather than expected `manager` (unless you want to run a query in the query builder to fix this issue).

Suggested way to test:
Pick any other user type (or the same user type in a different collection), **but only if that user type does not have any app resources or view definitions already**, then create a view definition under that view type and make sure that "Edit View Definiition" link goes to that view definition when signed in as a user of that user type

**Comment by chanulee1** [comment]
User Type view sets do not seem to apply. Created new view definition under "FullAccess" user type and logged in as `spfishadmin` (changed user type for this user from "Manager" to "FullAccess"). Also created new user `fullaccess` with user type "FullAccess". "Edit View Definition" link goes to view definition at collection level for both users.

col: `KU Fish Voucher Collection`
https://kufishnotests-testability.test.specifysystems.org/specify/resources/view-set/41/

**Comment by chanulee1** [comment]
"Edit View Definition" link seems to go to collection level view definition for user `fullaccess` with user type "FullAccess", and for user `guest` with user type "Guest", despite there being view definitions at the user type levels for both "Guest" and "FullAccess" in `KU Fish Tissue Collection`.

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/new/

**Comment by maxxxxxdlp** [comment]
Thanks, for testing this again. Turns out there were two bugs in here. I was able to test this locally properly and make sure the bug is finally fixed.

To confirm the fix, please test:
1. Adding resource to the "Limited User" or "Manager" user type in the Tissue collection (because those two haven't yet  been affected by this bug)
2. Adding a personal resource (on a user level) to a newly created user (any collection would work for this) - there was a bug with this too

**Comment by chanulee1** [comment]
Form def link still seems to go to view def at collection level. Changed user type of `spfishadmin` to "Manager" and created a view def under the "Manager" user type in the Tissue collection.

**Comment by chanulee1** [comment]
For the newly created user, attempting to create a view def for the user at the user level results in error.

https://user-images.githubusercontent.com/103299204/206315436-2cd338bc-7205-45fe-acf4-6f741b1f80aa.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/resources/

[Specify 7 Crash Report - 2022-12-07T22_56_32.562Z (1).txt](https://github.com/specify/specify7/files/10180675/Specify.7.Crash.Report.-.2022-12-07T22_56_32.562Z.1.txt)

User: `viewdeftest`
Col: `KU Fish Tissue Collection`

**Comment by maxxxxxdlp** [comment]
The error is a bug, caused by [ac7fad5](https://github.com/specify/specify7/commit/ac7fad50ab651f3a97e73219ab5c13340d00ae1c). Fixed

**Comment by chanulee1** [comment]
Fixed!
Tested: `kufishnotests`
