### ISSUE TITLE
[testability] Using browser navigation buttons in RS causes problems

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2537]
Clicking the browser "back" button after removing/deleting a record in RS causes error. RS displays invalid RS item number. 

https://user-images.githubusercontent.com/103299204/205366394-ed5326bb-f65a-4ff0-92ee-f166d335cd92.mp4

Clicking browser "back" button after creating and saving record in RS creates new record.

https://user-images.githubusercontent.com/103299204/205368916-a6ecdff9-4015-45fd-90de-397f754ddc54.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/view/agent/7/?recordsetid=114

browser: `chrome`

**Comment by maxxxxxdlp** [comment]
First video: Fixed. The back arrow would now ignore deleted records

Second video: that's the intended behavior. Going back in this context goes back to the way that form looked like when you pressed the "Add" (or "Clone") button. Essentially, you are going back to adding a new record. Then, if you press the "Save" button, you create a new record. Do you have suggestions on how to make this less confusing?

**Comment by chanulee1** [comment]
Back arrow issue appears to be fixed.

**Comment by chanulee1** [comment]
> First video: Fixed. The back arrow would now ignore deleted records
> 
> Second video: that's the intended behavior. Going back in this context goes back to the way that form looked like when you pressed the "Add" (or "Clone") button. Essentially, you are going back to adding a new record. Then, if you press the "Save" button, you create a new record. Do you have suggestions on how to make this less confusing?

It makes sense when you explain it. I was surprised by this because I didn't think of the "adding" step as its own, separate stage. I was expecting it to "undo" the creation of the new record. I think that this way might be more intuitive, and the use case for adding records with the back arrow seems narrow. I can't speak for all users, though.

**Comment by maxxxxxdlp** [comment]
@chanulee1 That's a good suggestion. Fixed.
Adding is considered a "step" by default everywhere. We need to add an explicit step to make it otherwise, however, I think it's worth it. Would be good (though maybe time-consuming) to write down a list of all the places where that happens and needs to be fixed.

For this fix those, testing steps:
- Creating new record in a record set and pressing browser's back arrow should not show the blank form
- Modifying an existing record and going back should not go show the same record again (previously it created a new "step" for each time you press "save" button)

**Comment by maxxxxxdlp** [comment]
@chanulee1 That's a good suggestion. Fixed.
Adding is considered a "step" by default everywhere. We need to add an explicit step to make it otherwise, however, I think it's worth it. Would be good (though maybe time-consuming) to write down a list of all the places where that happens and needs to be fixed.

For this fix those, testing steps:
- Creating new record in a record set and pressing browser's back arrow should not show the blank form
- Modifying an existing record and going back should not go show the same record again (previously it created a new "step" for each time you press "save" button)

**Comment by chanulee1** [comment]
Appears to be working.
Tested: `kufishnotests`
