### ISSUE TITLE
Can't upload a data set if you have uploaded it previously

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#254]
Sounds strange but, if you modify a data set that you have uploaded already, you can't upload it in Sp7 or Sp6.  If you modify the data set in Sp6, you can upload it.

**Comment by benanhalt** [comment]
When a row is uploaded its upload status get set to *uploaded*, and the uploader will skip it on subsequent uploads. Specify 7 doesn't clear that *uploaded* status when data is modified. Making it do so would require fairly extensive changes because the browser and the server only communicate the row IDs, not their statuses or whether data is modified. So, this is probably not for this release.

A work around is to add a new row, fill down the data from the uploaded row (modifying as desired), and then (optionally) delete the uploaded row.

**Comment by tlammer** [comment]
really strange thing I discovered is if you add new rows to the data set, don't modify the previous rows and don't have catalog number (which would cause duplication errors), and upload again, all of the rows get uploaded.  The previous rows don't get skipped, or at least the details doesn't say they were skipped.

**Comment by maxxxxxdlp** [comment]
N/A since 7.6.00
