### ISSUE TITLE
[testability] CO attachment not cloning properly

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2562]
Cloning CO record with a collection object attachment does not clone the attachment properly. Same behavior with carry-forward. Probably the cause of #2557.

https://user-images.githubusercontent.com/103299204/206299699-bd300923-c960-42de-9002-7be93f5dcb68.mp4

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/61173/?recordsetid=125

**Comment by grantfitzsimmons** [comment]
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/37256050/206584136-33815377-9d44-439a-aab2-70115386e7b1.png">

Still able to recreate this issue after redeploying the instance. Maybe the fix isn't live yet. Causes an issue when cloning as well.

https://kufishnotests-testability.test.specifysystems.org/specify/view/collectionobject/new/?recordsetid=97

**Comment by maxxxxxdlp** [comment]
This isn't fixed yet - I mistakenly attributed this issue in the commit message - though I am currently looking into fixing this.

It occurs because I incorrectly disabled carry over for attachments - we either need to reenable carry over for attachments (like it was before), or fix the attachments plugin to handle this case.

The problem with carrying over attachments is that I am not sure if multiple records pointing to the same attachment is going to cause issues (see https://github.com/specify/specify7/issues/1754).

Could we do some testing with that on that behavior `edge`? I.e, two records point to same attachment. delete one of them. what happens?

Also, have 10 records point to same attachment - how does the attachments viewer handle that - does it display 10, or 1, or none, or error?

**Comment by maxxxxxdlp** [comment]
Can confirm, deleting a record also deletes the attachment, even if the other record is pointing to the same attachment - https://demo-assets.specifycloud.org/fileget?coll=sp7demofish&type=O&filename=6d063109-621e-4965-9cf7-0e3fecc61b0c.md&downloadname=kss_project.md

Until that is fixed (i.e, back-end adds a check for other usages of attachment, or front-end adds explicit clone of attachment), clone for all *attachments tables must be disabled.

**Comment by chanulee1** [comment]
Attachments are not cloned, and are disabled in the carry-forward config menu.
Tested: `kufishnotests`
