### ISSUE TITLE
Cannot navigate back to original collection after navigating to a CoR item

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2564]
https://user-images.githubusercontent.com/37256050/206349938-3e6355f8-0ac7-4a1e-832d-425b866a651e.mp4

Left is `testability`, right is `edge`

**Steps to Recreate:**
1. Click on the Collection Object catalog number in the CR plugin
2. Navigate to the item in the Tissue Collection
3. Go back in the browser to return to the original item
4. See you are unable to

Cannot recreate this issue on `edge`

**Comment by grantfitzsimmons** [comment]
**National Fish Collection**, user is `collection`

https://willemcatno-testability.test.specifysystems.org/specify/view/collectionobject/195554/

**Comment by maxxxxxdlp** [comment]
Cause:
Switching a collection is an action that has it's own URL
Thus, when you click on the back arrow, the switch collection action is triggered again.
Fixed by making switch collection action delete itself from the history once it redirects you to a new collection

When testing, please also test the cache buster as it had the same bug

**Comment by chanulee1** [comment]
How do I test the cache buster?

**Comment by chanulee1** [comment]
Going back in the browser for an isolated CO works as expected. For a CO within a record set, going back does not immediately navigate back to the original collection and record. The first "back" navigates back to the correct record set, but remains in the second collection. The records in this set are replaced with the related records in the second collection. Backing a second navigates back to the original collection.

https://user-images.githubusercontent.com/103299204/206753517-182e9e6c-939d-4700-9909-b250edbfee50.mp4

https://willemcatno-testability.test.specifysystems.org/specify/view/collectionobject/195168/?recordsetid=52

**Comment by maxxxxxdlp** [comment]
> How do I test the cache buster?

There is "Clear Browser Cache" option in User Tools

**Comment by maxxxxxdlp** [comment]
As part of fixing this bug, I discovered that it was also present in other places:
- Deleting an app resource and trying to go back
- Navigating to a URL like `http://localhost/specify/view/collectionobject/4/?recordsetid=84` where, `/collectionobject/4/` refers to an existing resource, and `?recordsetid=84` refers to an existing record set, but the resource is not part of the record set. In this case, you should be redirected to `http://localhost/specify/view/collectionobject/4/` and the browser back button should not let you go back to the record set url.
- Open a record in a form (not record set). Delete it. Try going back
- Save query (either new or modified). Saving should not create a new history entry (i.e, when pressing the back button)
- Delete a collection role
- Delete an institution rule
- Delete a user
- Save user (either new or modified)
- Change data set owner

Those should be fixed now. Please test them if possible.

Also, fixed another bug:
- Renaming the record set should open the first record in the record set, rather than a form for adding records to a record set

**Comment by chanulee1** [comment]
Issue still seems to happen.

https://user-images.githubusercontent.com/103299204/207136133-c3991f59-4800-4969-8b18-bb52a493aaad.mp4

https://willemcatno-testability.test.specifysystems.org/specify/view/collectionobject/195168/?recordsetid=52

**Comment by chanulee1** [comment]
After rebuild:
Now cannot return to original collection.


https://user-images.githubusercontent.com/103299204/207148603-db8e805a-cecc-4241-92e9-2807786b7187.mp4

**Comment by maxxxxxdlp** [comment]
Delaying this issue till future release
