### ISSUE TITLE
[testability] Unable to save locality record

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2578]
Cannot save a specific locality record. Also, multiple locality records in this record set are unsaved upon navigation, similar to in #2517. Separate issues?

https://user-images.githubusercontent.com/103299204/206818700-e7565616-ac8f-48e9-acf5-208919a83fb2.mp4

https://uoregonpaleo-testability.test.specifysystems.org/specify/view/locality/12125/?recordsetid=1037

**Comment by maxxxxxdlp** [comment]
Caused by the bug where back-end sends fields with date-time format, but front-end expects them to be in date format, thus converting it makes front-end thing that field value changed and thus triggers an unload protect

In particular, this was caused by the the Geo Ref Det Date field in the Geo Coord Details subform

Fixed

**Comment by chanulee1** [comment]
Appears to be fixed.
