### ISSUE TITLE
Collection list should have a scrollbar at all times

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2588]
> If a user has access to multiple collections, then the list might be so large that it exceeds the bounds of the panel, however the scrollbars do not automatically appear to indicate there are more collections to pick from. The user is potentially going to not know additional collections are available if they scroll the list.

**Problem:**

![image](https://user-images.githubusercontent.com/37256050/207151736-4384bda2-5ac1-4d07-8ed2-376b4f0b00e9.png)

**Solution:**
Show a scroll bar at all times when the list exceeds the visible frame
![image](https://user-images.githubusercontent.com/37256050/207151755-e203a87e-e192-4989-bf23-804a1b8479e2.png)

**Requested By:** Matthew Cruz at UMich

**Comment by maxxxxxdlp** [comment]
I think scroll bar being invisible is a browser setting - we can override it, but I would rather not, as it goes agains user's wishes, and because this affects **every** scroll bar in specify

**Comment by mcruz-umich** [comment]
I agree with not overriding a browser setting. Since there is a fundamental UX flaw when visually there is more to the list than meets the eye and no indicator to the user that can scroll to see more, perhaps there is an alternative.
Is there some visual element that is part of the visual package being used here that can convey there is more content? An alternative might be to resize the container to render the entire list. This would only face the [rare?] issue of looking odd if the list was really long. We have 10 collections in that one DB. Is there much chance of a list being longer? Perhaps it will not look strange at all.

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-9-release-announcement/1131/1
