### ISSUE TITLE
Add an option to save a particular tree view conformation as the default.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#261]
If a default tree conformation is saved for a user, the tree view would open to that conformation when selected from the toolbar instead starting completely closed.

**Comment by benanhalt** [comment]
Other possibility is to have a pref to always open the tree down to a certain level.

**Comment by benanhalt** [comment]
Or to the first uncollapsed column.

**Comment by timo11** [comment]
Three buttons have been stuck next to the search field:
'Save' saves the current conformation as the default for the current user.
'Restore' displays the saved default conformation.
'Forget' forgets the default.

The conformations are saved as cookies.
The default conformation is only used in cases where the tree would formerly display root only, otherwise the last conformation is used.

**Comment by yvonneekanim** [comment]
Verified. The remember, restore and forget buttons work as specified.
