### ISSUE TITLE
Cannot create new agent from the assign agent QCBX in the accounts panel

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2696]
**Reported By:** @grantfitzsimmons

**Comment by grantfitzsimmons** [comment]
**Reported By:** Natural History Museum of Denmark

> 
> Our process was the following:
> 
> 1. Sp7 – Security and Accounts
> 
> 2. Choosing the collection
> 
> 3. Under ‘User Accounts Assigned to this Collection’ selecting a user
> 
> 4. Clicking on Enable Collection Access
> 
> 5. First problem: it doesn’t find an agent with this name
> OK, we are creating a new one for him
> 
> 6. Trying to save it
> 
> 7. Set User Agents
> 
> 8. Second problem: a pop-up window is appearing that says ‘Set user agents’
> Please set the following agents before proceeding:
> It show the he has agents at the collections, where he needs to have one, but doesn’t have, where he has no access. I cannot save it this way.
> I cannot save it if I fill out every fields (adding agents for him at each and every collections).
> 
> 9. Dead end.

**Comment by grantfitzsimmons** [comment]
**Reported By:** Willem

> I tried to add a new user. It seems that there was an issue when I tried to create a new agent record from within the ‘create new user’ process. I was forced to create a new agent in the agent table first and then look it up in the create user process.

I can confirm this experience as reported above.

**Comment by maxxxxxdlp** [comment]
I got good news and bad news.

Turns out, this is a bug with business rules, not with the security panel. Scoping rules were not applied to resources created outside of the Data Entry (or Interactions or Record Set) screen (on the front-end, the workbench creates resources on the back-end so it's ok) (all other business rules were still applied). Thus, agents created in the security panel were not scoped to division.

This has been a bug since the beginning of specify 7, but it didn't manifest itself for two reasons:
 - we didn't have any place where you created resources outside of Data Entry.
 - we didn't not load code dynamically. even if you were in query builder, the form code was loaded anyway.

Since scoping file was loaded dynamically, it was only loaded when you open Data Entry. And if you didn't open forms, it won't get loaded. Thus, a temporary workaround for this bug is to open any form, and then if you go to user preferences, the agent will be created correctly.

But I also pushed a temporary fix.

**Comment by maxxxxxdlp** [comment]
#2696 and #2405 are manifestations of the same issue

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-release-announcement/1079/1

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/error-creating-new-agent/1245/2
