### ISSUE TITLE
Confusing management of user access to collections

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2697]
> Whereas I love the new edition of Specify7 and user management appearing to be really powerful now, I’m stuck waddling about a simple task: Adding an existing user to another collection.
> 
> For instance: I have a user, Tom Schiøtte, which has been connected to the “Invertebrate Zoology” collection in Specify for a very long time. This user needs to be added to a newly created collection called “Exhibitions”. So I log on with my admin access and head to the Security and Accounts section.
> 
> First I try to look up the user at the institution level. His username is “schioette”. I then select the collection “NHMD Exhibitions” from the dropdownlist and tick off “Enable Collection Access” and “Full Access - Legacy” (He’s marked “Collection Admin” for InvZool).
> 
> Assuming an agent needs to be assigned to this user for this particular collection/discipline, I also add that, believing all should be OK then.
> 
> ![image](https://user-images.githubusercontent.com/37256050/208686953-92b4d602-26bb-4f43-a5cd-4c7b83cf7695.png)
> 
> I move down to hit “Save”:
> 
> ![image](https://user-images.githubusercontent.com/37256050/208686966-bafcf7b2-cbfd-4c5a-b088-5b195ea7686e.png)
> 
> 
> But then, for some reason, Specify7 demands that I also set agents for all other collections, even though these are not relevant at all.
> 
> ![image](https://user-images.githubusercontent.com/37256050/208686997-8578929a-2c55-467c-9dd1-2181dfde5e17.png)
> 
> 
> Why is that???

**Reported By:** [Fedor at the Specify Community Forum](https://discourse.specifysoftware.org/t/confusing-management-of-user-access-to-collections/944/1)

Is this because the user is an admin in Specify 6?

**Comment by maxxxxxdlp** [comment]
Yes, the user being an admin in sp6 would trigger this.
Though, we would need access to their database to know for sure.


> But then, for some reason, Specify7 demands that I also set agents for all other collections

I believe the dialog is showing Division, not Collections. That's because agent table is scoped to division, not collection.

Setting agents in other collection won't be a problem, as it won't give the user access to those collections (unless the user has `Collection Access` checkbox checked).

We should probably improve the dialog to state whether the following agents are required because of sp6 or because of sp7

**Comment by maxxxxxdlp** [comment]
Potential duplicate of #2405

**Comment by grantfitzsimmons** [comment]
Duplicate of #2405
