### ISSUE TITLE
`MissingAgentForAccessibleCollection` when agent outside of division collection is selected

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2700]
1. Sp7 – Security and Accounts
2. Choosing the collection
3. Under ‘Collection User Roles’ selecting Full Access - Legacy
4. Clicking on Add
5. With using the Query Builder trying to find the user
6. When clicking on Select, another pop-up shows up with this:
‘There is an unrecoverable error that will not allow us to safely return to your current window.’
7. Attached the Error message
8. Dead end.

[Error Message](https://github.com/specify/specify7/files/10287852/adding_agent_to_exh_collection_Specify.7.Crash.Report.-.2022-12-16T10_23_49.324Z.1.txt)

```
{"MissingAgentForAccessibleCollection": {"missing_for_6": [], "missing_for_7": [851970, 983040], "all_accessible_divisions": 
[2, 2, 327680, 327680, 327680, 327680, 327680, 360448, 458752, 458752, 491520, 491520, 491520, 688128, 688128, 688128, 851968, 917504]}}
```

**Reported By:** Natural History Museum of Denmark

**Comment by maxxxxxdlp** [comment]
Duplicate of #2405

**Comment by bronwyncombs** [comment]
Reopening because this was reported by Dr. Panos Stephanopoulos @ University of Patras via [943](https://specifysoftware.bolddesk.com/agent/tickets/943): 

```
],
  "responseText": "{\"MissingAgentForAccessibleCollection\": {\"missing_for_6\": [], \"missing_for_7\": [7], \"all_accessible_divisions\": [2]}}"
}
```
Panos described the same workflow as reported in the description. 

[Specify 7 Crash Report - 2026-05-21T12_35_47.669Z.txt](https://github.com/user-attachments/files/28158914/Specify.7.Crash.Report.-.2026-05-21T12_35_47.669Z.txt)
[Specify 7 Crash Report - 2026-05-22T07_25_18.559Z.txt](https://github.com/user-attachments/files/28158913/Specify.7.Crash.Report.-.2026-05-22T07_25_18.559Z.txt)

I am not sure if the PRs fixing the issue this was closed in favor of resolve this. It can be closed again if we are confident that this will be fixed by https://github.com/specify/specify7/pull/3283

**Comment by bronwyncombs** [comment]
Reported by Fedor @ Natural History Museum of Denmark via [BoldDesk](https://specifysoftware.bolddesk.com/agent/tickets/1091).

[Specify 7 Crash Report - 2026-07-01T07_25_25.761Z.txt](https://github.com/user-attachments/files/29555895/Specify.7.Crash.Report.-.2026-07-01T07_25_25.761Z.txt)

**Comment by grantfitzsimmons** [comment]
This is a duplicate of #2405, all reports should be directed there
