### ISSUE TITLE
`statspage`: Relative date in the past not working

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2723]
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/37256050/210104961-dcf6de66-00b0-43de-8514-c560654e73a1.png">

I set the query to return the past 7 days worth of records. I created a large number today  but none are returned.

https://coldfish-statspage.test.specifysystems.org/specify/query/122/

**Comment by grantfitzsimmons** [comment]
I see the confusion– the past 7 days does not include today. Bug or not, you decide @maxxxxxdlp

**Comment by maxxxxxdlp** [comment]
Past 7 days should include today

**Comment by realVinayak** [comment]
In this case, the query should have been 'Greater than' since the relative date just returns a single date based on the inputs. If we want, we can add a feature that if the users click on the relative date, then the 'Equal' in the UI will behave similarly to 'Greater than', and then hide the 'Greater than' item. Not sure if that would be best since there might be corner cases we might need to think about.

**Comment by maxxxxxdlp** [comment]
@realVinayak you are right. This is confusing, but #2724 may make it clearer. Closing this in favor of #2724
