### ISSUE TITLE
`agent-merging`: Show many-to-one rels in dialog

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2736]
Related to #2579 

---

Rather than showing `Collector` show `Collecting Event`s

**Comment by chanulee1** [comment]
Not sure if this is a problem. When there is an intermediate table relating the agent to the table in question, the exact relationship can be kind of unclear. Correct me if I got that wrong.

https://user-images.githubusercontent.com/103299204/216518535-219d6ebf-10e3-4fad-92e0-8a0f03a6bfe6.mp4

**Comment by maxxxxxdlp** [comment]
True. This was a bit intentional as a compromise between keeping that section brief and giving useful information. Do you have suggestions on how to improve it.

One outcome of this is that what you can see in the video as "Accession - Accession Agent" line being shown in references twice. This happens if current agent is related to Accession Agent in more than one way (i.e, via `createdByAgent` for some of them, and via `modifiedByAgent` for others). Should we merge those together or keep them separate?

I belive Andy suggested going one step further and merging together all references with the same parent table (i.e, `Accession - Accession Attachment` and `Accession - Accession Agent` would be printed as just `Accession (5)`)

**Comment by chanulee1** [comment]
I think that merging the references with the same parent table makes sense, and it would certainly make the UI much cleaner. For more information, maybe clicking the link could lead to a dialog that shows the exact relationship and groups the records based on that? Not sure what is best for users.

**Comment by maxxxxxdlp** [comment]
Fixed

**Comment by grantfitzsimmons** [comment]
Fixed on #2796
