### ISSUE TITLE
Attachment table count not scoped to the current collection

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2762]
<img width="680" alt="image" src="https://user-images.githubusercontent.com/37256050/211232825-5ec5376e-ec61-40bf-9e0f-175ad359f121.png">

**Comment by maxxxxxdlp** [comment]
Thanks for discovering this!
I will merge this with https://github.com/specify/specify7/issues/2292 - all the cases where it happens are important to fix. I will try to get to soon

**Comment by grantfitzsimmons** [comment]
@tlammer says it's back

**Comment by melton-jason** [comment]
Actually, the fix for this issue (and #2292) should be included right now in production and not in `v7.9.3` or `v7.9.3.1`. 

The merge commit (https://github.com/specify/specify7/commit/7324c28adc552ecb2aefd4c0533433001103cffc) from the PR which resolved this problem (#3304) is not present in any tags currently. 

This can be verified by running the following:
```bash
git name-rev --tags --name-only 7324c28
```

Additionally, #3304 was merged Jan 26 while the `v7.9.3` tag was made Jan 23. 

It will need to be verified again if the bug is still present in `production` currently, but it is not fixed in `v7.9.3.+` and should be fixed in `production`.

**Comment by emenslin** [comment]
Fixed
