### ISSUE TITLE
Front-end has no direct access to sp7-exclusive tables

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2813]
<img width="1565" alt="image" src="https://user-images.githubusercontent.com/37256050/212392190-b12a082f-b944-4fbe-a3dc-50734e6a0d9a.png">

**Comment by grantfitzsimmons** [comment]
https://sp7demofish.specifycloud.org/specify/query/new/spdataset/

**Comment by maxxxxxdlp** [comment]
I don't know why, but Ben made some tables not be available through the main specify API (tables for notifications, workbench, permissions and all other specify7-exclusive tables).

Thus, all of those tables are not available to the front-end, except though dedicated APIs. We can look into changing that in the future.

**Comment by maxxxxxdlp** [comment]
Though, the query builder should not show a blank page - it should show a 404 page.
You could open a separate bug for that

**Comment by grantfitzsimmons** [comment]
It does show a 404 page, so that's not a problem :smile:

**Comment by maxxxxxdlp** [comment]
oh I see. it's not visible on the screenshot.
Yeah, then it's just a back-end bug - something that we can consider changing

**Comment by melton-jason** [comment]
> > > > Add a block for
> > > > 
> > > > * `spdataset`
> > > 
> > > 
> > > For more context, this is regarding adding a deletion blocker to SpecifyUser. This operation is not currently supported with how I extended deletion blockers, but I will add a way to support adding reverse relationships so this can be added.
> > 
> > 
> > `Spatasets` will more complicated than any other table(s) to work with on the backend. Many of Specify's internal helper functions rely on the datamodel being loaded when Specify starts up (this happens in [load_datamodel.py](https://github.com/specify/specify7/blob/production/specifyweb/specify/load_datamodel.py)). The issue is that to get the list of tables and fields in the database, Specify 7 reads the `specify_datamodel.xml` in the Specify 6 config directory (as seen below), and as far as I know the spdataset table is not included within that file.
> > https://github.com/specify/specify7/blob/4877f75686668cdd5b2d28c46881fb7628ce69a4/specifyweb/specify/load_datamodel.py#L222-L231
> > 
> > We could manually use SQL to get the correct information, but that will only be a short-term solution (which may be fine for now). Preferably, we would want to engineer a way to load/register these Specify 7 specific tables in the internal specify datamodel. (If such a way already exists and I am overlooking it, then feel free to point it out. I have checked all attributes on specify.models and spdataset does not exist)
> 
> From [#2806 (comment)](https://github.com/specify/specify7/pull/2806#issuecomment-1384365814)
> 
> It would be nice to have a proper solution to adding these tables into the Specify datamodel, this would be beneficial both for backend use (as described above) and for frontend use. Currently in Specify 7, users are not allowed to query on these tables that are not loaded into the datamodel, which may become an issue if tables are added solely in Specify 7.

From #2835

**Comment by maxxxxxdlp** [comment]
Implementing that would also allow getting rid of some apis (i.e, the notifications API. Some Workbench APIs too potentially, but those would be more difficult as they would also require migrating permissions)

**Comment by maxpatiiuk** [comment]
@grantfitzsimmons reminded me that it's not just about having access to those tables on the front-end - we would also need to add them to the schema config

minor thing, but that would allow to better resolve https://github.com/specify/specify7/pull/4472#pullrequestreview-1850047772

**Comment by acwhite211** [comment]
Here a list of the Specify 7 exclusive tables that are currently not in the specify_datamodel.xml file provided by Specify 6:

accounts:
- Spuserexternalid

attachment_gw:
- Spattachmentdataset

business_rules:
- PsuedoManyToManyManager
- UniquenessRule
- UniquenessRule_Field

notifications:
- Message
- Spmerging

permissions:
- UserPolicy
- Role
- LibraryRole 
- UserRole
- RolePolicy
- LibraryRolePolicy

specify:
- SpecifyUserManager
- Specifyuser
- Preparation
- Taxon
- Storage
- Geography
- Geologictimeperiod
- Lithostrat

workbench:
- Spdataset

stored_queries:
- All the sqlalchemy models in stored_queries app (not needed in api)

**Comment by melton-jason** [comment]
> PsuedoManyToManyManager

This is a [Model Manager](https://docs.djangoproject.com/en/3.2/topics/db/managers/), not a Model instance. 
It does not represent a table in the database and like the SQLAlchemy models, the frontend shouldn't know it exists. 

> add these missing tables to the datamodel.py file

Why do the Specify7 exclusive Models need to be added to the `datamodel.py` file? 
Is the motivation to have a representation of all models in one place?
Is the plan to completely migrate the Models to the file, or have an additional representation of the Models alongside the current definitions in their respective Django Apps?

Duplicating the models may run into some problems in the future. 
Notably: how will discrepancies be resolved between the model defined in the Django App and the model in the `datamodel.py`? How will new models be added to the `datamodel.py`? 
I assume there would be some functionality to auto-update the associated model representations in the `datamodel.py` whenever Django is being initialized. 

Alternatively, instead of duplicating the model representations, I would think an adapter can be made to serialize already-existing models for the `/context/datamodel.json` endpoint. 

Regardless of the implementation, I think all models can be loaded from Django by using the following: 

(Fetching all models programmatically means that Specify7 models can be created/updated without worrying about or managing some other code specifically for the datamodel code)

```py
from django.apps import apps

all_models = apps.get_models()
```
