### ISSUE TITLE
Importing a query is not functional

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2817]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/37256050/212417073-0dd7ea98-bd06-4ff3-a1b3-22ec5090f901.png">

`v7.8.3`

https://sp7demofish.specifycloud.org/specify/overlay/queries/new/

[Pteridophytes Family list.json.zip](https://github.com/specify/specify7/files/10415376/Pteridophytes.Family.list.json.zip)

**Comment by melton-jason** [comment]
When I try and import the attached query ([Pteridophytes Family list.json.zip](https://github.com/specify/specify7/files/10415376/Pteridophytes.Family.list.json.zip)), Specify throws `No Agent matches the given Query`

For me, it seems like this issue is caused by the inclusion of references to Agents and Specifyusers.
In the attached query export in [Pteridophytes Family list.json.zip](https://github.com/specify/specify7/files/10415376/Pteridophytes.Family.list.json.zip), there are many references to Agents and Users which do not exists in my database. 

![issue-2817](https://user-images.githubusercontent.com/64045831/212765931-c0c8d550-c882-458e-906d-fd6494b04fd1.png)

When I manually go through the query json and replace all users and agents with ones that exist in my database, I am able to properly import the Query (albeit with a field not being mapped properly) 

![issue-2817-query](https://user-images.githubusercontent.com/64045831/212766500-0d13afe6-f896-4cab-bba5-789a4928297e.png)

Is Specify supposed to ignore references to Agents/Specifyusers for query imports? Or should they not have been exported in the first place?

**Comment by grantfitzsimmons** [comment]
Most of the time importing and exporting a query happens within the same database. Between databases is something that has not been used to my knowledge, but should be supported.

I need to troubleshoot this query in a different database but I cannot. I can remove those fields and try again.

I don't think those are necessary to preserve upon import, and if removing them allows it to be used, I would think it's the best path forward

**Comment by maxxxxxdlp** [comment]
Original response:

I think it's useful to preserve that information, thus it should be included in the export, but Sp7 should be able to handle that information referring to non-existent records (either by checking if they exist before creating a query, or by retrying without them if the query fails)

---

New response:
On second though, that information would be overwritten anyway (SpecifyUser would refer to current user, createdByAgent would refer to current agent, and modifiedByAgent might be set to current agent by the back-end too), thus the simplest and best solution would probably be to exclude those fields from export / ignore them on import.
