### ISSUE TITLE
Browser navigation buttons not behaving correctly

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#2823]
Sometimes, when the browser navigation arrows are used, the url changes but the page remains the same. Not sure exactly what triggers this, but seems to be associated with urls with '/new/' in them, such as when creating a new record or a new query.

https://user-images.githubusercontent.com/103299204/212745313-f20e79ba-dd89-432d-a45b-4031406c241e.mp4

https://kufishnotests-edge.test.specifysystems.org/specify/

browser: Chrome
branch: `edge`

**Comment by maxxxxxdlp** [comment]
This is bad.

I had it but I thought that it was just a Chrome (or Chrome Beta) bug (because I also had it in my chrome extension)
and reloading the page does not fix it for me. closing the tab does - another sign that it's a chrome bug

**Comment by maxxxxxdlp** [comment]
I think it started happening after migration to react-router. We updated to the newest version of react-router on the `xml-validation` branch

**Comment by grantfitzsimmons** [comment]
This hasn't been encountered since as far as I can tell. 

@maxxxxxdlp Reopen if this is something we need to address now or I can once we have a report of this issue.

**Comment by maxxxxxdlp** [comment]
🎉

> This hasn't been encountered since as far as I can tell.

that's great news!

that was a very worrying issue for a while, and I didn't exactly know what caused it or how to fix it.
I had it happen in my chrome extension too (which does not use react router, but does still use react, and code from specify 7) - still I belive this was a browser bug, and that's why it resolved itself on it's own
