### ISSUE TITLE
Delete button does not work after deleting a deletion blocker item

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2875]
`agent-merging` but likely applicable to `edge`

**Comment by maxxxxxdlp** [comment]
Likely applicable to `edge`, but should be fixed on `agent-merging` as it did some refactoring of delete blockers

**Comment by maxxxxxdlp** [comment]
Unable to replicate on `agent-merging` branch, but I did changes to delete blockers there so it's possible that this is fixed now. Need testing

**Comment by chanulee1** [comment]
Cannot immediately delete after deleting deletion blocker item. Shows count 0 of the item. Closing deletion blocker and clicking delete again shows that the count is now 1. Attempt to navigate to deletion blocker item fails (since it is deleted). Must reload page to delete record.

https://user-images.githubusercontent.com/103299204/217065392-dd77b554-06fb-4712-b867-35a1dfb49951.mp4

**Comment by maxxxxxdlp** [comment]
"0" should not be displayed.
Reopening the dialog should not display stale blockers.
Fixed both bugs

**Comment by chanulee1** [comment]
Fixed.
