### ISSUE TITLE
`agent-merging`: Use partial dates instead of precision dates

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#2892]
**Requested By:** Ian Engelbrecht

**Comment by maxxxxxdlp** [comment]
Fixed:
1. PartialDateUi is now shown instead of simple date fields
2. The precision field is not visible, unless the date field is not visible, or "Show conflicting only" is unchecked
3. Merging the date field also merges the precision field. Merging the precision field does not merge the date field.

The above rule aplies to all of the following fields (from the entire database, not just Agent):

```json
{
  "dateOfBirthPrecision": "dateOfBirth",
  "dateOfDeathPrecision": "dateOfDeath",
  "date1Precision": "date1",
  "date2Precision": "date2",
  "borrowDatePrecision": "borrowDate",
  "endDatePrecision": "endDate",
  "startDatePrecision": "startDate",
  "catalogedDatePrecision": "catalogedDate",
  "embargoReleaseDatePrecision": "embargoReleaseDate",
  "embargoStartDatePrecision": "embargoStartDate",
  "inventoryDatePrecision": "inventoryDate",
  "date3Precision": "date3",
  "date4Precision": "date4",
  "date5Precision": "date5",
  "completedDatePrecision": "completedDate",
  "curatorApprovalDatePrecision": "curatorApprovalDate",
  "examDatePrecision": "examDate",
  "treatmentCompDatePrecision": "treatmentCompDate",
  "extractionDatePrecision": "extractionDate",
  "sequenceDatePrecision": "sequenceDate",
  "determinedDatePrecision": "determinedDate",
  "preparedDatePrecision": "preparedDate",
  "endDateVerbatim": "endDate",
  "startDateVerbatim": "startDate",
  "catalogedDateVerbatim": "catalogedDate",
  "endDepthVerbatim": "endDepth",
  "startDepthVerbatim": "startDepth",
  "maxUncertaintyEstUnit": "maxUncertaintyEst",
  "endDepthUnit": "endDepth",
  "startDepthUnit": "startDepth",
  "GGBN_concentrationUnit": "GGBN_concentration",
  "GGBN_volumeUnit": "GGBN_volume",
  "GGBN_weightUnit": "GGBN_weight"
}
```

The ones on the left in the above list would be hidden, unless "Show conflicting fields only" is unchecked.

If user (or auto merge) desires to carry over one of the fields on the right in the above list, the corresponding value from the field on the left would also be carried over.

**Comment by chanulee1** [comment]
PartialDateUi appears on the merged record preview. Should it appear on the unmerged record previews as well? Precision field merging appears to be working as expected.


https://user-images.githubusercontent.com/103299204/216681052-8e78e41e-32d1-4df0-be0e-96cd9208ce66.mp4

https://coldfish-agent-merging.test.specifysystems.org/specify/overlay/merge/Agent/?records=16387%2C17583

**Comment by maxxxxxdlp** [comment]
No. The precision is clear based on the value in the date field. It appears in the first column just because it can be edited - when read only it is not needed

**Comment by grantfitzsimmons** [comment]
> Fixed:
> 
>     1. PartialDateUi is now shown instead of simple date fields
> 
>     2. The precision field is not visible, unless the date field is not visible, or "Show conflicting only" is unchecked
> 
>     3. Merging the date field also merges the precision field. Merging the precision field does not merge the date field.

Should we consider hiding precision date entirely due to https://github.com/specify/specify7/issues/3930?

@melton-jason @maxxxxxdlp

**Comment by maxxxxxdlp** [comment]
no. I would suggest instead adding business rules to remove precision when date is removed.

but really, the date picker (PartialDateUi) was supposed to do that already - however, that component has been very bug prone in the past, and does not have tests.

My suggestion thus would be to first PartialDateUi bug, rather than remove a feature
