### ISSUE TITLE
Aggregated field can be unmapped in query builder

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#2935]
https://user-images.githubusercontent.com/64045831/216409973-2a8ae69c-ae9b-4950-a6c4-08eaedd5ecfb.mp4

**Note** 
This bug can only occur if there is at least one other mapped field present. Specify disables the `Query` button if the aggregated field is the _only_ field in the list of fields, but enables it once another field is present

**Comment by emenslin** [comment]
The current behavior (7.9.6) no longer throws an error, however, you can still run a query with just an unmapped field and it just seems to show results for every record in the table. Leaving this open because it seems like weird behavior but someone else can close it if this is what it's supposed to be

https://github.com/specify/specify7/assets/150940840/44284de9-cff7-4b2b-8874-233751f839af

**Comment by emenslin** [comment]
Closing in favor of #3649 as there is no longer an error
