### ISSUE TITLE
`tooltips`: Custom and browser tooltip both displaying

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3014]
![image](https://user-images.githubusercontent.com/37256050/219829907-ee006074-cc64-4c1d-9249-3067c4f38f5f.png)

https://user-images.githubusercontent.com/37256050/219829902-5d4644cb-3763-49a4-a268-2c0540355481.mov

Only in Firefox, not Chrome

**Comment by maxxxxxdlp** [comment]
Able to also replicate in Chrome, just not right away.
Happens if you quickly move your cursor between different tooltips.
Fixed

**Comment by maxxxxxdlp** [comment]
Did a bit of general refactoring. Please test.

Also, just noticed that disabled buttons still have modern tooltips but only in Firefox because of a React bug - https://github.com/facebook/react/issues/19419 (according to the spec, events should not be fired on disabled elements, but react seems to not apply this rule consistently across browsers)

Thus, I recommend testing tooltips both in Chrome and Firefox.
