### ISSUE TITLE
Can not access query builder from query combo box in auto-generated form

### ISSUE THREAD

**Issue by melton-jason** [specify/specify7#3047]
https://user-images.githubusercontent.com/64045831/221268267-fe61445a-6016-48e0-87c6-b8245cc608a6.mp4

**Additional Context**
The affected field (Address of Record) is hidden in the schema

Branch: `production`
OS: Windows 11
Browser: Chrome

**Comment by maxxxxxdlp** [comment]
Two issues:
Unclickable button not showing up as disabled - fixed
Buttons is unclickable - this is because there is no type search defined for the Address Of Record (Type search defines which columns to search on) - I refactored the code to not need it for the search dialog as it was barely used by it

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-7-release-announcement/1079/1
