### ISSUE TITLE
Saving new query doesn't prompt for a query name.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#305]

**Comment by benanhalt** [comment]
Please test saving new queries, existing queries with changes, and "Save as".

**Comment by garrettgirard** [comment]
All of the above seem to be working. The only thing I noticed is that if you make any changes to an existing query and click "Save", the dialog box that pops up when you choose "Save As" pops up for a second and then disappears. This isn't really an issue, it just happens. It might be helpful, since it shows you that the query is actually being saved.
