### ISSUE TITLE
Aggregator Editor: Picklist render problems

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3070]
"Formatter" picklist not rendered correctly?

https://user-images.githubusercontent.com/103299204/222269165-1c725f25-ff95-49e8-8461-618cb158aaf7.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/9/formatter/Agent/name/Agent
Browser: Chrome, Firefox
OS: Windows 10

**Comment by maxxxxxdlp** [comment]
This is not a bug.

Formatter is being rendered as a free-input field with suggestions rather than a pick list.

This is because formatter name is specified in XML as just name, not the ID (formatters don't have IDs), thus there is no referential integrity (i.e, deleting a formatter does not check for usages of the formatter).

Thus, a field might end up being set to a formatter that doesn't exist - UI has to handle that.

In addition, formatters might be defined at different levels (i.e, you could create the `DataObjFormatters` app resource at user, user type, collection, division or global level) - thus depending on the current user and current scope, the UI might be able to resolve the formatter name or not - thus we must allow for entering a formatter name that is not on the list.
