### ISSUE TITLE
Cannot select blank formatted records in qcbx

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3184]
When the fields included in the formatted are blank in the record, it cannot be selected from a qcbx.

https://user-images.githubusercontent.com/103299204/225414404-47a13a08-2016-4350-93cb-3a884ff65946.mp4

![image](https://user-images.githubusercontent.com/103299204/225414462-ea8eced6-b5d8-426d-9450-32b9948b0d6c.png)

branch: `edge`, `7.8.8`

**Comment by maxxxxxdlp** [comment]
The bug here is that the browser thinks that query combo box does not have a value just because it's formatter is empty, thus not allowing to save a form (for a required field)

@grantfitzsimmons Would it be better to have a generic formatting for resources that would otherwise have empty formatters (table name #id, ie `Agent #123`)

or should we instead use a ` ` (space character) just as a workaround for the required field issue

In either case this won't affect query builder/exports/reports, just presentation in query combo boxes

**Comment by grantfitzsimmons** [comment]
> @grantfitzsimmons Would it be better to have a generic formatting for resources that would otherwise have empty formatters (table name #id, ie `Agent #123`)

I like the generic formatting idea just for query combo boxes

**Comment by chanulee1** [comment]
Seems to still happen on `xml-editor`.

Formatter includes only first name and middle initial, causing problems for records with only a last name/blank

https://user-images.githubusercontent.com/103299204/226435190-2a9e65d6-cf12-4b03-baf4-ade5e02ef0a3.mp4


.

**Comment by maxxxxxdlp** [comment]
Fixed:

![Screenshot 2023-04-14 at 10 59 02](https://user-images.githubusercontent.com/40512816/232095558-9c77c51a-a6a2-4d75-97ea-ff0b7e6251fd.png)

When testing, please make sure that the formatting is non-blank both in query combo box results, and in the query combo box when you select a value, save form and reload the page.

**Comment by chanulee1** [comment]
Looks good. Able to select records generically formatted records. Formatting is non-blank in qcbx results and in qcbx after selecting, saving, and reloading page.
