### ISSUE TITLE
`statspage` 1 - Initial Load and Permission Migrations

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#3196]
**Initial Load**

The most important part of the process, since this part is done only once and hence isn't tested as much as other components of the stats page. Also, a lot of things can go wrong here as it needs to make migrations for assigning permissions.

**Steps to test this**
1. Open a database that did not have a stats page before in a branch different than `statspage`. This might be tricky since we already put a stats page on a lot of databases before. I will recommend making a fresh copy of a database other than `coldfish`, preferably one which has multiple collections and a lot of users. 
2. Go into Security and Accounts and make sure there is a user with a `Full Access - Legacy` role. The name must match exactly. Further, I will recommend making another `Full Access - Legacy` role - Specify doesn't enforce unique role names. There now should be at least two `Full Access - Legacy` roles, and multiple users assigned to these roles (more the better)
3. Load the `statspage` branch on the same database and first log in as a `Collection Admin`. 
4. **Before going to the stats page, go to network and throttle your network speed to Slow 3G**. This is done to induce artificial delay - a lot of bugs are hard to catch if the page loads too fast, especially for stats. 
5. Go to the stats page (the icon **should** be visible). You should default to the first page in the Shared category - make sure it loads correctly. 
6. The top of the page should say 'Last refreshed now'. You should have edit access - you should be able to click on 'Edit' and go into edit mode. If the items haven't yet loaded, try deleting items or adding items, essentially anything that could cause a layout change - this is why the artificial delay was added. 
7. Go to a page in the 'Private' category. It should also say 'Last refreshed now', and the items should load then. 
8. Log out as the `Collection Admin`, and log in as a user with the `Full Access - Legacy` role in the same collection. Go to the stats page. If you have tried this within 24 hours, the page in the Shared layout should not refresh again. You should also have edit access, this is very important as `Full Access - Legacy` should have edit access.
9. Go to a page in the 'Private' section, it should load on the spot and say 'Last refreshed now'.
10. Log out as the `Full Access - Legacy`, and log in as the user with any other role (not `Collection Admin` or `Full Access - Legacy`). Go to the stats page, and you should **not** have edit access to Shared layouts. You can update the shared layout, but not edit it. However, if you go to a page in the Private section, you should have edit access. 
11. Play around and make sure the layout is loaded correctly, and clicking on 'Refresh' refreshes the page correctly. If the initial layout has been loaded, then this test is done. Don’t log out as the current user as the next issue requires it.

**Comment by grantfitzsimmons** [comment]
Tested with `nhmd_test_03_08_23` extensively:

---

- [x]  Open a database that did not have a stats page before in a branch different than `statspage`. This might be tricky since we already put a stats page on a lot of databases before. I will recommend making a fresh copy of a database other than `coldfish`, preferably one which has multiple collections and a lot of users. 
- [x]  Go into Security and Accounts and make sure there is a user with a `Full Access - Legacy` role. The name must match exactly. Further, I will recommend making another `Full Access - Legacy` role - Specify doesn't enforce unique role names. There now should be at least two `Full Access - Legacy` roles, and multiple users assigned to these roles (more the better)
- [x]  Load the `statspage` branch on the same database and first log in as a `Collection Admin`. 
- [x]  **Before going to the stats page, go to network and throttle your network speed to Slow 3G**. This is done to induce artificial delay - a lot of bugs are hard to catch if the page loads too fast, especially for stats. 

This was very fun.

- [x]  Go to the stats page (the icon **should** be visible). You should default to the first page in the Shared category - make sure it loads correctly. 
- [x]  The top of the page should say 'Last refreshed now'. You should have edit access - you should be able to click on 'Edit' and go into edit mode. If the items haven't yet loaded, try deleting items or adding items, essentially anything that could cause a layout change - this is why the artificial delay was added. 
- [x]  Go to a page in the 'Private' category. It should also say 'Last refreshed now', and the items should load then. 
- [x]  Log out as the `Collection Admin`, and log in as a user with the `Full Access - Legacy` role in the same collection. Go to the stats page. If you have tried this within 24 hours, the page in the Shared layout should not refresh again. You should also have edit access, this is very important as `Full Access - Legacy` should have edit access.
- [x]  Go to a page in the 'Private' section, it should load on the spot and say 'Last refreshed now'.
- [x]  Log out as the `Full Access - Legacy`, and log in as the user with any other role (not `Collection Admin` or `Full Access - Legacy`). Go to the stats page, and you should **not** have edit access to Shared layouts. You can update the shared layout, but not edit it. However, if you go to a page in the Private section, you should have edit access. 
- [x]  Play around and make sure the layout is loaded correctly, and clicking on 'Refresh' refreshes the page correctly. If the initial layout has been loaded, then this test is done. Don’t log out as the current user as the next issue requires it.
