### ISSUE TITLE
TypeError: failed to fetch when editing Cat #

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3290]
While creating a new Collection Object and editing the Cat #, I got a `TypeError: Failed to fetch`

**To Reproduce**
1. Go to sp7demofish on v7.8.9-prerelease, use the KUFishTeaching Collection
2. Click on Data Entry and enter a 5 digit Cat # and then delete 4 digits to end up with only 1
3. See error

**Expected behavior**
I can edit the digits 

**Screenshots and Crash Report**
[Specify 7 Crash Report - 2023-04-03T20_47_31.678Z.txt](https://github.com/specify/specify7/files/11142444/Specify.7.Crash.Report.-.2023-04-03T20_47_31.678Z.txt)
 
![Screenshot 2023-04-03 at 3 47 05 PM](https://user-images.githubusercontent.com/53784701/229626054-2e7b64a5-682f-4241-85c4-ad68704703a6.png)

**Desktop:**
 - OS: Mac OSx Ventura
 - Browser: Chrome
 - Specify 7 Version: 7.8.9-prerelease

**Database Name:** 
sp7demofish

**Comment by maxxxxxdlp** [comment]
Congrats on finding your first Specify bug and opening a GitHub issue!

This particular bug was likely caused by someone updating the test server or by it updating itself (on any changes on the test panel configuration, all deployments might be inaccessible for a few seconds - https://github.com/specify/specify7-test-panel/issues/26), thus front-end failed to reach back-end.

Can you try to replicate this bug again? If it doesn't happen, that would mean it's likely just the test server updating. If you can reproduce it again, that would mean it's a real bug

**Comment by carlosmbe** [comment]
Thanks, let's hope they're aren't any new bugs today.

After attempting to reproduce the bug for a third time. It most likely was just the test server updating.
: D

**Comment by melton-jason** [comment]
I was personally not able to recreate this issue. Of all the errors you see while testing on the test panel you will most likely see `TypeError: Failed to Fetch`. It is a known issue, and 'fixing' it would probably require adding logic to dismiss that particular error message or having a test panel server which does not update its deployments frequently. 

As @maxxxxxdlp pointed out, when you receive this specific error message, try and recreate what you were trying: more often than not someone was creating/removing a new deployment or making some other change on the test server (which updates the deployments). 

Also, congrats on the first issue! 🎉 
Thank you for being descriptive in the issue body!

Totally optional, but if you want to make your issue more perfect than it is already, you could be more specific in the title. `Edit Cat # Issue` is somewhat vague and _could_ describe exactly what the issue is and what causes it.
Something like `TypeError: failed to fetch when editing Cat #` makes it very clear _exactly_ what the problem is and what causes it (this also makes it easier to search/identify in the future. For example, this issue would be very easy to pick out from a crowd if someone were trying to fix a `TypeError: failed to fetch` problem)

Nice job all around! 
Happy Testing! 😀

**Comment by carlosmbe** [comment]
Thanks for the feed back @melton-jason. I'll do my best to make it even better next time. I'm going to update the title right now.

I really appreciate all the advice, you've all given me today.

**Comment by maxxxxxdlp** [comment]
> I was personally not able to recreate this issue. Of all the errors you see while testing on the test panel you will most likely see TypeError: Failed to Fetch. It is a known issue, and 'fixing' it would probably require adding logic to dismiss that particular error message or having a test panel server which does not update its deployments frequently.

There is actually to remove the brief downtime:
Currently it runs docker-compose to rebuild the containers.
That is needed to deploy new containers, but also to restart nginx with new configuration.
If we were outside of docker, we could just run this line to reload the configuration without causing downtime: https://serverfault.com/questions/378581/nginx-config-reload-without-downtime. Not sure how to do that in docker (because we have to run `docker-compose up --build` anyway to deploy new instances, and that's the command that causes the downtime)
