### ISSUE TITLE
Make relative dates refresh as needed

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3301]
**Describe the bug**
The Last Refreshed X time ago on the top of the Stats page only refreshes when another UI Element changes. This can be confusing since 10 minutes can pass but if the user does not change any other element. The timer will remain unchanged which can leave the user uncertain of how accurate their current stats are. For example, stats refreshed 30 minutes ago can be shown as 8 seconds ago.

**To Reproduce**
1. Go to any stats page and refresh the page
2. Leave the stats page alone and do not make any changes 
3. See error

**Expected behavior**
A more informative way of being aware of when these stats were refreshed.

**Describe the solution you'd like**
More frequent auto updates of that timer.

**Describe alternatives you've considered**
A more vague title. Like "A few seconds ago", "Quite some time back". "A While Ago"

**Screen Recording**
It looks like a minute worth of a still image but that's how it little refreshs.

https://user-images.githubusercontent.com/53784701/229926835-190da0e5-9d8b-44a9-a72c-3a89a3f5cfa3.mov

**Desktop:**
 - OS:  Mac OSx Ventura
 - Browser: [Chrome]
 - Specify 7 Version: [statspage branch in test panel ]

**Database Name:** NHMD_TEST

**Reported By**
Carlos @carlosmbe 

**Additional context**
Logged in as petrifiedroadkill
IN NHMD AMBER Collection

**Comment by maxxxxxdlp** [comment]
This applies everywhere a relative date is visible, not just in the stats page
We already had an issue for this (#1610) but I will close that one as duplicate because you provided more details

**Comment by realVinayak** [comment]
Solution: Extract the string into a state and use a setInterval to update just the state string every 5 seconds (or something other time)

**Comment by maxxxxxdlp** [comment]
That was going to be my solution
Except need to test the performance impact of that (for pages that have a lot of relative dates) - i.e, the query list dialog when you have 500 queries or 500 data sets
Thus, it might be necessary to make the solution a bit fancier where the update interval is 5 seconds for <1min, then 1min for <1hr and 1hr for the rest

**Comment by realVinayak** [comment]
The fancier solution looks like a good solution!

**Comment by grantfitzsimmons** [comment]
@carlosmbe @realVinayak Can you write a more detailed explanation of what you expect and what you should see?

i.e. Make a screenshot of the page and say "after 30 minutes you should see a refresh"

We need to determine what the proper behavior is for this.

@realVinayak How often is the stats page refreshed if we don't touch anything?

**Comment by realVinayak** [comment]
If you don't touch anything, and don't even reload the page, it will never refresh. If you reload the page, and if 24 hours have passed (this is actually a preference - would be set to 0 for release), it will auto-refresh. Other than that, you'd have to click on 'Refresh'. Does that clear it up?

The request, if I understood it properly, is that to make relative dates (like "10 minutes ago") auto-increment automatically. So, after a minute it should say "11 minutes ago". Right now, if you don't click on anything, it would continue to say "10 minutes ago" - until you click on anything. So stats could have been refreshed 5 hours ago, but since user didn't click on anything, it would say 10 minutes ago.
We were aware of this when we designed it, and didn't think it was important enough to fix because workaround is so simple - click on anything. Let me know if that has changed.
