### ISSUE TITLE
`xml-editor` Overflow in xml editor dialog

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3322]
https://user-images.githubusercontent.com/103299204/231005527-edbdbf8d-d390-4f7b-a79d-5c382b17f831.mp4

Browser: Chrome, Firefox

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/184/formatter/Accession/0

**Comment by chanulee1** [comment]
With long mapping lines, typing in any text field in the dialog causes scroll bar to spasm.

https://user-images.githubusercontent.com/103299204/231223082-f35993f5-dfde-4dfd-8373-a9cd283c72b5.mp4

**Comment by maxxxxxdlp** [comment]
> Overflow in xml editor dialog

Fixed by enforcing min-width for it (which causes horizontal scroll bar in the dialog). A better fix would be to use CSS container queries to replace the table layout with a list layout on narrower screens, but that would be too much work for what it's worth.

> With long mapping lines, typing in any text field in the dialog causes scroll bar to spasm.
> Also sometimes happens with aggregator editor:

Fixed in [a2d109b3d](https://github.com/specify/specify7/commit/a2d109b3d)

**Comment by chanulee1** [comment]
Looks good. Cannot replicate issue.
