### ISSUE TITLE
`xml-editor` Tooltips persist and can float off of dialog

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3330]
https://user-images.githubusercontent.com/103299204/231230930-e9f2deac-3aaf-43ba-880e-818b90d124b9.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/app-resource/184/formatter/Agent/4

**Comment by maxxxxxdlp** [comment]
Fixed the tooltip being visible even when an element is off the screen

Making the tooltip not appear when the dialog is closed is trickier so it wasn't implemented. This is because when dialog is closed, the react-modal library returns focus back to the last focused element - which triggers the tooltip on the last focused element. There is no simple way in JavaScript to differentiate between user-triggered focus and program-triggered focus

**Comment by chanulee1** [comment]
Tooltip not visible when element is off screen. But, unable to trigger tooltips in the dialog after tooltip goes off screen.


https://user-images.githubusercontent.com/103299204/232850901-41731ec5-9f16-4be8-8ab9-e1ac40ee769c.mp4
