### ISSUE TITLE
`xml-editor` Unable to create a Leaflet Layers resource

### ISSUE THREAD

**Issue by chanulee1** [specify/specify7#3339]
Also, 404 error page is stacked on top of the app resource page.

https://user-images.githubusercontent.com/103299204/231554261-0b8ba785-dfe5-4b88-b4a3-3fcd0b19d1c0.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/

**Comment by chanulee1** [comment]
Able to create Leaflet Layers resources. Is the 404 error page issue included in this fix?

**Comment by maxxxxxdlp** [comment]
Fixed.
Now any 404 error that is triggered when you are in an overlay will replace the overlay with a 404 dialog.
Any 404 error that is triggered when you are not in an overlay will replace the main content with a 404 page (rather than append 404 to the content)

In production, the easiest way to trigger a 404 is to try to display a resource that doesn't exist (make up any resource id that is not present in the database)

**Comment by CarolineDenis** [comment]
Fixed in xml-editor
