### ISSUE TITLE
Modern tooltip covering QCBX

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3401]
**Reported By:** RBGE

> We have been finding that the position of the pop up for Query Combo Boxes which lists ‘Searched Fields’ is getting in the way of the dropdown:
>  
> ![image](https://user-images.githubusercontent.com/37256050/234076417-1978cf75-0ec6-456f-8096-b34c1a2e4643.png)

**Comment by maxxxxxdlp** [comment]
@CarolineDenis this can be fixed by making that tooltip appear on top of the box instead.

Read the tooltip documentation to see how to achieve that - https://github.com/specify/specify7/blob/51ea5579edffeb1c36edb93612efe140f5046c98/specifyweb/frontend/js_src/lib/components/Molecules/Tooltips.tsx#L1-L57

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify-7-8-11-release-announcement/1174/1
