### ISSUE TITLE
When Distinct is true for tree queries, crash occurs

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3466]
When a query on a tree table such as Taxon is searched as "Distinct" in Specify 6, it crashes Specify 7 when run. 

This can be remedied by exporting the query, editing the JSON directly (change `"selectdistinct": true` to `"selectdistinct": false`), then re-import.

```json
         "id": 239,
	"contextname": "Taxon",
	"contexttableid": 4,
	"countonly": false,
	"formatauditrecids": false,
	"isfavorite": true,
	"name": "Taxon Query",
	"ordinal": 32767,
	"remarks": null,
	"searchsynonymy": null,
	"selectdistinct": true,
	"smushed": null,
	"sqlstr": null,
```

https://pripaleoschemaupdatedcm202304211540-v7810-prerelease.test.specifysystems.org/specify/query/238/

When run, the following crash occurs:

```
InvalidRequestError at /stored_query/ephemeral/ No entities to join from; please use select_from() to establish the left entity/selectable of this join 
```

[Specify 7 Crash Report - 2023-05-08T19_33_29.906Z.txt](https://github.com/specify/specify7/files/11424545/Specify.7.Crash.Report.-.2023-05-08T19_33_29.906Z.txt)

**Comment by carlosmbe** [comment]
**Describe the bug**
Specify 6 Distinct Queries will cause a crash when ran in 7.
See screen shots for comparison.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to `PriPaleo Updated` and log in as `testuser`
2. Go to the saved `Taxon Query` query
3. Run and see error
4. Recreate the query in 7 and it will not crash

**Expected behavior**
Automatic disable of Distinct so that it can run issue free.

**Screenshots**
<img width="1792" alt="Screenshot 2023-05-08 at 2 31 50 PM" src="https://user-images.githubusercontent.com/53784701/236916371-ab07d053-510c-4b5c-a4e2-fa030abd4d1a.png">
<img width="1785" alt="Screenshot 2023-05-08 at 2 34 31 PM" src="https://user-images.githubusercontent.com/53784701/236916377-19ac6c76-88e3-455e-a7ba-f7ea867b66d2.png">

[Specify 7 Crash Report - 2023-05-08T19_36_35.845Z (1).txt](https://github.com/specify/specify7/files/11424562/Specify.7.Crash.Report.-.2023-05-08T19_36_35.845Z.1.txt)
[Specify 7 Crash Report - 2023-05-08T19_36_35.845Z.txt](https://github.com/specify/specify7/files/11424563/Specify.7.Crash.Report.-.2023-05-08T19_36_35.845Z.txt)
[Specify 7 Crash Report - 2023-05-08T19_36_20.659Z (1).txt](https://github.com/specify/specify7/files/11424564/Specify.7.Crash.Report.-.2023-05-08T19_36_20.659Z.1.txt)
[Specify 7 Crash Report - 2023-05-08T19_36_20.659Z.txt](https://github.com/specify/specify7/files/11424565/Specify.7.Crash.Report.-.2023-05-08T19_36_20.659Z.txt)

<img width="1792" alt="Screenshot 2023-05-08 at 2 36 41 PM" src="https://user-images.githubusercontent.com/53784701/236916845-764a28f2-8c8b-4d0e-95b3-f0ceef6de59c.png">
<img width="1790" alt="Screenshot 2023-05-08 at 2 36 28 PM" src="https://user-images.githubusercontent.com/53784701/236916846-857cbb1c-155d-4474-877b-93df0cac012e.png">
<img width="1792" alt="Screenshot 2023-05-08 at 2 35 36 PM" src="https://user-images.githubusercontent.com/53784701/236916847-66b9085c-4ca2-4439-a41b-4e4293a351a0.png">

**Desktop:**
OS: Mac OSx Ventura
Browser: Chrome
Specify 7 Version: 7.8.10-prerelease

**Database Name:** Updated Pripaleo

**Comment by emenslin** [comment]
Fixed
