### ISSUE TITLE
`Edit Query` Button Changed to -> `Edit SP Query`

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3517]
**Describe the bug**
First noticed in [Pull#3513 ](https://github.com/specify/specify7/pull/3513). Despite not touching the Button its been renamed.

It's in Edge. Not in 7.8.11 as of 19 May 2023

**To Reproduce**
1. Run a query 
2. Scroll down to the results
3. See error on top of screen

**Expected behavior**
`Edit Query` Button **NOT** `Edit SP Query`

**Screenshots**
Issue
<img width="1792" alt="Screenshot 2023-05-19 at 1 00 12 PM" src="https://github.com/specify/specify7/assets/53784701/81214e6f-a7e0-4f30-9795-905a1d828e72">

Solution 
<img width="1792" alt="Screenshot 2023-05-19 at 12 59 48 PM" src="https://github.com/specify/specify7/assets/53784701/03956ca5-deaa-4fee-9cea-7db5082a584b">

**Comment by CarolineDenis** [comment]
@carlosmbe 
The label being changed in the button is not an issue. 
Go in: 
- Schema Config 
>> Select English 
>> Check Show Advanced Tables 
>> Select SpQuery
>> Change "Caption" to Query 
>> Save  
>>>Go Back to Query Builder and see the change

**Comment by carlosmbe** [comment]
@CarolineDenis 
Noted. Can confirm that this works.
However, this is still a bit strange.
In 7.8.11. Even though the caption is also "SP Query" the Edit Button does not change to match the Caption, "Edit SP Query" like in Edge.

**Comment by maxxxxxdlp** [comment]
> like in Edge

Could be because one of your browsers has the old localization string cached. Can you try in incognito?
Or clean the cache for that tab?


![Screenshot 2023-05-22 at 13 27 36](https://github.com/specify/specify7/assets/40512816/cb06d097-a609-4d7d-a7e7-6f989143b8b2)

**Comment by carlosmbe** [comment]
@maxxxxxdlp 
Tested on a different computer and in incognito. Can confirm it's not due cache.

**Comment by carlosmbe** [comment]
@CarolineDenis 
Would it be possible to make the Button text static like in older versions or was it made dynamic for a specific reason.

 I feel that being able to rename this Button through the schema config can lead to users being confused.

**Comment by maxxxxxdlp** [comment]
It was made dynamic because users asked to be able to control it (instead of it being hardcoded in source code)
The table labels everywhere in the UI are now coming from the schema config - that's the canonical place
Issue: https://github.com/specify/specify7/issues/2420
Whatever table label you pick in the schema config, that will be used everywhere across the UI so it doesn't make sense to hardcode the label in this particular button just because the table label in schema config is not what you expect - they would still have the same "problem" everywhere else
