### ISSUE TITLE
Add search box to home page

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3540]
**Requested By:** NMC

**Comment by maxxxxxdlp** [comment]
Isn't it one click away? - it's always on the side menu
In fact, it being on the side menu is maybe even better because the side menu is always there, where as the home page is not always visible
Also, https://discourse.specifysoftware.org/t/search-specify-in-your-browsers-search-bar/1087 might be what they are looking for

**Comment by CarolineDenis** [comment]
Implement search box above the splash screen

**Comment by maxxxxxdlp** [comment]
The feature that Caroline did where search field is focused automatically as soon as the dialog is open (if I correctly remember the way it's implemented) makes this even simpler

Though of course, you could still add it to the home page
