### ISSUE TITLE
Nested Query Builder Can Not Create All Items CSV

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3616]
**Describe the bug**
If you open the Query Builder from let's say Data Entry and try to create a CSV from the query you just built. It will not export. I also tested this on the new Selected Query Branch and they work fine.

**To Reproduce**
1. Go to Data Entry -> Taxon -> Parent of Taxon
2. Click on the search on the side
3. Enter Query Builder
4. Run something and click on `Create CSV`
5. See Error

**Expected behavior**
It is exported without an issue.

**Beautiful Screen Recording**

https://github.com/specify/specify7/assets/53784701/b0491cf7-611a-4f88-b1c4-4a6f6db889ff

**Comment by maxxxxxdlp** [comment]
The dialog says "A notification will appear when the export file is complete and ready for download"

Does the notification appear after a while in the side menu? If yes this is working as expected

**Comment by carlosmbe** [comment]
@maxxxxxdlp It does not.

**Comment by maxxxxxdlp** [comment]
Weird. The export mechanism shouldn't be affected by query being nested. Are you sure this works correctly when the query builder is not in a dialog but opened standalone?

**Comment by CarolineDenis** [comment]
Confirm that the export doesn't work in a dialog but does in stand alone.

**Comment by maxxxxxdlp** [comment]
weird. when someone fixes this, could you assign me on the PR for review? I am just curious what's going on here

**Comment by CarolineDenis** [comment]
The backend query fails because the key 'fields' is not present in the serialized resource.

**Comment by CarolineDenis** [comment]
Findings and potential solution: 

- When exporting query result we need the fields from the queryResource.toJSON() (line 53 in Export.tsx) 

- The fields are set only if the condition typeof getQueryFieldRecords === 'function' is true. 

- getQueryFieldRecords is a function if the variable saveRequired is true otherwise it's undefined. (line 184 in Wrapped.tsx) 

- saveRequired depends on 3 conditions:  const saveRequired =

    (isResourceModified || state.saveRequired) && !isEmbedded; (line147 in Wrapped.tsx) 

- if we take off the condition " !isEmbedded " from the saveRequired variable, the export works finally. 

===> @maxxxxxdlp do you remember why you had that extra condition there or can we take it off in order for the export to work?

**Comment by maxxxxxdlp** [comment]
`isEmbedded` is there to not set unload protect for when query is opened in a dialog (modifying the embedded query would then prompt the user to save - it shouldn't as this is an autogenerated ephemeral query - if they want to save it, there should be a "Save" or "Open in new tab" button that would open a proper full screen query - https://github.com/specify/specify7/issues/3000)

The `getQueryFieldRecords` is undefined if there are no unsaved changes. The intention is that query.fields contains the query fields, but they might not be up to date (because updating that state on any change would be expensive - i.e. as the user is typing into the query filter text field, that would generate a lot of state updates). Thus, if some component needs to get up to date access to the fields, it calls getQueryFieldRecords() instead.

> This can probably be refactored/simplified when we get rid of Backbone as I remember difficulty with updating backbone and syncing that with react being part of the reason for this strange design.

The bug is that saveRequired is being used to mean two different things: in some places it is used to indicate if changes were made to the query, in other places it is used to indicate if we need to prompt the user to save changes - those are not the same.

So the solution would be to split saveRequired into two variables, only one of which would have the isEmbeeded condition, and then check all the usages to see which one makes sense where (i.e, for unload protect, isEmbeeded check is needed; for getQueryFieldRecords it isn't; then check the other usages)
