### ISSUE TITLE
Slow load performance when using "Browse in forms"

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3638]
https://github.com/specify/specify7/assets/37256050/8ba54457-0c2e-4c7c-b780-1c3c76108536

> Several people have been experiencing an issue with the browse in forms view being slow to load fully – the first part will load, but as you scroll down the page remains white for several seconds.
> 
> This only seems to be limited to ‘browse in forms’ when looking at results from a query. This seems to happen in both Firefox and Chrome.

**Reported By:** Royal Botanic Gardens Edinburgh (RBGE)

**Comment by grantfitzsimmons** [comment]
@chanulee1 Can you take a look at this and let me know what you think early next week?

**Comment by melton-jason** [comment]
@grantfitzsimmons Is this issue for slow performance compared to previous versions of Specify 7, or just generally poor performance when compared to opening a normal form, record set, etc?

I am sure other browsers have a similar feature, but you can 'somewhat' empirically test this in Google Chrome. 
Chrome has the 'Performance Insights', 'Performance', and 'Recorder' tools in its Developer Tools you can use to gather and measure performance.  
If this issue is regarding slow performance from a previous version of Specify 7, we can use these tools to measure the difference, and maybe determine which component is causing the slow down.

**Comment by grantfitzsimmons** [comment]
I think it is slow overall, not necessarily in comparison to previous versions.

**Comment by emenslin** [comment]
Fixed
