### ISSUE TITLE
7.9 Stats Page Buttons Do Not Match The Rest of Specify 

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3661]
**Describe the bug**
Title.
See Screen Shots of the Top Buttons.

**To Reproduce**
1. Go to Stats Page
2. See error

**Screenshots**
<img width="1624" alt="Screenshot 2023-06-22 at 2 32 49 PM" src="https://github.com/specify/specify7/assets/53784701/216041f6-5cf6-4bdd-99a5-b04a1101a30c">

# VS 

<img width="1792" alt="Screenshot 2023-06-22 at 2 33 12 PM" src="https://github.com/specify/specify7/assets/53784701/1074c4b8-9c78-4368-b83a-468df2fc80d1">

**Desktop:**
 - OS: Mac OSx
 - Browser: Chrome
 - Specify 7 Version: 7.9 Dev
 
**Database Name:** NHMD

**Comment by carlosmbe** [comment]
You could probably use  #3527 as a reference

**Comment by maxxxxxdlp** [comment]
The inconsistency is actually in more places:
- Preferences page
- Security Page
- Schema Viewer

I do like how larger buttons look, but they also take more space

Perharps we should consider using the larger buttons everywhere except for workbench because workbench (and workbench mapper) has a ton of buttons in the toolbar?

**Comment by grantfitzsimmons** [comment]
I agree with @maxxxxxdlp
