### ISSUE TITLE
Incorrect Language in Navigation Bar and Other Places

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3673]
**Describe the bug**
If you change the language. Certain aspects are not changed despite Specify having a the translated word.

I used Russian for this example since it's a complete but issue persists for the others.

Mainly noticeable for workbench.

Stats Page also has issues

**Screenshots**
<img width="194" alt="Screenshot 2023-06-23 at 4 52 20 PM" src="https://github.com/specify/specify7/assets/53784701/c0c1ed81-af17-4341-b022-0151fb56592c">

<img width="1596" alt="Screenshot 2023-06-23 at 4 52 51 PM" src="https://github.com/specify/specify7/assets/53784701/1af5c64f-e3dd-452c-9712-e49527dd79ca">

<img width="1219" alt="Screenshot 2023-06-23 at 4 55 16 PM" src="https://github.com/specify/specify7/assets/53784701/3a11faac-e6f3-447f-bf15-dcce850728c9">

**Desktop:**
 - OS: Mac
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by maxxxxxdlp** [comment]
Dataset names are not translated. Nor are record set names, query names and etc - it's up to the user to create a name for those in any language they wish.

Original stats page item names are translated, but only to the language you used when you opened it the first time - after that, we can't be renaming the items without user's content as that could lead to loss of data

The "Name", "Timestamp Created" and "Timestamp Modified" messages in the dialog on the last screenshot are not translated because those are coming from the schema localization - in user preferences you can change UI language and you can change the schema (forms) language - unless you set both to the same language, you will see an inconsistency like this
