### ISSUE TITLE
`QueryComboBox.tsx` is missing a check to ensure resource is not `null` or `undefined`

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3749]
# 🤖 AI DISCLAIMER

This warning was created by Raycast AI. I have no idea if it's accurate, so please close this issue if it is not.

---

The code is missing a check to make sure `﻿resource` is not `﻿null` or `﻿undefined` before attempting to clone it. Otherwise, it will cause a runtime error.

**File:** https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/components/FormFields/QueryComboBox.tsx

```tsx
import React from 'react';
<DataEntry.Edit
  aria-pressed={state.type === 'ViewResourceState'}
  disabled={
    formatted?.resource === undefined ||
    collectionRelationships === undefined
  }
  onClick={handleOpenRelated}
/>
{canAdd ? (
  <DataEntry.Add
    aria-pressed={state.type === 'AddResourceState'}
    onClick={(): void =>
      state.type === 'AddResourceState'
        ? setState({ type: 'MainState' })
        : setState({
type: 'AddResourceState',
resource: pendingValueToResource(field),
          })
    }
  />
) : undefined}
{hasCloneButton && typeof resource === 'object' && (
  <DataEntry.Clone
    disabled={formatted?.resource === undefined}
    onClick={(): void =>
      state.type === 'AddResourceState'
        ? setState({ type: 'MainState' })
        : loading(
formatted!.resource!.clone(true).then((resource) => retake setState({
    type: 'AddResourceState',
    resource, retake })
)
          )
    }
  />
)}
<DataEntry.Search
  aria-pressed={state.type === 'SearchState'}
  onClick={
    isLoaded && typeof resource === 'object'
      ? (): void =>
          setState({
type: 'SearchState',
extraConditions: filterArray( retake getQueryComboBoxConditions({
    resource,
    fieldName: field.name,
    collectionRelationships:
      typeof collectionRelationships === 'object'
        ? collectionRelationships
        : undefined,
    treeData:
      typeof treeData === 'object'
        ? treeData
        : undefined,
    relatedTable,
    subViewRelationship, retake })
    .map(serializeResource)
    .map(({ fieldName, startValue }) =>
      fieldName === 'rankId'
        ? {

field: 'rankId',

operation: 'lessThan',

values: [startValue],
          }
        : fieldName === 'nodeNumber'
        ? {

field: 'nodeNumber',

operation: 'notBetween',

values: startValue.split(','),
          }
        : fieldName === 'collectionRelTypeId'
        ? {

field: 'id',
```

**Comment by melton-jason** [comment]
Is the code you provided the AI's suggested fix? 
Here is how the relevant section of code looks like in production
https://github.com/specify/specify7/blob/80a0c45581b5eb94224b0131f8d07b3fa311f0b9/specifyweb/frontend/js_src/lib/components/FormFields/QueryComboBox.tsx#L444-L460

Yes, it's true that if `formatted.resource` was null or undefined, an error would be thrown when the clone button is clicked. 

Notice the `disabled={formatted?.resource === undefined}` on the `DataEntry.Clone` component. 
The clone button will be disabled if either `formatted` or `formatted.resource` is undefined. 
So really, the code to clone the resource should never get called if the resource is null or undefined because the button will not be able to be pressed. 

Typescript would also normally throw this error, but we _know_ that `formatted.resource` will never really be undefined or null when the clone button is clicked. Thus we use the [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) to tell Typescript that we know better.

**Comment by grantfitzsimmons** [comment]
Thanks for the explanation, Jason!

**Comment by maxxxxxdlp** [comment]
we will look back at this issue as `oh I miss the good ol' days when AI was making silly mistakes and we could laugh about it` instead of `this damm machine is always right`

already feel like that a bit when arguing with ChatGPT - it always end up convincing me rather than the other way around 🤣

**Comment by melton-jason** [comment]
On the other hand, I think the AI knows more than it's letting on... :thinking: 

It's foreshadowing a new keyword in ES 15 :worried: 
Don't know what `retake` means or does, but now I am curious!

```ts
loading(
formatted!.resource!.clone(true).then((resource) => retake setState({
    type: 'AddResourceState',
    resource, retake })
)
```

(Besides these few hiccups though, I'm once again impressed by AI! Not a bad job at all)
