### ISSUE TITLE
Queries are throwing errors by default on the stats page

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3753]
```
IndexError at /stored_query/ephemeral/ list index out of range 
```

**Steps to Recreate:**
1. Open the "Digitized Last 7 Days" or "Collection Object" query
2. See crash
   [Specify 7 Crash Report - 2023-07-10T15_34_18.124Z.txt](https://github.com/specify/specify7/files/12003762/Specify.7.Crash.Report.-.2023-07-10T15_34_18.124Z.txt)

Many query items are showing "Error":

<img width="997" alt="Screenshot 2023-07-10 at 10 44 01 AM" src="https://github.com/specify/specify7/assets/37256050/c4c0e13a-ba63-4ddf-bc7f-663ad2171cc3">

https://herbrbge31323-v79-dev.test.specifysystems.org/specify/stats

**Comment by CarolineDenis** [comment]
@melton-jason I'll let you explain our findings about this

**Comment by melton-jason** [comment]
The underlying issue here was a formatters issue, and not a Statistics one. 
You would have received the same errors if you had recreated the queries in the QueryBuilder and attempted to run them. 

The error `IndexError at /stored_query/ephemeral/ list index out of range` was being thrown from the following line of code:
https://github.com/specify/specify7/blob/06e22a20e3a9d733f09b68c45b50a215853aa217/specifyweb/stored_queries/format.py#L158

The UIFormatters and DataObjFormatters AppResources have since been updated and the error no longer occurs.  
These two files were valid XML, but contained multiple instances of "invalid" nodes for formatters.

**Comment by grantfitzsimmons** [comment]
@melton-jason @CarolineDenis 

That configuration is the same as the one that currently exists in the production `herb_rbge` database, no? 
This sounds like something that could affect existing users. How were there "invalid" nodes in the `DataObjFormatters` file?
