### ISSUE TITLE
Cloned records have all determinations as current

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3786]
**Steps to Recreate:**
1. Go to this record: https://herbrbge31323-v7813.test.specifysystems.org/specify/view/collectionobject/1267753/?recordsetid=457
2. Click **Clone**
3. See cloned determinations are all current

https://github.com/specify/specify7/assets/37256050/707dc9df-821a-46db-9b66-cabf8d43ea90

`v7.8.13` and `v7.9-dev`

Chrome, macOS

**Comment by grantfitzsimmons** [comment]
> When I am creating a duplicate entry to modify using the clone button, and the original entry has more than one determination, the determinations all show up as current in the duplicate entry. I have to toggle off the extra current determinations in order to save the new record. (Otherwise, specify gives me an error message and can’t save the record.)

**Reported by:** Caleb at KU

**Comment by combs-a** [comment]
This is still present in `v7.9.3` and in the current `edge` for v7.9.4, adding more documentation:

**Describe the bug**
When cloning a collection object with multiple determinations, isCurrent is set to true on all of them.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to a Collection Object with multiple determinations
2. Click Clone
3. Go through the determinations list and see that isCurrent is true on all of them

**Expected behavior**
isCurrent should only be applied to one determination.

**Screenshots**
In `edge`:

https://github.com/specify/specify7/assets/71564869/063172f2-7fc4-4170-8caa-707f14f764bf

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`
- Database Name: `sdnhm_herps
- Collection name: `Herp-PC`
- User Name: `testuser`

[Specify 7 System Information - 2024-04-16T21 00 22.969Z.txt](https://github.com/specify/specify7/files/15002386/Specify.7.System.Information.-.2024-04-16T21.00.22.969Z.txt)

**Comment by emenslin** [comment]
New behavior, see #5022
