### ISSUE TITLE
Warning dialog before merging

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#3816]
Add a warning dialog when clicking on merge before proceeding with merge. 
*See @grantfitzsimmons text

**Comment by grantfitzsimmons** [comment]
> Before proceeding, please note that the following action may interrupt other users. This action may cause delays or temporary unavailability of certain features for Specify users. Please consider the impact on their experience.

How does this sound?

**Comment by maxxxxxdlp** [comment]
@grantfitzsimmons 

That sounds like the issue we were having with stats page queries making other pages not accessible

Are you sure this affects all users of a given specify instance and not just the current browser?

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp Good question and I will test that. 

The concern is that when running an agent merge process, which involves updating a large number of records in commonly used tables such as Collection Object, Collecting Event, Determination, etc., there is a possibility of overloading the DBMS. The merge process sends a request to modify thousands of records within a short time frame, potentially causing a higher priority for these requests over those sent by other users performing data entry tasks.

Consequently, there is a risk of interruption other users in Specify as requests from the merge process may supersede requests from other users, affecting their ability to create or edit records. What do you think about that?

**Comment by maxxxxxdlp** [comment]
To clarify, by "modify thousands of records" you mean if agent was used by a thousand records (i.e as determiner) those would be updated now?

While valid concern, I can't see how that's worse than doing a workbench upload or a tree merge, which we have been allowing people to do (although, not without issues)

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp 

> To clarify, by "modify thousands of records" you mean if agent was used by a thousand records (i.e as determiner) those would be updated now?

Exactly.
 
> While valid concern, I can't see how that's worse than doing a workbench upload or a tree merge, which we have been allowing people to do (although, not without issues)

I made the same point during our meeting today discussing the release. It is on par with a WorkBench upload or tree merge, but those two activities have caused a lot of grief for Specify users in the past (particularly Edinburgh, who have resigned themselves to only doing WorkBench uploads during an allotted period of time on Thursdays). I think some kind of warning for all of those activities would be warranted.

**Comment by maxxxxxdlp** [comment]
> there is a risk of interruption other users in Specify as requests from the merge process may supersede requests from other users

why not just allow user to try to click the "Save" button again if save failed (or to be safe, only allow that if it failed due to timeout) - that will catch all of the cases like this, not just those caused by agent merging, and won't require us to cripple/nerf every tool in specify (workbench uploads, then stats queries, now agent merging)

I had an issue or a comment somewhere about doing that - don't remember where.

The agent merging branch, XML editor branch, and business rule changes branches all did some advance in this area

i.e, the agent merging dialog already uses this logic - if merge fails for any reason, it lets you do it again without loosing data

**Comment by maxxxxxdlp** [comment]
> I think some kind of warning for all of those activities would be warranted.

at least add a checkbox to that dialog "Don't ask again" or something like that

the "Upload" button in the workbench is not going to be clicked as many times as the "Merge" button in agent merging (simply because merging usually merges few records at a time, where as workbench upload thousands at a time) so any extra useless click are that much worse

**Comment by grantfitzsimmons** [comment]
I'd like there to be a checkbox as well.

**Comment by realVinayak** [comment]
@maxxxxxdlp @grantfitzsimmons yes, it should be for everyone. For stats, it was just read queries - but agent merging does read and write. So, locks will be issued at db level. The exact number of rows it would lock will depend on the progress of the merge, since we don't lock everything in the beginning of transaction but gradually update rows. But, towards the end of transaction, any row that should be affected would have been locked - just for read

Is it worse than workbench/trees? I don't know - but current user testing implies that. For me, it took 33 minutes to merge a set of 4 agents with a LOT of references - and I was running that locally.
