### ISSUE TITLE
`xml-editor`: Unknown table prevents saving form definition

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#3820]
A spin-off of #3708 

---

<img width="414" alt="image" src="https://github.com/specify/specify7/assets/37256050/980c5071-e730-485c-a92a-e042a477400e">

From `herb_rbge`'s forms. This is preventing me from saving.

```xml
        <viewdef
            type="form"
            name="Collection Object Search"
            class="java.util.Hashtable"
            gettable="edu.ku.brc.af.ui.forms.DataGetterForHashMap"
            settable="edu.ku.brc.af.ui.forms.DataSetterForHashMap">
            
            <desc><![CDATA[The Collection Object form.]]></desc>
            <enableRules/>
            
            <columnDef>120px,2px,p,2px,120px,2px,p,2px,60px,2px,p,p:g</columnDef>
            <rowDef auto="true" cell="p" sep="2dlu"/>
            
            <rows>
                <row>
                    <cell type="label" labelfor="1"/>
                    <cell type="field" id="1" name="catalogNumber" uitype="text"/>
                    <cell type="label" labelfor="2"/>
                    <cell type="field" id="2" name="collection_collectionName" uitype="text"/>
                </row>
                <row>
                    <cell type="label" labelfor="3"/>
                    <cell type="field" id="3" name="accession_number"  uitype="formattedtext" uifieldformatter="AccessionNumber"/>
                    <cell type="label" labelfor="4"/>
                    <cell type="field" id="4" name="cataloger" uitype="text"/>
                    <cell type="label" labelfor="5"/>
                    <cell type="field" id="5" uitype="plugin" name="this" initialize="name=PartialDateUI;df=catalogedDate;tp=catalogedDatePrecision" uifieldformatter="Date"/>
                </row>
            </rows>
        </viewdef>
```

**Video:**

https://github.com/specify/specify7/assets/37256050/525db78f-21db-409c-bb9e-3771e4228229

https://herbrbge33123-issue-3657.test.specifysystems.org/specify/resources/view-set/1/

**Comment by maxxxxxdlp** [comment]
What is the difference between this and #3708?


Warnings preventing saving is not valid behavior - it's a bug that must be fixed
Looking at the app resource code, all invalid table names for this specific attribute (in view def and view set def) would result in warnings rather than errors
`Hashtable` is some sort of special java table. I don't know if there are other special cases so decided to resolve to triggering warnings rather than errors in this case - we can change it to have a safelist of known sp6 tables

though calling them sp6 tables is wrong as this attribute refers to sp6 class rather than a database table

whoever wants to look into this deeper, you can use the tool I wrote (https://github.com/specify/specify_tools/tree/main/xml-inspector) for finding a list of all the possible values for the `class=""` attribute that have ever been used and accepted by sp6

**Comment by grantfitzsimmons** [comment]
@maxxxxxdlp 

The issue with https://github.com/specify/specify7/issues/3708 is that it says "unknown table", but we are clearly familiar with it 😂 As you said, the fix for that issue is to have a safelist of known Specify 6 classes/tables.

**Comment by maxxxxxdlp** [comment]
it's an unknown table as far as sp7 is concerned, and will be once sp6 is put to sleep 😊
