### ISSUE TITLE
Stats Page Query Errors Do Not Use Properly Use Toast

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#3833]
**Describe the bug**
If you run into a Query Builder Error while in Stats Page the toast gets created alongside the dialogue.

**To Reproduce**
1. Go to Stats Page
2. Add a query that's guaranteed to throw an error on run. (Like UnMapped Queries)
3. Open the query

I'm logged in as petrifiedroadkill in NHMD -> NHMD Amber 

**Expected behavior**
The error should only appear as a Toast and not have the Dialogue open.

**Beautiful Pictures**

https://github.com/specify/specify7/assets/53784701/9470c6d6-0213-4499-b31f-8cedb793c6f7

**Desktop:**
 - OS: Mac OS
 - Browser: Chrome
 - Specify 7 Version: 7.9

**Comment by carlosmbe** [comment]
You could also consider the fact the Progress Bar keeps on spinning despite an error occurring another part of the bug. As it may make the user think that it's possible to still get results.

**Comment by maxxxxxdlp** [comment]
The issue is that you have two errors occurring.
Front-end runs the query once in "count only" mode to get the results count
and it runs it again with "limit 40" to fetch the first 40 results

not specific to the stats page

> You could also consider the fact the Progress Bar keeps on spinning despite an error occurring in another part of the bug. As it may make the user think that it's possible to still get results.

unfortunately, this issue happens in many places in the UI whenever an error related to a network request happens (as opposed to an error due to rendering content)

**Comment by maxxxxxdlp** [comment]
See https://github.com/specify/specify7/pull/3843#pullrequestreview-1548973310
