### ISSUE TITLE
Adding a new prep in disposal doesn't always enable save btn

### ISSUE THREAD

**Issue by CarolineDenis** [specify/specify7#3983]
- create new disposal 
- add one new prep
- save 
- add a second prep
- save btn is disable 

* present in 7.8.7

**Comment by CarolineDenis** [comment]
Isn't disposal preparations in regards of disposal the same as what a CO would be for an accession? 
We can add an accessionId in a CO form since there is an accessioned field in the CO table than we can display all the COs present in an accession on the accession form as read only. 
In this situation, disposalPreparation has a disposalId in its table but disposal do not have a field for an array of disposalPreparation. Why then the disposalPreparations have a way of adding such objects? 

@maxxxxxdlp @melton-jason

**Comment by CarolineDenis** [comment]
When adding a new disposal preparation we are changing the resource disposalPreparation on its disposalId field but the save button for this page is on the Disposal form and is listening for changes of values for disposal table right?

**Comment by maxxxxxdlp** [comment]
@CarolineDenis There is one important concept that I didn't have time to mention during our meeting on Wednesday, and that is the concept of dependent and independent relationships.
It probably is mentioned in one of the videos in the google drive folder, but here is the gist:

If it doesn't make sense for a record of table `A` to exist without having a connection to a "parent" record from table `B`, then the relationship from `B` to `A` is dependent (see the "Dependent" column [in the schema viewer](https://sp7demofish.specifycloud.org/specify/data-model/#disposal)).
Practical example: relationship from "Disposal" to "Disposal Preparation" is dependent because it doesn't make sense for "Disposal Preparation" to exist without being connected to some "Disposal".

An alternative way to look at this is though imagined hierarchy of tables. Accession table can be considered a parent table of "Accession Citation", "Accession Authorizaton", and "Accession Agent", thus relationship from Accession to these tables is dependent.

Now, here is how the designation of relationship as dependent/independent makes a difference in practice:
If you request an Accession resource, all of the resources at it's dependent relationships are also provided by the back-end in that response - you can't fetch Accession without also fetching it's Accession Citations. This also means that if you don't have read access to Accession Citation table, you can't read Accession record either (something Grant is complaining about - https://github.com/specify/specify7/issues/2714)

The other practical difference is that dependent tables like "Accession Citation" are in general not opened in a form - they are usually only displayed in a subview inside of their "parent" table. Since these tables are dependent on their parent, they don't have their own "Save" button, and instead the changes to them count as changes to the parent resource, and are saved when the parent resource's save button is clicked (having to deal with dependent/independent resources is one of the reasons [resourceApi.js](https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/components/DataModel/resourceApi.js) is so much more complicated than the [resource.ts](https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/components/DataModel/resource.ts#L33-L109))

That is why, dependent subviews are supported - the changes to them while saved in a separate table, count as modifications to the parent resource.

And that is why when you see the pull request we have open (https://github.com/specify/specify7/pull/3125), it says "independent" in the title.

In contrast, independent relationships are relationships between tables that can exist without each other and are standalone on each own. Collection Object and Accession are standalone tables, and while they can have a relationship between them, they can be used without the relationship too. Same for Determination and Taxon (but not Collection Object and Determination)

Feel free to ask Grant or Jason for more examples/more detailed explanations.

**Comment by CarolineDenis** [comment]
mhhh okok thank you for the explanations. So what I thought is not the issue here (adding a new prep not triggering the save button)

**Comment by maxxxxxdlp** [comment]
the issue title says "doesn't always enable save btn". do you mean it triggers save button only some of the time? in that case it's a bug

as far as what behavior is expected, @grantfitzsimmons can you comment on this?

**Comment by CarolineDenis** [comment]
@maxxxxxdlp, Yes the save button becomes active when the first prep is added. You save it. Then you add a new one, the save button is not enabled. (Some times it take 2 tries)

**Comment by maxxxxxdlp** [comment]
Yeah, seems like a bug. Could be related to https://github.com/specify/specify7/issues/1702

**Comment by CarolineDenis** [comment]
Findings: 
https://github.com/specify/specify7/blob/5ddf62fc57a579ac3db5878b6c187d4c7617b884/specifyweb/frontend/js_src/lib/components/Forms/Save.tsx#L75
`saveRequired` is not recalculated when adding a second prep.

**Comment by maxxxxxdlp** [comment]
Okay, if this is a resource api bug, unless it's urgent, might be easier to just wait till when we rewrite the resource API (and that might also fix https://github.com/specify/specify7/issues/1702)

**Comment by emenslin** [comment]
Fixed
