### ISSUE TITLE
Loan/Borrow agents are cloned but uniqueness rules block save 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#3998]
**Describe the bug**
Loan and borrow agent and roles are carried forward, but you can't save the new record. 

**To Reproduce**
1. Go to new loan or borrow
2. Add loan/borrow agents
3. Save
4. Clone record
5. See error

**Expected behavior**

Should be able to save form

**Screenshots**

https://github.com/specify/specify7/assets/135047322/568795b4-0771-4c7c-bf9e-5d3bd640cd5f

https://github.com/specify/specify7/assets/135047322/bcc081a1-a331-42d4-93f3-d66df2471ed2

**Desktop:**
 - macOS, Chrome, `v7.8.13`

**Database Name:** 

herb_rbge_9_3_23

**Comment by realVinayak** [comment]
that's not the expected behaviour. Also broken in production

**Comment by melton-jason** [comment]
This Issue should have the same underlying cause as #4109.  
In short, the problem occurs because when a Loan/Borrow is cloned, the references to the previous Loan/Borrow are carried over to the respective LoanAgents/BorrowAgents as well. 
See https://github.com/specify/specify7/issues/4109#issuecomment-1761815550
