### ISSUE TITLE
`502 Bad Gateway` due to large queries generated by delete blockers requests

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4007]
<img width="1920" alt="image" src="https://github.com/specify/specify7/assets/37256050/a5bdbb42-5239-4a71-900d-865670b984d2">

@realVinayak has more context about the situation. Can expand more tomorrow.

**Comment by realVinayak** [comment]
Date range query is the problem here. the optimization is pretty simple:
```
SELECT 
  determination.`DeterminationID` AS `determination_DeterminationID`, 
  date_format(
    determination.`DeterminedDate`, 
    CASE determination.`DeterminedDatePrecision` WHEN 2 THEN '%m/%Y' WHEN 3 THEN '%Y' ELSE '%m/%d/%Y' END
  ) AS date_format_1 
FROM 
  determination 
WHERE 
  determination.`CollectionMemberID` = 4 
  AND determination.`DeterminedDate` IS NOT NULL 
  AND determination.`DeterminationID` IN (
    '65536', 
    '512', ..... )
```
to this instead:
```
SELECT 
  determination.`DeterminationID` AS `determination_DeterminationID`, 
  date_format(
    determination.`DeterminedDate`, 
    CASE determination.`DeterminedDatePrecision` WHEN 2 THEN '%m/%Y' WHEN 3 THEN '%Y' ELSE '%m/%d/%Y' END
  ) AS date_format_1 
FROM 
  determination 
WHERE 
  determination.`CollectionMemberID` = 4 
  AND determination.`DeterminedDate` IS NOT NULL 
  AND determination.modifiedbyagentid = 1514 # Or anything else)
```
For 40k valid determinatios (in the `in` clause, filtered by deletion blocker), the first query doesn't finish in 5 minutes. The second finishes in less than 2 seconds. 

Based on state of query execution, looks like having a big list in `in` clause trips mysql optimizer as the state is `Statistics` and `Preparing` for a considerable time (even under just `EXPLAIN` - https://dev.mysql.com/doc/refman/8.0/en/general-thread-states.html)
