### ISSUE TITLE
WorkBench Data Sets dialog shows "Timestamp Modified" instead of "Uploaded"

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4011]
`v7.7.5`, `v7.8.0`:
<img width="688" alt="image" src="https://github.com/specify/specify7/assets/37256050/256944f0-1aa3-4b9d-898c-5ba1fd679411">

`v7.9-dev`,`v7.8.13`, `v7.8.4`,:
<img width="797" alt="image" src="https://github.com/specify/specify7/assets/37256050/6b3eeabf-51e8-4fd5-8e32-8d36ae74566a">

Where did it all go wrong!?

**Comment by grantfitzsimmons** [comment]
<img width="797" alt="image" src="https://github.com/specify/specify7/assets/37256050/7b9285d9-cb3c-4cac-a9aa-3ba2b89ff956">
![image](https://github.com/specify/specify7/assets/37256050/f427ac7b-55c9-4620-ac05-6edbffe6a31d)

**Comment by maxxxxxdlp** [comment]
> Where did it all go wrong!?

This was a change made by me (and by Caroline under my directive). See https://github.com/specify/specify7/issues/2420

We went though all the places in the UI and where applicable changed it from using UI localization to using schema localization.

Pros:
- The label is editable by the user
- The label would be consistent when appearing in the UI dialogs/error messages with what label you see in the query builder, forms, workbench and schema config
- We have to localize schema anyway - duplicating the label in the UI is only going to add more work for the translators

Cons:
- We have less control over what label is displayed - at most we can change the default value (and only if their database hasn't customized it already) - this can be bad if default value doesn't work nicely in our UI or if default value has a spelling error (yes, that happened)

Given the above points, I would encourage specify to use schema label for a given field instead of UI localization whenever labeling data coming from that field.

However, this particular example is a bit of a bad case because the Workbench table is used by sp6 only, and the SpDataset table does not have schema localization, thus I had to use the labels from the Workbench table (they are still editable by the user in the schema localization, or if they customized it in sp6).

Given the above, please use schema localization whenever possible, but don't use it when it doesn't work for you.

**Comment by grantfitzsimmons** [comment]
This was reported to us by Willem at SAIAB today
