### ISSUE TITLE
Loading a database from the `seed-database` folder is not working

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4116]
Originally reported to @maxxxxxdlp by myself in April 2022, but I encountered today. 

@specify/dev-testing Interested to see if any of the devs have encountered the same thing.

A seed database is present in the `seed-database` directory. 

<img width="728" alt="image" src="https://github.com/specify/specify7/assets/37256050/4a413212-e25e-4701-9c15-219e11d2e1aa">

After trying to log in, I first see `'specify.specifyuser' doesn't exist`

![image](https://github.com/specify/specify7/assets/37256050/1140f125-b7f4-445b-a750-da3dadd253fd)

@maxxxxxdlp:
>It was supposed to get populated from the file

Of course, the database exists, and some migrations run, but all of the other tables are missing:

![image](https://github.com/specify/specify7/assets/37256050/51f030dd-30da-4bdd-afe6-4083e8d03b86)

When deploying in Docker since this report, I've had to do the following:
```sql
drop database specify;
create database specify;
use specify;
source /docker-entrypoint-initdb.d/specify.sql;
```

where `specify.sql` is located in the `seed-database` directory.

**Comment by grantfitzsimmons** [comment]
@realVinayak 

>likely because you already ran it once. 
>
> Remove the database volume (should be named something like specify7-database), and it would work.

And he is right. Would it be better for it to run every time for development? Maybe. I'm not going to overthink it, but this issue can at least make this discoverable for others who are similarly confused.

**Comment by maxxxxxdlp** [comment]
What you are saying seems correct (https://stackoverflow.com/a/39765233/8584605 and https://stackoverflow.com/a/52715521/8584605)

However, I can remember in the past having multiple .sql files in my seed-database folder (downloaded locally in case I need them for testing)) and running into trouble because  database would get replaced unexpectedly on restart - solution was to rename all but one file to .sql_.
Maybe I am misremembering and this was caused by me clering all docker volumes
