### ISSUE TITLE
`xml-editor`: Cannot remove prep type items or add new ones

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4151]
https://github.com/specify/specify7/assets/37256050/86ae8a6e-c3f3-4e4f-9e73-12752a40f657

`nbm-mnb` database copy,  `/specify/view/picklist/51/`

**Comment by CarolineDenis** [comment]
NOTES: 
The issue is not really that we cannot add or delete a prep type, it's the fact that the + and - buttons are enabled and shouldn't. 
See comment: https://github.com/specify/specify7/pull/3441#issuecomment-1557984644
This feature will be read only until https://github.com/specify/specify7/pull/3125 is implemented

**Comment by CarolineDenis** [comment]
Will add back the read only
