### ISSUE TITLE
Add option for preserving base table row count with tick box in queries

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4162]
Very much related to https://github.com/specify/specify7/issues/2005

> **Intro:**
> We referred to this a few meetings ago. It regards querying Collection Object Properties (COP) data.
> The CSIRO Australian National Wildlife Collection (ANWC) have 180+ plus ‘Trait’ types that are applied across a variety of Collection Objects.
> Traits are recorded using the Collection Object Properties table, in a one-to-many relationship from the Collection Object, using the text16 field with a picklist consisting of the 180+ trait types.
> As well as the Trait type, there are associated Value (Text or Numeric) and Unit fields for each trait recorded.
> While this allows great flexibility and ability to apply the variety of traits needed, there are limitations when it comes to querying the data, particularly around null values.
> **Use case:**
> The Egg collection is a subset of the full collection. Most of the time, ‘Clutch Size’ is entered as a trait, but sometimes it is not.
> A user is compiling data for a paper and is working with a particular set of Egg collection objects. They want to include the clutch size for any object that has it recorded (while maintaining their full object list).
> If they search by the clutch size trait specifically, they will not get their full Egg object list, only a list of objects where clutch size has been entered.
> They can retain their full list if they use the aggregated view or 'any' trait operator, however they will get all the trait data, not just clutch size. It is a fair bit of work filtering that noise out via excel, especially if you're working with thousands of records.
> However, we can achieve what they want via the backend with SQL using an outer join. 
> ```sql
> SELECT
>     c.CatalogNumber,
>     c2.text16 as Trait,
>     c2.text33 as Value_Text 
> FROM collectionobject c
> LEFT OUTER JOIN collectionobjectproperty c2 ON c.CollectionObjectID = c2.CollectionObjectID
>     AND c2.Text16 = 'Clutch Size'
> WHERE c.CatalogNumber LIKE "E%"
> ```
> **Request:**
> Is it possible to have a tick box option in queries to 'Preserve the base table row count'? When ticked it would change the query to an outer join rather than the inner join we suspect Specify is using? (Or some alternative function that achieves what we're trying to do demonstrated by the SQL)
> 
> Note: 
> We have other ideas relating to querying tables with one-to-many relationships, a few of which may have github requests already. We thought we could run over them briefly in our next chat, before submitting further tickets. We think this one would be useful regardless and doesn't seem to have been brought up by others before (apologies if it has!).
> 
> Here's a summary picture:
> ![image](https://github.com/specify/specify7/assets/37256050/ffd0dabe-c2c6-4ecc-b8cd-de4cbe425ecb)

**Requested by:** Zoe at CSIRO ([Asana](https://app.asana.com/0/1201972579963460/1205791087547130/f))

**Comment by realVinayak** [comment]
I think this is a false issue, backend does left join (what they want)

**Comment by danb213** [comment]
Hi, could you please re-open this because the system does not currently do what we would like it to. I just tested in 7.9.4 and if I start with a list of specimens I get 6 rows, but as soon as I specify a trait (from the CollectionObjectProperty table) it goes down to 3 because 3 of the specimens have no data for that trait and so no row in that table.
![image](https://github.com/specify/specify7/assets/110948439/f1682d6d-ec27-4576-8bf6-7da9b15258ab)
![image](https://github.com/specify/specify7/assets/110948439/cb56c28a-d064-4b3d-bcc6-e2fe278d6f8c)
We've requested this because users have complained of losing information about specimens just because a trait they are after has not yet been collected, they still want to see those specimens in the query results along with any other data they've searched for.

**Comment by realVinayak** [comment]
@danb213 Hmm the count goes down because of the filter. Underlying join is still outer, and the orginal rows are still present. Instead of saying Traits -> Traits -> Equal -> Egg measurements, do Traits -> Traits -> (Equal -> Egg measurements) or (empty).

**Comment by danb213** [comment]
Hi @realVinayak, your suggestion doesn't work for the traits (COP) table because when the "egg measurement" trait hasn't been added, there is no row in that table. Adding the "OR EMPTY" clause still doesn't bring back the missing 3 rows because the value is not empty, it's completely not there!

The request is for the query to preserve the row count based on any conditions on the base table data only, and if the user adds anything else it should bring back a NULL if that data doesn't exist. Another example would be to search for all specimens catalogued in the last month (using the collectionobject cataloguedDate field) and to bring back the taxon name from the current determination. If there is no determination on one of those specimens you would lose that from the query results:

![image](https://github.com/user-attachments/assets/3413fe53-9198-438c-82b2-b73f5f45cce2)
