### ISSUE TITLE
`xml-editor`: See a summary of warnings 

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4168]
When there are a lot of warnings in an XML file, I need to now scroll and find them one-by-one (after #4119 was merged). There is no place where they are all displayed anymore.

> I would very much like to see a summary of these warnings.

Maybe this means they show at the bottom again? Maybe a button to see them all in a dialog? It would be nice to see.

**Comment by maxxxxxdlp** [comment]
Maybe if you have warnings, the save button should bring up the dialog with warnings and ask if you want to proceed anyway?
(kind of like workbench mapper does when you have missing required mappings)

**Comment by maxxxxxdlp** [comment]
Btw, I just found out that codemirror (the editor we use ⚡) includes this feature natively:

https://github.com/specify/specify7/assets/40512816/6f1072d6-97ed-4d06-a056-27ecb4b016f0

scroll to the bottom of https://codemirror.net/examples/lint/ to see an example

so I would really be against us implementing and maintaining this feature.

we should instead:
- document what codemirror features are available
- (optionally) show either a hint in the UI on how to open the warnings panel OR have a button that makes codemirror's warnings panel open (see https://codemirror.net/docs/ref/#lint.lintGutter:~:text=openLintPanel%3A%20Command,the%20lint%20panel.)

**Comment by CarolineDenis** [comment]
Tested the command shift + command + m and it works great! 
@maxxxxxdlp thank you for the tip

**Comment by combs-a** [comment]
Reopening for an addon to this request: currently, the behavior of the summary is that it disappears after you start editing, and you can't bring it back up unless a) you have errors and click save, or b) know the shortcut.

In my opinion, this is a bit flawed, since if you edit it you can no longer see the list of warnings unless you know the shortcut--which isn't told to the user in the editor itself. This will lead to the QoL issue of having to scroll to find the warnings again, or having to find it in documentation elsewhere.

A better behavior would be to keep it up until it is dismissed, since it's a bit clearer to users, and doesn't mean you have to click save or know the hotkey for it. Alternatively, having a tooltip in the XML editor itself that lets you know that you can bring it back up with Ctrl+Shift+M would be fine.

Example of the behavior:

https://github.com/specify/specify7/assets/71564869/3c2b6b77-48b2-466c-a38f-4d580918dc19
