### ISSUE TITLE
`xml-editor`: Creating a new form definition based on a default form is unintuitive

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4177]
<img width="405" alt="image" src="https://github.com/specify/specify7/assets/37256050/de483e8c-b52b-4035-b44f-940334b6bd71">

I am in a fish collection, I want to create a new form based on the fish collection form definition.
I am greeted with a giant list of all discipline's forms, and it is really unclear which I should choose.

**Expected Behavior**
I should see my discipline's forms show up first (Fish)

Here are my options at this time:
```
Fish
Fish > Fishbase
Fish > Manager > Fish
Fish > Guest > Fish
```
This is very strange, as a user, since I do not have a concept of what these things mean.

Maybe we could represent this under a header for each discipline, shown like this:

> **Ichthyology**
> * Fish Default
> * Manager User
> * Guest User
> * Fishbase
>
> **Herpetology**
> * Herpetology Default
> * Manager User
> * Guest User

**Comment by grantfitzsimmons** [comment]
Another note– the names need to be resolved to the proper discipline names.

Fish --> Ichthyology
Vertpaleo --> Vertebrate Paleontology
Invertpaleo --> Invertebrate Paleontology
Bird --> Ornithology
Mammal --> Mammalogy
Vascplant --> Vascular Plants
Invertebrate --> Invertebrates

**Comment by maxxxxxdlp** [comment]
Another idea:
it is possible that most of these form definitions are duplicates of each other (i.e same form definition copied for each discipline). in that case, perhaps present an alternative UI:

you have a previous of the form, and below the preview list of places in which it is defined.
below that another preview, and list of places in which it is defined

Pros:
- List would be way shorter if most views are the same
- User has better idea of what form they need to pick because they will see a side by side preview of different view definitions

Cons:
- Displaying a preview of each form rather than just name may make this dialog **much** longer in the worst case
- It may be hard to notice the differences between forms (or there might not even be any noticeable differences - just a whitespace or comment difference between view definitions)
