### ISSUE TITLE
Creating a query the full name field from a tree uses (formatted) instead of full name

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4181]
https://github.com/specify/specify7/assets/37256050/a46e31a9-060c-4e9a-a82f-7a1c9d0aea64

[Aisle-end Report.json.zip](https://github.com/specify/specify7/files/13228528/Aisle-end.Report.json.zip)

https://fwri2023-v790.test.specifysystems.org/specify/query/312/
`spadmin`, Ichthyology

This is happening in both `v7.9.0` and `v7.9.1`.
This is confirmed in both the Storage tree and the Taxon tree.

This prevents anyone from creating a report (due to https://github.com/specify/specify7/issues/2899) **and** it causes users to lose filtered query results since full name queries revert to (formatted). 

See this PR for more information about the underlying issue: https://github.com/specify/specify7/pull/3026

From @melton-jason  in [this comment](https://github.com/specify/specify7/pull/3026#issuecomment-1442187194):
> Explicitly querying on the Full Name field sends the expected `(formatted)` stringid and fieldname to the backend. 
> At the moment, the backend actually has no support for the `FullName` field to be sent with tree query fields. 
> To get the `FullName` field, the backend _expects_ it to be as if it were formatted. 

From @maxxxxxdlp in [this comment](https://github.com/specify/specify7/pull/3026#issuecomment-1442191688):
> That is why in the UI I am pressing "Full Name" instead of formatted.
> If you find that it's actually using formatted, then change the UI to replace "Full Name" with "(formatted)" in the list of fields, and leave the other fix you did in place

https://github.com/specify/specify7/pull/3026

**Reported By:** Paul at FWRI

Encountered when trying to work around https://github.com/specify/specify7/issues/2899

> Seems like I’m getting this error even without formatted fields in the query. I’m trying to create a report that lists all the contents in a given aisle in the collection based on my storage tree.
>
> ![image](https://github.com/specify/specify7/assets/37256050/5a60cd35-f278-4039-b670-285925a1d99d)

**Comment by CarolineDenis** [comment]
@maxxxxxdlp or @melton-jason , could you briefly explain what there is to do in order to fix this issue? Thank you! :)

**Comment by maxxxxxdlp** [comment]
The issue likely occurs in https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/components/QueryBuilder/fieldSpec.ts

That file has two main functions:
- Converting the query builder field from the format stored in the database (that format is quite inconvinient to work with because it's a legacy shared with sp6) to the format used by react (front-end only format that is not saved in the database, thus we can change at any time)
- Converting back from react to database format

Somewhere in the process an error must be occurring.

For example, when converting from react to database, see this special case for tree full name:
https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/components/QueryBuilder/fieldSpec.ts#L110-L111

And here is the code for tree full name when converting from database to react:
https://github.com/specify/specify7/blob/48c1f00d576a03e25927847723c17be340944f80/specifyweb/frontend/js_src/lib/components/QueryBuilder/fieldSpec.ts#L308-L312


Also note that back-end needs to do a similar two-way conversion process. Here is the mostly equivalent back-end file where this is happening - https://github.com/specify/specify7/blob/production/specifyweb/stored_queries/queryfieldspec.py
