### ISSUE TITLE
Set Min Window Size for Agent Merging View

### ISSUE THREAD

**Issue by carlosmbe** [specify/specify7#4189]
**Describe the bug**
This is a minor bug but you can resize the agent merging windows and sub views to extremely small proportions. It's a big issue but I can easily imagine an instance where a User accidentally resizes the window and doesn't know how they did it. Thus, they start sending us emails asking for help.

**To Reproduce**
1. Select a couple of agents
2. Click on Merge Records
3. Re size on both x and y axis to make it as small as possible
5. Repeat with subview.

**Expected behavior**
Min Size applied so that the view is still viewable

**Beautiful Picture**

https://github.com/specify/specify7/assets/53784701/22548cb7-7e50-4eab-8f88-f871a04919c0

<img width="881" alt="Screenshot 2023-11-02 at 2 16 58 PM" src="https://github.com/specify/specify7/assets/53784701/112b1f0a-459e-46e9-8b69-aa5256493d12">

**Desktop:**
 - OS: Mac Os
 - Browser: Chrome
 - Specify 7 Version: 7.9.1

**Comment by maxxxxxdlp** [comment]
I don't think this is specific to this dialog - you can do that for any dialog.

Contraining the min-height is probably not a good idea because:
That would require hardcoding some assumptions about what the is the size of the content the dialog is displaying, and what is it's scale (size can vary because dialog content is dynamic, and scale can vary a lot because user can change font size, UI scale or browser window zoom level)
And any time you hardcode an assumption, you cause issues because there would come up a case not covered by your assumption
Plus, having to specify min heights for different dialogs would add more work for programmers and more maintenance task

What we could do, is set some min height to something small like 10rem (or something smaller than the height of the smallest dialog - the loading dialog), but I don't see how that is much better than not having a height constraint.

Feel free to reopen this issue if you disagree
