### ISSUE TITLE
WB cells containing nothing but white space cause upload errors

### ISSUE THREAD

**Issue by timo11** [specify/specify7#420]
If '   ' is entered into a dataset cell, uploading the dataset may result in failure with a error in the message window something like this: Dataset could not be uploaded: edu.ku.brc.specify.tasks.subpane.wb.wbuploader.UploaderException: org.hibernate.PropertyValueException: not-null property references a null or transient value: edu.ku.brc.specify.datamodel.Taxon.name.

The easiest way to replicate the issue is by entering '  ' in a cell mapped to species, when the genus is non-blank.

**Comment by timo11** [comment]
This a problem with the sp6 uploader. bugzilla #10306. Fixed in sp6 revision 12141. A new build of Sp6 is required to test this bug in 7.

**Comment by garrettgirard** [comment]
Tested in LSU Mammals, this issue is fixed. Now when you try to upload data with ' ' (black spaces), the uploader is successful and doesn't give any errors. The determination for that CO is then determined to the lowest rank that has data. For example, if Genus is filled, but Species is empty (blank spaces), there will be no error in the upload and the resulting record will be determined to Genus.
