### ISSUE TITLE
Picklist Size Limit form validation error 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4206]
**Describe the bug**
The business rule for picklist size limit was removed a while ago (PR #2202), but the picklist form definition still enforces a size limit within the range of 2-500 to save. This leads to a weird UX as the picklist can have theoretically unlimited values, but the size limit field requires a value between 2 and 500 regardless of the actual count of items. Further, the use of a 0 or -1 to dismiss the size limit constraints is no longer an option. 

**To Reproduce**
1. Go to `herb_rbge_9_3_23` on test panel >> url ending: specify/view/picklist/84
2. Click on the `+` to add a value (should be greater than 500)
3. Adjust size limit to 0/-1 and compare with a value between 2-500

**Screenshots**
<img width="584" alt="Screenshot 2023-11-13 at 10 54 33 AM" src="https://github.com/specify/specify7/assets/135047322/6bbd5309-e784-4887-bf95-8ce066099f10">
<img width="584" alt="Screenshot 2023-11-13 at 10 54 48 AM" src="https://github.com/specify/specify7/assets/135047322/5f5ceb8e-f19e-420b-b94e-934c69f3ce26">

**Desktop:**
 - OS: macOS
 - Browser: Chrome
 - Specify 7 Version: `v7.9.1`

**Database Name:** `herb_rbge`

**Reported By**
Robyn at RBGE

**Additional context**

> [Max's comment](https://github.com/specify/specify7/issues/1515#issuecomment-1123020373) on a related issue: 
> 
> It is set that way in the form definition:
> 
> `<cell id="sizeLimit" initialize="max=500;min=2" isrequired="true" name="sizeLimit" type="field" uitype="spinner" />`
> 
> Other than the form definition, there is no reason why it can't be -1. Specify 7 would handle both 0 and -1 as "no limit"

**Comment by maxxxxxdlp** [comment]
thanks for providing lot's of details. just a FYI for the future: if an issue requires changing to default forms, add it to the "[Form Changes](https://github.com/orgs/specify/projects/3)" project. (assuming the workflow hasn't change since I left - @grantfitzsimmons can you confirm?)

The benefit of this is that when it comes to make a new sp6 release, we can easily see in a single place all the of pending form changes we need to make and can make them all at once.

---

aside: looks like most recent issues don't use projects anymore. @grantfitzsimmons was that an intentional change or just a slip up from lack of time/insufficient wiki documentation? there is significant value in assigning issues into back-end/front-end projects (for setting size&priority) as well as project for each component of specify for easily filtering and tracking (I use that all the time when searching for duplicates if I don't remember exact issue title)

**Comment by emenslin** [comment]
Can recreate as of edge (7.9.6)
