### ISSUE TITLE
`xml-editor`: Attachment gallery button should not display unless there are attachments

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4211]
![image](https://github.com/specify/specify7/assets/37256050/ae8b9541-bcfb-4a8a-988d-cf1993986301)

Added in https://github.com/specify/specify7/pull/3363

I believe it appears out of place and lacks usefulness without attachments. It does not align with the form meta menu button and lacks functionality without attachments already uploaded.

**Comment by CarolineDenis** [comment]
Since attachments can take some time to be loaded it was decided to disable the button rather than remove it and then add it if there is attachments. 
Plus, when we have a big number of records, by example 1200 we will only fetch the first X attachments and it might return an empty array, a dialog will than open when clicking on the gallery icon to fetch the next X. This would be possible neither if we remove the icon. 
I suggest that we keep the button as it is

**Comment by maxxxxxdlp** [comment]
> Plus, when we have a big number of records, by example 1200 we will only fetch the first X attachments and it might return an empty array, a dialog will than open when clicking on the gallery icon to fetch the next X. This would be possible neither if we remove the icon.

that is the case in record sets. but the screen shot that Grant sent is not from a record set, it's from individual record

**Comment by CarolineDenis** [comment]
Well, I believe the issue at hand is that we currently have the attachments gallery icon present in the record set. However, we find ourselves in a new data entry form within a fictive record set. In order to address this, it would be advisable to remove the icon specifically for the fictive record set.
