### ISSUE TITLE
Infinite loop with uniqueness checking rule

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7#4261]
Seems like a pretty critical issue due to the infinite loop sending a ton of network requests.

Replication (on production branch in ku fish):

https://github.com/specify/specify7/assets/40512816/200543de-9e72-4236-af26-5e563f7d2600

Seems like just opening the Accession form is enough, but showed other steps just in case it makes a difference

**Comment by melton-jason** [comment]
There seems to be something with your attached video, or at the very least I am unable to view it. 

> Seems like just opening the Accession form is enough

I can not seem to recreate this issue by solely opening the Accession form, both on a new and existing Accession form.
(It does seem to make a call to fetch an image every render, but the image itself is cached and I do not think it is related to business rules)

https://github.com/specify/specify7/assets/64045831/1109b6c7-9fb4-4897-9a7f-b39e9b93a32f

Can you please provide more context or try reuploading the video?

**Comment by maxpatiiuk** [comment]
hmm, the video plays normal for me in chrome (on mac). I encoded it as h265 (very efficient format, but it's not the first time I am using it on github issues so don't know why the issue happened now)

here is a h264 encoded video instead:

https://github.com/specify/specify7/assets/40512816/8d5cd7e9-1b10-4b88-8b71-e9b883094fa5

Steps:
1. Run query on accession table
2. Open any accession (`2004-IC-073` in the video)
3. Close the form after 5 sec - then I go to open the query list (not sure this step matters)
4. Lots of console output and network activity

I can send the form or the whole database if needed

**Comment by melton-jason** [comment]
Thank you for providing more information! 
Hmm, weird. It does seem to be an issue with encoding then as the h264 encoded video displays just fine...

I am using:
Coogle Chrome - Version 120.0.6099.71 (Official Build) (64-bit)
Ubuntu 22.04.3 LTS

**Comment by melton-jason** [comment]
I was not able to recreate an infinite loop of requests (the below video does not recreate the steps exactly as in https://github.com/specify/specify7/issues/4261#issuecomment-1848196994, but the results are the same if the steps are followed).
It takes a moment, but it does seem there are a finite amount of requests which will eventually be resolved. 
While investigating this I _did_ uncover some interesting points without looking at the code. 

Firstly, the below video uses CollectionObject as the base table of the query, but I have encountered similar results with Accession and Taxon as a base table. 

https://github.com/specify/specify7/assets/64045831/808792b0-a4f0-42dd-bd76-36f227f2c010

The problem seems to occur because Specify is initializing a large amount of resources (which appears capped at 80), and then calling `resource.set()` which triggers the business rule checks for the changed field.

This `resource.set()` and subsequently the business rule checks appear to originate from one of three possible places when using the Browse in Forms:
- They originate from the form that that is opened (usually as a result of a formatter setting the value of a field)
- They originate from fetching the resource as a result of `RecordSetAttachment.tsx`
- Some unknown Backbone method calls `set()`

- - - 

![Screenshot from 2023-12-11 14-04-06](https://github.com/specify/specify7/assets/64045831/57d60827-31b8-416b-af36-0c42cc31a927)

In the case of `RecordSetAttachment.tsx`, the previous requests to fetch resources of the Query base table can be seen before the business rule requests are made, and it is likely the former is the cause of the latter. 

Regardless, further investigation will need to be done.

@maxpatiiuk, if you can confirm that businessrules are indeed causing an infinite loop for you, could you share the form or database? Furthermore, does the same behavior happen when viewing an individual form, not in a RecordSet?

**Comment by melton-jason** [comment]
The issue here does seem to be the result of initializing a large amount of resources to fetch all related attachments in a record set. 

I replaced the following lines: 
https://github.com/specify/specify7/blob/0a47efcd66919958dad31e46bebdbc31b2ff436e/specifyweb/frontend/js_src/lib/components/Attachments/RecordSetAttachment.tsx#L36-L72

with a simpler version requiring no fetches from the backend: 
```ts
const [attachments] = useAsyncState(
    React.useCallback(
      async () => ({
        attachments: [],
        related: [],
      }),
      []
    ),
    false
  );
```
The videos provided below can be used as a comparision:

`production`

https://github.com/specify/specify7/assets/64045831/6ec60c76-3738-40ed-85b3-d570c9618800

Without fetching attachments from `RecordSetAttachment.tsx`

https://github.com/specify/specify7/assets/64045831/d3daeda8-b71c-4570-a2fb-56be2d1b5bdc

**Comment by maxpatiiuk** [comment]
thanks for investigating this further.
after checking it more, you are right, it appears that requests are not infinite
it's just that with the m1 performance bug (https://github.com/specify/specify7/issues/2574), the requests took very long time to resolve

@CarolineDenis can you take over this issue since you own the code in question?
could you delay fetching all of the resources until the user actually clicks on the attachments button?

also, you could use an API endpoint like /api/specify_rows/ or query builder API to get all relevant attachments in a single request (although with a bit more code)
