### ISSUE TITLE
RSS Export Feed `notifyUserId` attribute is ignored

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4267]
<img width="1902" alt="image" src="https://github.com/specify/specify7/assets/37256050/2312c602-75cd-4954-8ffb-e879165aafdb">

Despite the RSS ExportFeed definition indicating that we need to notify the user with an ID of `5` (which would be `holze001`, not `spadmin`), the `spadmin` account is notified. See the record in the `notifications_message` table on the right.

**Comment by combs-a** [comment]
Updated documentation of this bug, still occurring.

**Describe the bug**
When updating an RSS feed, it sends the notification to the currently logged in user, regardless of what `notifyUserId` is.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to App Resources -> Open an existing/create a new RSS Export Feed.
2. Make the "Send completion notification to user" field a user that you're not logged in as and save.
3. Update RSS feed.
4. See that the notification is sent to the currently logged in user.
5. Go back to App Resources, empty the "Send completion notification to user" field and save.
6. Log in as user that isn't the "Run as user".
7. Update RSS feed.
8. See that notification is sent to currently logged in user.

**Expected behavior**
It should send the notification to the user in the "Send completion notification to user" field, or in the case there is nothing in that field, the "Run as user" user.

**Screenshots**

https://github.com/specify/specify7/assets/71564869/004beae3-2abc-4f04-b3e2-d814743b6ad0

https://github.com/specify/specify7/assets/71564869/350579f2-578f-4a63-a477-8836b238f299

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`
