### ISSUE TITLE
`xml-editor`: Specify user query combo does not work in ExportFeed

### ISSUE THREAD

**Issue by realVinayak** [specify/specify7#4334]
To replicate:
1. Go to visual editor for export feed
2. Try entering values in the `Run as user` or `Send completion notification to user` and notice that records are not fetched.

![image](https://github.com/specify/specify7/assets/61122018/c04ab0a0-5e29-427b-9e5d-a1ac191ec695)

@maxpatiiuk was it supposed to work or is this an invalid issue?

**Comment by maxpatiiuk** [comment]
It was supposed to work, and was working when I made this UI, but doesn't seem to work anymore - may have been broken during the merge process
edit: don't see any change since May in query combo box code that could have caused this

for reference, this is the component being used - https://github.com/specify/specify7/blob/1d6409c522a5ebd60ebb2fa6a30c00e2ac60f6e4/specifyweb/frontend/js_src/lib/components/ExportFeed/Editor.tsx#L343-L384

**Comment by realVinayak** [comment]
Great, we just narrowed down the source to most of the remaining codebase /s

**Comment by realVinayak** [comment]
@maxpatiiuk are you sure that it used to work? I checked out the [commit](https://github.com/specify/specify7/commit/07bbc83e3a22baca85d880d1f0cadb2fa953a524) that added it, and it wasn't working

**Comment by maxpatiiuk** [comment]
this bug might be database-dependent. see https://github.com/specify/specify7/pull/4345#pullrequestreview-1801295017
