### ISSUE TITLE
`xml-editor`: `KeyError at /context/view.json 'name'` since `name` is not added to `viewset` when creating a new form definition from scratch

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4366]
**Describe the bug**

**To Reproduce**
1. Go to https://kufishdemo-xml-editor.test.specifysystems.org/specify/view/collectionreltype/new/
2. See error
   <img width="1022" alt="image" src="https://github.com/specify/specify7/assets/37256050/f3e04829-6f7e-449f-84ad-292800572739">

```
KeyError at /context/view.json 'name' 
```
[Specify 7 Crash Report - 2024-01-05T19_46_21.415Z.txt](https://github.com/specify/specify7/files/13845952/Specify.7.Crash.Report.-.2024-01-05T19_46_21.415Z.txt)

**Expected behavior**
The form I created using XML-editor should work!

**Screenshots**
See that `name` is a field in the table.
<img width="2036" alt="image" src="https://github.com/specify/specify7/assets/37256050/31e8a02d-90f4-4794-bb6a-1aeccae131af">

Here is the form definition: https://kufishdemo-xml-editor.test.specifysystems.org/specify/resources/view-set/9/CollectionRelType/CollectionRelType

```xml
<viewdef name="CollectionRelType" class="edu.ku.brc.specify.datamodel.CollectionRelType" type="form" gettable="edu.ku.brc.af.ui.forms.DataGetterForObj" settable="edu.ku.brc.af.ui.forms.DataSetterForObj">
	<desc>CollectionRelType Form</desc>
	<columnDef>p,3dlu,f:p:g</columnDef>
	<rowDef auto="true" cell="p" sep="2dlu"/>
	<rows>
		<row>
			<cell type="label" labelfor="1"/>
			<cell type="field" id="1" name="name" uitype="text"/>
		</row>
		<row>
			<cell type="label" labelfor="4"/>
			<cell type="field" id="4" name="leftSideCollection" uitype="querycbx" initialize="name=CollectionRelationship" isrequired="true" colspan="6"/>
		</row>
		<row>
			<cell type="label" labelfor="5"/>
			<cell type="field" id="5" name="rightSideCollection" uitype="querycbx" initialize="name=CollectionRelationship" isrequired="true" colspan="6"/>
		</row>
	</rows>
</viewdef>
```

**Desktop:**
macOS, Arc

**Comment by melton-jason** [comment]
The error is being raised because there is no corresponding view in the viewset with a `name` attribute. Or at the very least, Specify can not find one. 

https://github.com/specify/specify7/blob/a3097d86cd205fa8d7cc3fb5463592b8b4f1efb5/specifyweb/context/viewsets.py#L91

There are no `views` defined in the viewset. 
Does the error still occur when one is defined?

**Comment by grantfitzsimmons** [comment]
The issue is that `xml-editor` needs to create the accompanying `view` in that case, no?

**Comment by melton-jason** [comment]
After doing some investigating, it looks like I was incorrect in my comment.
The issue here is that there is literally no `name` attribute on the `<viewset>` element (nor is there is a viewset element, but the backend uses the first element with a tag that _starts_ with the string 'viewset', so in this case it uses <viewsets>. See below)

For example, take a look at the [fish.views](https://kufishdemo-xml-editor.test.specifysystems.org/specify/resources/view-set/4/) viewset in the KU Fish Voucher Collection. More specifically, towards the top of the file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<viewset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="Fish Views">
	<views>
		<view name="Accession" class="edu.ku.brc.specify.datamodel.Accession" busrules="edu.ku.brc.specify.datamodel.busrules.AccessionBusRules" resourcelabels="false">
			<desc>The Accession form.</desc>
...
```

Now compare this to the corresponding part in the ColRel generated by the visual xml-editor:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<viewsets>
	<views>
		<view name="CollectionRelType" class="edu.ku.brc.specify.datamodel.CollectionRelType" resourcelabels="false" busrules="edu.ku.brc.specify.datamodel.busrules.CollectionRelTypeBusRules">
			<altviews>
...
```
As aforementioned, the backend finds the first element with a tag that starts with `viewset`, and then tries to access a `name` attribute on that element (as in the code snipped provided in https://github.com/specify/specify7/issues/4366#issuecomment-1879305292).

Adding a name attribute to the `<viewsets>` element resolves the error.
The solution here then is to have `xml-editor` write a name attribute to the viewset(s) element. 

This issue will notably occur for _all_ newly created viewsets: it is not restricted to solely the CollectionRelType table.

**Comment by CarolineDenis** [comment]
NOTES: 
- Happens when start a new vied def from scratch and not from selecting an existing from the proposed list. 
- confirm that there is no name attribute on the <viewset> and when adding it the issue is fixed. 
- the name attribute should be populated at creation with the name the user defined in the first dialog

**Comment by maxpatiiuk** [comment]
> handleSaved() in AppResource/Editor.tsx (line 319) is not triggered
@maxpatiiuk , when the view is created from scratch, we need to find a way to add the views name attribute in the createViewDefinition?

handleSaved is called when the `Save` button is clicked, not when the editor is opened

---

https://github.com/specify/specify7/issues/4366#issuecomment-1879499290

One of your snippets includes `viewset`, but another includes `viewsets`
Seems like sp6 expects `viewset` ([source 1](https://github.com/specify/specify6/blob/master/src%2Fedu%2Fku%2Fbrc%2Fspecify%2Fui%2FDBObjDialogFactory.java#L125), [source 2](https://github.com/specify/specify6/blob/master/src%2Fedu%2Fku%2Fbrc%2Fspecify%2Fdatamodel%2FSpUIViewSet.java#L467))

@CarolineDenis  XML Editor needs to be corrected to expect that, here:
https://github.com/specify/specify7/blob/xml-editor/specifyweb%2Ffrontend%2Fjs_src%2Flib%2Fcomponents%2FFormEditor%2Findex.tsx#L28

Other test files are fine - https://github.com/specify/specify7/blob/xml-editor/specifyweb%2Ffrontend%2Fjs_src%2Flib%2Fcomponents%2FFormEditor%2F__tests__%2Findex.test.ts#L19

---

Although, the .xml test files in this directory are even weirder because they contain both: https://github.com/specify/specify7/tree/xml-editor/specifyweb/context/data

```xml
<viewsets><viewset name="Fish Views">
```

However, I do not see any `viewsets` in https://github.com/specify/viewset-schema, so I would assume it's a mistake or a historical fluke.

---

Then, to add the `name` attribute, add this to the viewSetsSpec:

```ts
    name: pipe(
      syncers.xmlAttribute('name', 'empty'),
      syncers.default<string>('')
    ),
```

and in React code set the name attribute if not already set
for example, that could be put in here - 
https://github.com/specify/specify7/blob/07c2e7b19adff23dc3efa05e59a24c815bd109bb/specifyweb/frontend/js_src/lib/components/FormEditor/Editor.tsx#L123

**Comment by CarolineDenis** [comment]
@maxpatiiuk , 
> handleSaved is called when the Save button is clicked, not when the editor is opened

Yes, that is what meant. When Save btn is clicked, handleSaved() is not called

> and in React code set the name attribute if not already set
> for example, that could be put in here -
> 
> [specify7/specifyweb/frontend/js_src/lib/components/FormEditor/Editor.tsx](https://github.com/specify/specify7/blob/07c2e7b19adff23dc3efa05e59a24c815bd109bb/specifyweb/frontend/js_src/lib/components/FormEditor/Editor.tsx#L123)
> Line 123 in [07c2e7b](https://github.com/specify/specify7/commit/07c2e7b19adff23dc3efa05e59a24c815bd109bb)

>  ...viewSets,

Why adding that in the delete button? 
Shouldn't we add it in the createView.ts? https://github.com/specify/specify7/blob/3b468ec22baf38bc29dfeb77ad7bde6a54bf05ed/specifyweb/frontend/js_src/lib/components/FormEditor/createView.ts#L103

The only issue is that we do not have access to the name of the resource here

**Comment by maxpatiiuk** [comment]
> Yes, that is what meant. When Save btn is clicked, handleSaved() is not called

Hmm, can you try again? It works for me:

https://github.com/specify/specify7/assets/40512816/ef0f977e-5c5e-4923-b668-c44e73ca42fb

> Why adding that in the delete button?

Ups, good catch!

I mean to link to this place: https://github.com/specify/specify7/blob/issue-4366/specifyweb%2Ffrontend%2Fjs_src%2Flib%2Fcomponents%2FFormEditor%2FEditor.tsx#L163

> Shouldn't we add it in the createView.ts?

That works too
Though, two reasons to do that in Editor.tsx:
- we have access to app resource name
- if existing resource does not have a name, the code in Editor.tsx will add it if needed. where as the code in createView.ts would only run for newly created resources

> The only issue is that we do not have access to the name of the resource here

you have - see `resource` and `appResource` from FormEditorContext
