### ISSUE TITLE
WorkBench not checking for uniqueness rules 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4500]
**Describe the bug**

When a uniqueness rule is configured in specify, this rule is not being respected during workbench validation/uploads. It does appear to work as expected for data entry, but not in the WorkBench. 

**To Reproduce**

1. Configure business rule
2. Create WB dataset and mapping for this field
3. Enter duplicate data in dataset and validate

**Expected behavior**

The WorkBench should not validate or upload duplicate entries for fields with uniqueness rules configured. 

**Screenshots**

**` fwri_1_9_24 :`**

[link to dataset on test panel ](https://fwri1924-edge.test.specifysystems.org/specify/workbench/359/)

<img width="1920" alt="Screenshot 2024-02-09 at 9 54 54 AM" src="https://github.com/specify/specify7/assets/135047322/cf89ac21-956f-40eb-b667-ab9d38ed16d7">

<img width="1920" alt="Screenshot 2024-02-09 at 9 54 43 AM" src="https://github.com/specify/specify7/assets/135047322/5d366d5c-9bbb-4f83-a0ea-cb1116b2ca85">

[link to dataset on test panel](https://fwri1924-edge.test.specifysystems.org/specify/workbench/358/)

<img width="1920" alt="Screenshot 2024-02-09 at 9 55 24 AM" src="https://github.com/specify/specify7/assets/135047322/8c74550e-0369-4ff5-b39a-151e7b82fc53">

<img width="1920" alt="Screenshot 2024-02-09 at 9 55 41 AM" src="https://github.com/specify/specify7/assets/135047322/56ec675a-9032-4bb4-8223-150ba0e8b0a9">

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge` / `v7.9.3.1`
- Database Name: `fwri_1_9_24`

**Reported By**
Corinna & Dan @ CSIRO

> in addition to Corinna's test I also tried it out on two different fields in another system and got exactly the same result - adding COs via a form behaves as expected (field turns red when duplicate value entered) but I can bypass the whole check via the Workbench: 
> ![image](https://github.com/specify/specify7/assets/135047322/5ad727d9-27e1-494a-96f0-f0c1f9d49f71)
> ![image](https://github.com/specify/specify7/assets/135047322/270ee854-8151-46e2-85c4-13a2813f5c7d)

[link to demofish dataset](https://sp7demofish.specifycloud.org/specify/workbench/60/)
[link to demofish recordset of WB uploads](https://sp7demofish.specifycloud.org/specify/view/collectionobject/51820/?recordsetid=43)

> I've set this up on your demofish site so you can see the issue - in KUFishtissue I've added text8 to the collection object form 
> and have set the uniqueness check:
> ![image](https://github.com/specify/specify7/assets/135047322/19924a23-4a07-4f34-a0eb-7bbd7576103e)
> ![image](https://github.com/specify/specify7/assets/135047322/c21570cb-f20c-4346-b22a-ca517166e12c)
> And here is the workbench dataset that uploaded the duplicates: 
> ![image](https://github.com/specify/specify7/assets/135047322/77bdce97-3028-417c-892e-83db8fd3d7c5)

**Comment by danb213** [comment]
We have been testing the fix for this in the specific version provided to us (https://github.com/specify/specify7/compare/v7.9.3.1...unique-workbench-fix) and everything looks good apart from one issue involving having blank/empty/null values.

For a single field you can have multiple empty values, which whilst technically is not unique is not really a problem because you can make it a required field if it must always have a value. However when doing the group uniqueness check across multiple fields the system is failing to spot duplications.

![image](https://github.com/specify/specify7/assets/110948439/1352c42e-4045-44f8-89ba-eb48d34bad5f)

In the image above the first two rows show the WB correctly flagging a duplicate when all three fields are populated, but for the bottom two rows it is allowing duplication because the last field is left empty in both cases.

For our implementations we can make the multiple fields in the group check required fields to avoid this, but it probably should be flagged as a bug?

**Comment by danb213** [comment]
Just wondering if the new issue (#4730) is a blocker for getting this ticket resolved? Will we see this fix in the next release?
