### ISSUE TITLE
Max Uncertainty Est field won't validate on form

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#4508]
**Describe the bug**

After adding GEOLocate marker to application, the form is unable to be saved because of the Max Uncertainty Est field, even though it doesn't actually tell you that. On `7.9.3.1`, the Save button will turn red momentarily but it dismisses when a value is entered into this field. On `edge`, nothing you do makes the form happy. 

**To Reproduce**

1. Go to new Locality
2. Add name and geography
3. Open GEOLocate and place marker
4. Save to Application
5. See error on `edge` 

**Expected behavior**

Allow to save form

**Screenshots**

https://github.com/specify/specify7/assets/135047322/13e7aa42-4f00-42a5-8203-cc4a94cdb9b6

- OS: macOS
- Browser: Chrome
- Specify 7 Version: `edge`
- Database Name: `fwri_1_9_24`

**Comment by melton-jason** [comment]
I was able to recreate this issue all the back to `7.8.6`!
The problem is that the `uncertainty` in GeoLocate is ` ` (or an empty string), and Specify attempts to parse this as a floating point number which results in the JavaScript primitive `NaN`. 
Specify then tries to set the `maxUncertainityEst` to this value, which results in the save blocker. 

https://github.com/specify/specify7/blob/9044ffc1e29eea13e1d18ccf20cad10ef5290978/specifyweb/frontend/js_src/lib/components/FormPlugins/GeoLocate.tsx#L70-L73

**Comment by melton-jason** [comment]
Not fixed by #4588

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6) but now you can just bypass the save by pressing it even though it is red and says the field is invalid 

https://github.com/user-attachments/assets/4998a694-8f6e-42eb-b0b7-221fd2039878
