### ISSUE TITLE
Permission denied dialog miss information 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4553]
**Describe the bug**
In edge when you get the permission denied dialog it does not include all the information and just says "no permission" 

**To Reproduce**

1. Log in as a user with limited permissions 
2. Do something you don't have permission to do 
3. See error with dialog 

**Expected behavior**
The dialog should have the same information that it has in 7.9.3

**Screenshots**
Edge
<img width="958" alt="Screenshot 2024-02-16 095703" src="https://github.com/specify/specify7/assets/150940840/796fc0a0-b21b-468d-9f34-6cd807bd5116">

7.9.3
<img width="960" alt="Screenshot 2024-02-16 095712" src="https://github.com/specify/specify7/assets/150940840/f7dcacb9-a4c3-4b4b-a740-51f6210bc706">

Alternatively, please fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823

**Comment by maxpatiiuk** [comment]
But the bigger issue here is the fact that the permission denied dialog is displayed at all
Everywhere in specify, we tried to simply hide/disable UI elements if user has no permission to them, rather than throw a scarry error message.
The fact that the error message occurs, means we might have missing permission checks somewhere.

The only case where error dialogs are expected if user went directly to a URL for a tool/resource they have to access to.

@emenslin could you please post the exact steps you use to get to this error dialog - and probably post that as a new issue (and assign @realVinayak if it relates to attachments)

**Comment by emenslin** [comment]
> @emenslin could you please post the exact steps you use to get to this error dialog - and probably post that as a new issue 


There is another issue I made around the same time as this one (#4550) which shows the exact steps that got me that dialog.
