### ISSUE TITLE
Add Field button touching separator box

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4619]
**Describe the bug**
When you open a table formatter there is no space between the last separator row and the `add field` button. 

**To Reproduce**

1. Go to app resources 
2. Click on `record formatters` 
3. Open the default accession formatter
4. Scroll down to the `add field` button 
5. See error

**Expected behavior**
There should be a gap between the last separator and the `add field` button. 

**Screenshots**
<img width="687" alt="Screenshot 2024-03-08 145936" src="https://github.com/specify/specify7/assets/150940840/99a9aae0-36cb-4726-9cda-71a2cea08187">

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: KUFish51623
- Collection name: KU Fish Voucher Collection

**Comment by grantfitzsimmons** [comment]
@emenslin In the future, could you please provide the following:
1. Include the URL with every screenshot, if possible (except for user-submitted screenshots).
2. Provide the username and collection.

This will reduce the time developers spend recreating an issue in the future. URLs often contain direct record IDs or route them to the dialog you are having issues with directly.

Thank you! 😊 This issue is very complete otherwise!
