### ISSUE TITLE
Icon overlaps label in form when "Use accessible month picker" is unchecked

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4642]
**Describe the bug**
When "_Use accessible month picker_" in Preferences is unchecked, on a form that has a date type selected as "_Month / Year_", the calendar icon overlaps the label next to it when the browser width is adjusted small enough for them to touch each other. 

**To Reproduce**
1. Go to Preferences -> Uncheck "_Use accessible month picker_" (https://umherb11024-edge.test.specifysystems.org/specify/user-preferences/)
2. Go to any form with a Date and the option for "_Month / Year_" (Data Entry or in video: https://umherb11024-edge.test.specifysystems.org/specify/view/collectionobject/1262680/)
3. Select "_Month / Year_" for the date if it is not already selected
4. Adjust window size smaller to see that the icon overlaps it

Note: Only happens on top section of data entry

**Expected behavior**
The calendar icon should not overlap the label. Expected behavior is also in the video: **Determined Year** underneath **Determinations** does not overlap with the label next to it.

**Evidence**
Showing the issue (Cataloged Date -> Project) and showing the expected behavior (Determined Year -> Determiner)

https://github.com/specify/specify7/assets/118556884/7aeebfd9-ce0e-4671-92d3-04679b3a16a2

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `umherb_1_10_24`

**Comment by grantfitzsimmons** [comment]
@pashiav Can you make sure to test this behavior against the latest tagged release?

**Comment by pashiav** [comment]
Works on **`v7.9`**. Expected behavior:

https://github.com/specify/specify7/assets/118556884/7e2a16a5-74bd-44b9-bd5c-6b8c63715804

**Comment by CarolineDenis** [comment]
I can only reproduce this behavior with UmHerb db. 
When removing w-unset from the input, 
https://github.com/specify/specify7/blob/afe8e8f9c0f8737e76ea68942bb38635d0ee63d7/specifyweb/frontend/js_src/lib/components/FormPlugins/DatePrecisionPicker.tsx#L30
the issue is fixed but I am wondering if it breaks something else. I'd like to be sure it doesn't. 
I will push the change to https://github.com/specify/specify7/pull/4671
and we can test it on that branch 
@maxpatiiuk , opinion?
