### ISSUE TITLE
`ExportFeed` visual editor creating invalid definitions

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4650]
**Describe the bug**
Creating or modifying an ﻿`ExportFeed` app resource using the visual editor results in export failures due to a KeyError in the code. The issue stems from attribute naming inconsistencies (i.e. `﻿collectionid` instead of `﻿collectionId`). To ensure functionality, the visual editor must use consistent camelcase for attribute names in line with existing resources.

## New `ExportFeed` app resource created with the visual editor

**This is not working.**

```xml
<?xml version="1.0" encoding="UTF-8"?>
<channel>
	<title>Test</title>
	<description>Test</description>
	<item collectionid="4" userid="1" notifyuserid="1" definition="DwCA_voucher" metadata="DwCA_voucher_metadata" days="7" filename="kudwca.zip" publish="true">
		<title>KU Fish Voucher</title>
		<id>ba7b743e-3263-4016-aebf-995f0d6a6e19</id>
	</item>
</channel>
```

After creating or adding to an existing `ExportFeed` app resource using the visual editor in `edge`, all exports will fail. The errors look like this on the several databases I tested this on:

```
"traceback":"Traceback (most recent call last):\n  File \"/opt/specify7/specifyweb/export/views.py\", line 169, in try_update_feed\n    update_feed(force=True, notify_user=user)\n  File \"/opt/specify7/specifyweb/export/feed.py\", line 53, in update_feed\n    collection = Collection.objects.get(id=item_node.attrib['collectionId'])\nKeyError: 'collectionId'\n"}
```

This error indicates a "KeyError" occurred in the code, specifically when trying to access a key ('collectionId') in a dictionary where this key is not present. That led me to look and see if this key is being created by the visual editor, and lo and behold, it is not.

The visual editor is creating a `collectionid` attribute in `<item>` rather than `collectionId` (notice the case difference). 

## Existing `ExportFeed` app resource created manually

```xml
<channel>
  <title>KUBI ichthyology RSS Feed</title>
  <description>RSS feed for KUBI Ichthyology Voucher and Tissue collections</description>
  <item collectionId="4" userId="2" notifyUserId="2" definition="DwCA_voucher" metadata="DwCA_voucher_metadata" days="7" filename="kui-dwca.zip" publish="true">
    <title>KU Fish</title>
    <id>8f79c802-a58c-447f-99aa-1d6a0790825a</id>
  </item>
</channel>
```

Notice `collectionid` is `collectionId`, `userid` is `userId`, `notifyuserid` is `notifyUserId`, and all the other names are consistent.

The visual editor needs to use the correct keys, so it should use camelcase properly to make it consistent with existing `ExportFeed` resources. If we shipped everything now, users would be unable to create working export feeds and be unable to use the "Update RSS Feed" function after doing so.

**Comment by CarolineDenis** [comment]
Attribute converted to lower case happen in: 
https://github.com/specify/specify7/blob/2df7eff405eb221f514a1634b80255a8ae01e407/specifyweb/frontend/js_src/lib/components/ExportFeed/index.tsx#L41
more specially in `deserializer(definition) `

**Comment by maxpatiiuk** [comment]
I think this is the place where conversion to lowercase is happening:

https://github.com/specify/specify7/blob/aa434e5d24f9b88b3a2c2d892d8619f5d35e815e/specifyweb/frontend/js_src/lib/components/Syncer/syncers.ts#L73

Reason:
When I was writing syncer, I looked at every single form attribute that ever existed, and they were all lowercase (I forgot to look at Export Feed). To catch typos, on the front-end we always use camelCase instead of lowercase (so `notifyUserId` instead of `notifyuserid` - more readable, and less bug-prone as IDE can catch typos), so I made syncer allow you to specify attribute in camel case, then it would look for camel case or lower case attribute in XML when reading, but convert to lower when writing back.

Given that export feeds is the only place where camelCase XML attributes are used, and that export feeds are only used by sp7, not sp6, I would say a propper fix for this is to make sp7 back-end more case-insensitive, rather than modifying the syncer (though we could add a flag to xmlAttribute to disable automatic lowercase conversion)
