### ISSUE TITLE
Adding new query in Stats displays "Error" results and large lists of numbers

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4684]
**Describe the bug**
When adding a new query to a category in Statistics, the resulting dialog shows **Taxa/Geographies Represented** items aligned with "Error" results and a long list of numbers under **Type Specimens**.

**To Reproduce**
Branch: `edge`
Db: `fwri_1_9_24`
1. Go to Statistics (https://fwri1924-edge.test.specifysystems.org/specify/stats)
2. Click Edit
3. Click Add on any category 
4. Scroll down to see "Error" results and long list of numbers

**Expected behavior**
Dialog after clicking **Add** should only show the selection of **Queries** and **Available Default Statistics**.
Behavior in `v7.9`:
![Screen Shot 2024-03-25 at 12 31 19 PM](https://github.com/specify/specify7/assets/118556884/c80f8899-201e-40b2-a1a9-0958f69c5a4e)

**Evidence**
`edge`

https://github.com/specify/specify7/assets/118556884/b1b43758-3a46-4344-92cf-502133cc0ec9

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `fwri_1_9_24`

**Comment by CarolineDenis** [comment]
NOTES: 
defaultDynamicCategoriesResponse is: 
/stats/collection/taxonsRepresented/dynamicPhantomItem/

"21",
"10",
"12",
"4",
"19",
"20",
...

Instead of 
/stats/collection/taxonsRepresented/dynamicPhantomItem/
: 
Array(10)
0
: 
"Kingdom"
1
: 
"Phylum"
2
: 
"Class"
3
: 
"Order"
4
: 
"Family"
5
: 
"Subfamily"
6
: 
"Genus"
7
: 
"Subgenus"
8
: 
"Species"
9
: 
"Subspecies"

see: 
  useDefaultDynamicCategorySetter(
    defaultDynamicCategoriesResponse,
    setDefaultLayout
  );
  in Statistics/index.tsx
