### ISSUE TITLE
Date picker hiding date precision on narrow forms

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4691]
**To Reproduce**

1. Go to https://fitznhmaoct2023-edge.test.specifysystems.org/specify/view/collectionobject/new/ as `petrifiedroadkill` in the NHMA Malacology collection
2. Zoom in or make the window narrower
3. See that `edge` does not make enough room for "Full Date" or "Month / Year"

**Expected behavior**
The date picker should have "Full Date", "Month / Year", and "Year" fully visible.

**Screenshots**

https://github.com/specify/specify7/assets/37256050/1ff19c8d-606c-4514-bbdb-bcdf7ed3a2cf

[Specify 7 System Information - 2024-03-27T18_27_51.565Z.txt](https://github.com/specify/specify7/files/14779664/Specify.7.System.Information.-.2024-03-27T18_27_51.565Z.txt)

**Comment by CarolineDenis** [comment]
@maxpatiiuk, our fix for https://github.com/specify/specify7/pull/4671 is probably the reason behind this. Any thought?

**Comment by maxpatiiuk** [comment]
> Date picker hiding date precision on narrow forms

This was the intended behavior.

Previously, date picker would force the entire column to be super wide, stealing more space from other columns.
Now, the date picker is only as wide as needed to display the date input itself. Then, if there is not enough space for the full `Select`, `Select` gets shrunk as much as needed.

Given that `Select` is less of a priority than the date input (or the fields in the other columns on the form), this seems like a desirable tradeoff when there isn't enough space. `Select` is lesser priority because it's not showing data, but only controls for the form, and because `Select` is perfectly operational even when shrunk.

See how nicely the new behavior optimizes the sizing at each resolution:

https://github.com/specify/specify7/assets/40512816/e8ed9487-ae4f-4aec-8456-818031f059a4

1. When there is plenty of space, the `Select` is full width, and the date input takes all the available space
2. When there is less space, the date input occupies full width, and the `Select` begins to shrink
3. When there is an extreme space pressure, the date input would also begin to shrink it

The new behavior is much more "space smart", even if it may look a bit less "pretty". Though really, it's letting neighboring columns reclaim a bit more space, making neighboring columns a bit less "ugly". Seems like a great tradeoff.

Thoughts?

**Comment by grantfitzsimmons** [comment]
@maxpatiiuk 

I'd prefer the date area to be shown over the precision, so I guess it is an improvement, but in this case both the full date and "Full Date" were shown in `v7` and they have enough room in `edge` ...

<img width="862" alt="image" src="https://github.com/specify/specify7/assets/37256050/682ffeb7-de33-4685-a6e6-206aef5699f2">

**Comment by maxpatiiuk** [comment]
> and they have enough room in edge ...

no they didn't have enough room - they just forcefully pushed other columns out of the way.
Notice how on the left screenshot, the Cataloger query combo box has fewer letters visible making it less usable. The fields in the last columns are also a bit narrower. At the same time, the fields in the middle column were way too wide.

if there is enough room, then everything would be displayed in full, without being cut off.

If we need a good compromise that is both space-efficient, and looks great, we could replace the `Select` in the date picker with just a button-icon, that when clicked would either toggle the date format or open a pick list to select a date format.
