### ISSUE TITLE
Generating Invoice on Save returns no results

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4716]
**Describe the bug**
When Saving a Gift record with "Generate Invoice on Save" checked, a new tab opens but returns no results. It should return a report in a new tab.

**To Reproduce**
1. Go to any Gift (https://umherb11024-edge.test.specifysystems.org/specify/view/gift/98/)
2. Edit a simple field (e.g. Description field)
3. Click **Save**
4. See new tab opens with the text "The report query returned no results."

**Expected behavior**
On Save, a new tab should open with the report from the Gift that it generated from.
Expected behavior on `v7.9.3.1`:

https://github.com/specify/specify7/assets/118556884/7f399022-4d78-4d64-aaed-6da806650e86

**Evidence**
`edge`

https://github.com/specify/specify7/assets/118556884/bc665199-15c3-4e13-9c32-3b93f9d9dfd7

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `umherb_1_10_24`
[Specify 7 System Information - 2024-04-01T20_08_20.319Z.txt](https://github.com/specify/specify7/files/14828123/Specify.7.System.Information.-.2024-04-01T20_08_20.319Z.txt)

**Comment by melton-jason** [comment]
Might be related to the changes in #4299

**Comment by grantfitzsimmons** [comment]
I've done some investigating. Here's what I found: 🔍 

Initially I suspected there may be a discrepancy between the results of the associated query with the report resource in `v7.9.3.1` and `edge`. I found that the associated query (SpQueryID = `516`) returned the same 211235 results in both versions.

<img width="2037" alt="image" src="https://github.com/specify/specify7/assets/37256050/a0c00878-b441-43b9-8b02-4c0895211f4c">

That means that we can most likely rule out the possibility of the query builder returning different results due to the base query alone. Though an interesting point caught my attention:

<img width="922" alt="image" src="https://github.com/specify/specify7/assets/37256050/d7dd09a2-c736-4358-8a21-f459b93e955c">

The 'Gift Number' field filters the results to only include Gift records that have a `giftNumber` that contains `1`. This issue features a gift that has a Gift Number of `3433`.

Back to Gift '3433' (https://umherb11024-edge.test.specifysystems.org/specify/view/gift/98)– when running the report in `edge`, it properly filters the results by the query, which would naturally exclude the gift since the Gift Number (`3433`) does not contain `1`.

When running the report from the dialog, the user must replace the `1` with the Gift Number (`3433`), which then prevents the results from being filtered by the original query, thus returning the report as it was shown when run after saving in `v7.9.3.1`:

https://github.com/specify/specify7/assets/37256050/ad34215c-2d51-4bc3-ac9e-916073ff9bfe

I think the problem is that the changes made in https://github.com/specify/specify7/pull/4299 now correctly follow the query filtering parameters linked to the report. Now it returns no results because the query immediately filters out the Gift the report is being run on due to it not containing `1` in the `giftNumber` field.

Is this the right behavior? I would argue it is, but I am open to a discussion about this.
