### ISSUE TITLE
Text cursor focus is lost when warning panel appears

### ISSUE THREAD

**Issue by lexiclevenger** [specify/specify7#4753]
**Describe the bug**
When the warning panel shows up in xml editor, the location of the text cursor is lost.

**To Reproduce**

1. Go to a form definition.
2. Go to a field and modify the name to be invalid.
3. Either wait for the warning panel to appear or press Command+Shift+M to see warning panel.
5. See that your cursor position has been removed.

**Expected behavior**
When a warning appears, the editor should not lose where your cursor is in the text.

**Screenshots**

https://github.com/specify/specify7/assets/164079735/8f5c14a6-01db-4c16-953d-0b87dab04f52

[Specify 7 System Information - 2024-04-05T20_46_40.528Z.txt](https://github.com/specify/specify7/files/14890647/Specify.7.System.Information.-.2024-04-05T20_46_40.528Z.txt)

- OS: Mac
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: fitznhmdoct2023
- Collection name: Vertebrate Paleontology
- User Name: petrifiedroadkill

**Comment by grantfitzsimmons** [comment]
+1 on this issue

**Comment by CarolineDenis** [comment]
NOTES: 
The linter with the errors does not appear if: 
- type a name with a mistake in it 
- linter opens 
- fix the mistake 
- linter closes 
- create a new mistake 
- linter does not reopen

**Comment by maxpatiiuk** [comment]
caused by a code we added to fix a different bug

https://github.com/specify/specify7/blob/issue-4741-fixup/specifyweb/frontend/js_src/lib/components/AppResources/EditorComponents.tsx#L227-L230

@CarolineDenis could you use git blame to see for what bug was this code added and if we can fix it in some other way (i.e only call setTimeout if it has been less than 1s since editor creation)

calling openLintPanel will always cause the focus to move to it according to their source code:
https://github.com/codemirror/lint/blob/ed7e40363463fed911cd066748bcc58e7368c54c/src/lint.ts#L216-L223
(unless we manually revert the focus back)
