### ISSUE TITLE
Preview Search tool in Record Formatters does not return correct results

### ISSUE THREAD

**Issue by pashiav** [specify/specify7#4756]
**Describe the bug**
Record Formatters' Preview Search tool does not always return the correct results.

**To Reproduce**

1. Go to AccessionAgent table formatter: https://umherb11024-edge.test.specifysystems.org/specify/resources/app-resource/92/formatter/AccessionAgent/1
2. Copy the name of an existing Agent in the Preview 
3. Click **Search** => paste the existing agent's name into the Agent field (e.g. Gerofue)
4. Click the green **Search** button 
5. See that it returns no results.

**Expected behavior**
The Search tool should always return the correct results for any input.

**Evidence**
1. Video shows that _Gerofue_ exists but does not appear in results => then selecting Collector returns all the collector records => shows that _Andrea Matthies_ exists => shows that no results are returned when only searching for _Andrea Matthies_

https://github.com/specify/specify7/assets/118556884/dd599d8f-73dd-49f4-93db-3449c8d99f83

2. Example of a record existing in Loan but returning no results: https://umherb11024-edge.test.specifysystems.org/specify/resources/app-resource/92/formatter/Loan/33

https://github.com/specify/specify7/assets/118556884/130221c3-6e65-4eaa-bf72-5e186f9f2b84

Note: I checked CO table format and it returned the correct results

[Specify 7 System Information - 2024-04-08T15_01_35.011Z.txt](https://github.com/specify/specify7/files/14907284/Specify.7.System.Information.-.2024-04-08T15_01_35.011Z.txt)
OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `umherb_1_10_24`

**Comment by CarolineDenis** [comment]
NOTES: 
- need to search on related tables in some cases 
- i.e: collectors, accessionAgent, 
By example the table passed to SearchDialog in AccessionAgent formatter should be 
`table.getRelationship('agent')?.relatedTable`
and not just table

**Comment by melton-jason** [comment]
I do not think the table being searched on is the problem here. 
When previewing records for the AccessionAgent formatter/aggregator, the Search results should return AccessionAgents, not Agents. 
An AccessionAgent format can not be applied to Agent records, and searching on the Agent table removes the ability to search on any AccessionAgent fields. 

The problem is that currently the express/simple search endpoint on the backend does not support searching on relationships, and even if it did the frontend does not pass the correct value as a query parameter to the endpoint. 
In other words, Specify is completley ignoring the value of the `Agent` in the query combobox.

The reason the `SearchDialog`  contains the `Agent` query combobox in the first place is that there is no default `AccessionAgentSearch` view. 

<img width="422" alt="Screenshot 2024-04-09 at 11 40 55 AM" src="https://github.com/specify/specify7/assets/64045831/141dec41-d062-4e9f-8cbb-6d1e9178fd62">

And in the case a Search View does not exist, Specify defaults to fetching the view defined for the table in the datamodel. 
(In this case, `AccessionAgent`) 

https://github.com/specify/specify7/blob/672427135169d65ba1573fa257267a963b5247e0/specifyweb/frontend/js_src/lib/components/SearchDialog/index.tsx#L150-L156

I suspect that no default Search View contains a query combobox: only non-relationship fields from the table. 
Changes would need to be done on both the frontend and backend to accommodate searching on `to-one` relationships.
This is probably an issue which existed long before `v7.9.4`, although `v7.9.4` introduces features which make viewing the SearchDialog for tables such as AccessionAgent much more common. 

---

The issue with a SearchView not returning the same results as the records which are fetched by default for previewing the formatter/aggregator is that the preview records can exist outside of the scope of the currently logged in collection. 
This change was made in https://github.com/specify/specify7/pull/4509

**Comment by CarolineDenis** [comment]
NOTES: 
Decision made today: 
Search option will be removed, the user to only will use the query builder
