### ISSUE TITLE
Table formats and aggregation using title instead of name

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#4797]
**Describe the bug**
The table formats and table aggregation are trying to use the title which then makes it show up with `(current, invalid value)`

**To Reproduce**

1. Go to table formats/aggregation through schema config 
2. Select any table
3. Make the title and name different values 

**Expected behavior**
The schema should use the name

**Screenshots**

https://github.com/specify/specify7/assets/150940840/106e2168-7cca-4c59-9745-f1e4569afc6e

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge
- Database Name: lsumzmammals9823
- Collection name: mammals
- User Name: Spadmin
[Specify 7 System Information - 2024-04-16T19_11_18.890Z.txt](https://github.com/specify/specify7/files/15001818/Specify.7.System.Information.-.2024-04-16T19_11_18.890Z.txt)

**Comment by maxpatiiuk** [comment]
> Table formats and aggregation using title instead of name

They should be using title instead of name.

Usually, title field is to be shown to the user, and name is to be stored in the database when referring to that resource (though, a database ID is always better option than `name` if available - sadly, not available for formatters/aggregators)

What could be the cause of the issue here is that formatter is defined in some collection, but not current collection. At the same time, the schema configuration settings apply at the discipline level, so it's possible for setting to be valid in one collection, but not another - which is a known limitation of the schema config system(

**Comment by grantfitzsimmons** [comment]
>What could be the cause of the issue here is that formatter is defined in some collection, but not current collection. At the same time, the schema configuration settings apply at the discipline level, so it's possible for setting to be valid in one collection, but not another - which is a known limitation of the schema config system

Unfortunately, that is not the case here. There is not another table format titled `Collection Object` elsewhere, and the one it is using has the title `Collection Object`, but the name `CollectionObject`. The pick list says the selected value is "Invalid" because it is checking against the titles, whereas the issue is that this is a valid choice.

This database only has a single collection and discipline.
