### ISSUE TITLE
No Formatter definition for Accession causes an error on Accession Combo Box.

### ISSUE THREAD

**Issue by alesan99** [specify/specify7#4817]
**Describe the bug**
Only on production, if the DB has an empty definition for the default Record Formatter for Accessions, attempting to use the Query Combo Box for the Accession number on the Collection Object Data Entry form will cause an error to appear.  
Presumably happens on other combo boxes.

**To Reproduce**

1. Ensure your DB has no fields for the Record Formatter for Accession (User -> App Resources -> Record Formatters -> Table Format: Accesssion)
2. Go to Data Entry and create a new CollectionObject.
3. Type anything into the accession combo box and wait.
4. An error occurs.

**Expected behavior**
On stable v7, there is no error and the suggestion results appear as `<Formatter not defined.>`.

**Screenshots**
![image](https://github.com/specify/specify7/assets/8108710/8a523124-1e67-4e0a-8e56-a6ac87194ff5)

**Crash Report**

[Specify 7 Crash Report - 2024-04-22T16_22_09.712Z.txt](https://github.com/specify/specify7/files/15067362/Specify.7.Crash.Report.-.2024-04-22T16_22_09.712Z.txt)

Please, also fill out the following information manually:

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge(debug)
- Database Name: KUBirds_8_25_23
- Collection name: Ornithology
- User Name: spbirdadmin

**Comment by pashiav** [comment]
LHS Expected Behavior `v7.9.3.1` | RHS `edge`:

https://github.com/specify/specify7/assets/118556884/7e655b94-7ba2-43fc-816a-558744b655f3


**Crash Report**
[Specify 7 Crash Report - 2024-04-22T19_39_00.947Z.txt](https://github.com/specify/specify7/files/15067866/Specify.7.Crash.Report.-.2024-04-22T19_39_00.947Z.txt)

OS: macOS Monterey (12.6.5)
Browser: Chrome
Specify 7 Version: `edge`
Database Name: `umherb_1_10_24`
[Specify 7 System Information - 2024-04-22T19_39_34.918Z.txt](https://github.com/specify/specify7/files/15067868/Specify.7.System.Information.-.2024-04-22T19_39_34.918Z.txt)

**Comment by pashiav** [comment]
After input error, duplicates are allowed and renamed in field when adding a new accession with QCB. 

https://github.com/specify/specify7/assets/118556884/1684ef9c-bc50-49d6-aa15-61235a616455

![Screen Shot 2024-04-22 at 3 52 02 PM](https://github.com/specify/specify7/assets/118556884/4a70ef6d-ddb2-4840-80f2-2c644977a788)
