### ISSUE TITLE
Collection Objects without any current determination can be saved

### ISSUE THREAD

**Issue by combs-a** [specify/specify7#4819]
**Describe the bug**
When you add and delete a determination, no determination will be current anymore. Present in v7.9.3 as well.

**To Reproduce**

1. Go to Data Entry->Collection Object
2. Add multiple determinations
3. Delete the determination with isCurrent checked
4. Check the other determinations to see that there is no longer any marked as current
5. See that you can save

**Expected behavior**
No behavior was implemented for this previously. Should maybe have a save blocker or something to prevent from saving without a current determination marked? Unsure of the implications of this, but knowing the up-to-date determination seems important.

**Screenshots**
![image](https://github.com/specify/specify7/assets/71564869/dbb7aca8-071a-44ba-b7a3-97abb5c68993)

- OS: Windows 10
- Browser: Firefox
- Specify 7 Version: `edge`
- Database Name: `sdnhm_herps_2_8_24`
- Collection name: `Herp-PC`
- User Name: `testuser`

[Specify 7 System Information - 2024-04-22T21 53 37.884Z.txt](https://github.com/specify/specify7/files/15068910/Specify.7.System.Information.-.2024-04-22T21.53.37.884Z.txt)

**Comment by grantfitzsimmons** [comment]
For reference, Specify 6 prevents saving the Collection Object record if there is not a current determination. I would advise taking this approach rather than arbitrarily setting the second determination as "current" so the data is not falsified.

<img width="1280" alt="image" src="https://github.com/specify/specify7/assets/37256050/e690bd5a-910f-456f-8f53-787832657b88">
