### ISSUE TITLE
Sp7 Email Message Launcher Button Generates Incorrect Email Format

### ISSUE THREAD

**Issue by Areyes42** [specify/specify7#4820]
**Describe the bug**
When utilizing the email message launcher button on Sp7 Edge, it appends the content from the last name text field to the email address, while the content from the first name text field is appended to the end of the entire message.

**To Reproduce**

1. Create or go to an existing agent in the database
2. Ensure there is a Last Name and Email associated with the agent
3. Click the 'Launch Email Message' button
4. See email format error in mail window

**Expected behavior**
On Specify v7.9.3.1(debug), the email address in the mail window is properly formatted and does not carry over any other text fields besides the email.

**Screenshots**
Left-side: `Edge`     |     Right-side: `v7.9.3.1`

https://github.com/specify/specify7/assets/130881183/6f653419-fa39-463b-a878-a94ab96936b3

- OS: macOS Sonoma 14.4.1
- Browser: Chrome
- Specify 7 Version: edge(debug)
- Database Name: KUFish_5_16_23
- Collection name: KU Fish Voucher Collection
- User Name: spfishadmin

**Comment by grantfitzsimmons** [comment]
To fix this, the web link definition needs to be reconfigured. It seems this was modified during testing, and this issue is simply a manifestation of that.

The breakdown of this `MailTo` web link is as follows:
* `mailto:` (static value)
* `email` (field value from the Agent table)
* Formatted resource (the Agent record formatted)

It is behaving as expected with this configuration in my opinion!

<img width="505" alt="image" src="https://github.com/specify/specify7/assets/37256050/e6422e7b-f3a1-475c-bfca-95c267afe5d9">


https://kufish51623-edge.test.specifysystems.org/specify/resources/app-resource/8/web-link/0

This was customized during testing, indicating it was likely broken without any thought.
