### ISSUE TITLE
Subview is collapsed immediately when record is added

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#4865]
**Describe the bug**

**To Reproduce**

1. Go to https://fitznhmdoct2023-edge.test.specifysystems.org/specify/view/collectionobject/new/ as `petrifiedroadkill` in the "NHMD Danekrae" collection
2. Add a record to the Paleo Context subview
3. See that the subview is collapsed in grid view rather than open to let the user easily add data to the record

**Expected behavior**
It should work as it did in `v7.9.3.1`.

It should automatically be expanded when a new item is added to a subview in grid mode. It adds an extra click each time an item is added so it can be expanded. 

**Screenshots**
Left is `v7` (expected behavior), right is `edge` (bug)

https://github.com/specify/specify7/assets/37256050/b5d68f9a-8b1e-4eb6-9c62-c89f2e5b44b4

https://fitznhmdoct2023-edge.test.specifysystems.org/specify/view/collectionobject/new/
https://fitznhmdoct2023-v7.test.specifysystems.org/specify/view/collectionobject/4371987/

**System Information**
[Specify 7 System Information - 2024-05-01T16_09_51.048Z.txt](https://github.com/specify/specify7/files/15178896/Specify.7.System.Information.-.2024-05-01T16_09_51.048Z.txt)

**Database:** Fitz_NHMD_Oct_2023
**Username:** petrifiedroadkill
**Collection:** NHMD Danekrae

**Comment by CarolineDenis** [comment]
NOTES: 
- might be related to https://github.com/specify/specify7/pull/4740

**Comment by alesan99** [comment]
As a sidenote, this also happens with Gift Preparations in Gift forms. Though this is on both production and edge.
I believe this was fixed by https://github.com/specify/specify7/pull/4597 at one point, but it seems to have broken again (The other cases tested in the comments still work).

![yage42k6Se](https://github.com/specify/specify7/assets/8108710/af6cc321-3a58-4f90-b79d-1bb04f0edabb)
KUBirds_8_25_23
