### ISSUE TITLE
Consider using a flag in the metadata column of SPAppResource to indicate DwCA resources.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#489]
This would allow the UI to present a picklist of available definitions.

**Comment by benanhalt** [comment]
But, it's not clear how the flag would be set in the first place...

**Comment by maxxxxxdlp** [comment]
Fixed by replacing the text boxes for specifying app resource name with a visual app resource picker.

The app resource picker has default filters enabled that show only app resources with mimeType `text/xml` or no mimeType.

**Comment by benanhalt** [comment]
How does it know the difference between a DwCA definition and other xml resource?

**Comment by maxxxxxdlp** [comment]
It displays all app resources with mime type of `jrxml/label`, `jrxml/report`, `text/xml` or no mime type at all.

There is also a button on the screen to change the filters

**Comment by maxxxxxdlp** [comment]
The fix basically made UX better by displaying all app resources rather than showing a blank input box.
The app resources are shown as a tree (allowing you to collapse/uncollapse collections or filter them down)

**Comment by benanhalt** [comment]
I see. My intention with this issue was to add a flag in the metadata column of the appresource for DwCA and metadata definitions so that they could be distinguished from other resources.

I'm thinking that maybe the export related resources should just be moved into their own tables though. I originally used appresources because I was trying to avoid Specify 7 only tables at that time.

**Comment by maxxxxxdlp** [comment]
I see.

If the current solution does not work, I would be in favor of adding a new flag/special mime type rather than a new table.

The fact that there are `SpAppResource` tables and `SpViewSetObj` tables that share `SpAppResourceDir` and `SpAppResourceData` is adding quite a bit of complication on the front end (and I am not sure if a separate table was even required for storing form definitions).

**Comment by benanhalt** [comment]
The new tables would just store the relevant information for the exports directly rather than referring to the app resource tables.

**Comment by maxxxxxdlp** [comment]
But then we would need separate UI for editing them. There already is a lot of infrastructure for app resources

**Comment by benanhalt** [comment]
Yes. It would be part of an update for adding UI for defining the exports.

**Comment by benanhalt** [comment]
I mean, the intention is eventually to add UI to define the exports instead of editing the XML directly. As part of that change, they could be stored in their own table instead of as app resources.

**Comment by maxxxxxdlp** [comment]
I see.

So far my intention was to replace the editor with a UI when you open an app resource with a recognized mime type.

As a test run, this is already implemented on `testability` branch for the following app resources:
- `UserPreferences` - allows to edit user prefs for another user
- `DefaultUserPreferences` - allows to change the default user prefs for all users in scope

The form editor would also be implemented like that. Instead of displaying an XML file, it would show a list of view defs defined in the file with an option to open a UI for editing any of them.

Same goes for Data Obj Formatters, UI Formatters, WebLinks, TypeSearches, Remote Prefs, Global Prefs, DWCA exports and the rest.

The benefit of using app resource UI for this is that we get a lot of features for free:
- A side bar with a tree of all app resources and filtering
- Import/Export of resources
- The UI logic for handling record-level permissions would have to be implemented only once too, once we have a support for that
- Plus, the same back-end API is reused
