### ISSUE TITLE
Aggregator separator disappears when relationship table field mapped to query as (aggregated) 

### ISSUE THREAD

**Issue by bronwyncombs** [specify/specify7#5012]
**Describe the bug**
- I created a format for Collectors using the Agent Variant name and last name of the agent

<img width="949" alt="Screenshot 2024-06-17 at 1 36 29 PM" src="https://github.com/specify/specify7/assets/135047322/cf3f9d15-2436-4cf1-a0da-1cba84c23870">

- I defined an aggregator for the collectors with a separator value of `, ` 

<img width="949" alt="Screenshot 2024-06-17 at 1 36 38 PM" src="https://github.com/specify/specify7/assets/135047322/a4d91958-f5c8-4f2b-be0c-276c292d5c51">

- When querying, if `Agent > Variants > (aggregated)` is mapped along with `Collectors > (aggregated)`, the separating comma disappears from the aggregation.

<img width="1264" alt="Screenshot 2024-06-17 at 1 40 08 PM 1" src="https://github.com/specify/specify7/assets/135047322/e9830f9c-7ece-4567-8ef9-f6529bd309e1">

<img width="1264" alt="Screenshot 2024-06-17 at 1 40 25 PM" src="https://github.com/specify/specify7/assets/135047322/b871c8b2-e803-41b5-b4de-277b76cd6a87">

**Expected behavior**
Separator value should remain

- OS: macOS
- Browser: Chrome
- Specify 7 Version: v7.9.5
- Database Name: ohiomollusk
- Collection name: Bivalves
- User Name: testuser

**Reported By**
Name of your institution

**Additional context**
Database name or any other context about the problem here.

**Comment by realVinayak** [comment]
This bug happened bc the SEP variable name is not unique across the query. Looks like that has been fixed by sqlalchemy in at least version 1.3. That is, we can add a bindparam be unique. https://github.com/sqlalchemy/sqlalchemy/issues/4933. Alternatively, we could do still do without it (by storing a counter for sep label.

Updating to the latest version (2.0) might just be a nice thing to do anyways. Especially since we've some form of backend tests for query builder now

**Comment by emenslin** [comment]
Can recreate in edge (7.9.6)

**Comment by realVinayak** [comment]
Closing in favor of https://github.com/specify/specify7/issues/5164. I'll resolve this as part of this [branch](https://github.com/specify/specify7/tree/wb_improvements) since I updated SQLAlchemy to 1.three
