### ISSUE TITLE
`TimestampModified` not being updated when modifying records

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5108]
**Describe the bug**
When modifying an existing record, the `timestampModified` is not being updated.
This issue started in `v7.9.6` and was likely introduced due to the changes in https://github.com/specify/specify7/pull/4618

**To Reproduce**

1. Create a new record in any table that has a `timestampModified` field and save the record **or** find an existing record
3. Make modifications to the record
4. Save
5. See that the `timestampModified` value has not been changed

https://github.com/user-attachments/assets/ffe9acfa-3cf7-4149-b9f1-d73b2905acdb

**Expected behavior**
The `timestampModified` should be set to the current timestamp when changes are made.

**Reported By**
University of Kansas (Andy and Caleb)

Andy:
>Can indeed confirm that the record he mentions does not have an updated modified on date.  have also confirmed that this is happening in my database too.  I just edited record 1234 in my voucher collection and saved it and it still has a modified date of 10/17/2019.  Something is amiss!!

**Comment by melton-jason** [comment]
You are correct in that the bug was caused by https://github.com/specify/specify7/pull/4618. 

In that PR, the API was changed so that passing `timestampcreated` or `timestampmodified` values when creating or updating a resource will always result in the API overwriting the values of those fields to the value specified in the request. 

To fetch a resource, the frontend (and BackBone) GETs the resource and stores all attribute values of the resource in memory. 
When a POST or PUT request is sent to the backend, the resource is serialized (all attributes stored by the frontend ORM) and sent to the backend. 

In essence, the frontend is fetching the resource's attributes and passing those same values to the backend whenever the resource is saved. 
Because of the API changes, this results in no changes to the `timestampcreated` or `timestampmodified` fields.

**Comment by grantfitzsimmons** [comment]
**Whatever solution we make for the timestamp issue, we need to base it off of the [7962-hotfix](https://github.com/specify/specify7/tree/7962-hotfix) branch on GitHub.**

**Comment by emenslin** [comment]
Fixed
