### ISSUE TITLE
ALL Table Aggregation separators with a space ` ` at the end or beginning are ERASED after any changes to DataObjFormatters

### ISSUE THREAD

**Issue by alesan99** [specify/specify7#5154]
**Describe the bug**
If you make any changes to the Record Formatters file and save, all table aggregators with a separator set to "; " (A semicolon with a space after) will have the separator erased.
Apparently this has been happening for a while and multiple databases have been affected already.

The same separator works in table format however.

**To Reproduce**

1. Go to App Resources -> Record Formatters -> Table Aggregation
2. Edit Accession Agent Table Aggregation
3. Set the Separator to "; "
4. Close
5. Click Save
6. Go back to Accession Agent Table Aggregation
7. Check the Separator

**Expected behavior**
This separators should be supported as it is in Table Formats.

- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: edge (7.9.7), 7.9.6, 7.9.5, 7.9.4
- Database Name: kubirds & sp7demofish
- User Name: spbirdadmin

**Comment by grantfitzsimmons** [comment]
The severity of this issue is high, and a resolution should be issued urgently.

Consider this– we are losing the aggregation separator for **most tables** immediately upon saving any edits to the `DataObjFormatters` file. Upon examining Andy's database, this issue has already become a problem in the wild.

https://github.com/user-attachments/assets/b9980a31-1954-41a5-8bd7-56692533951e

We need to resolve ASAP.
