### ISSUE TITLE
Hide Collection Object Type

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5222]
Hide on the front-end so that users cannot access it easily until 7.9.8 when we can serve static files for it

**Comment by sharadsw** [comment]
Making a list of all places where it needs to be hidden. Let me know if I'm missing anything
- Data Entry tables list
- Schema Config tables list
- Schema config entry for COType under CollectionObject relationships
- Workbench base tables list
- Form definitions list

**Comment by melton-jason** [comment]
Did we want to hide the relationship in the QueryBuilder also?

**Comment by maxpatiiuk** [comment]
Given that this hiding is intended to be temporary, simply marking the field as hidden in front-end schema overrides might be better as it would be much easier to revert, rather than having to hunt down several places in the code

see https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/components/DataModel/schemaOverrides.ts#L97

it won't hide the field completely from the schema config, but I think that's ok since this is just temporary
