### ISSUE TITLE
`Multiple treedefitems found for rank Continent` when validating data set

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5313]
**Describe the bug**
This happens only in `v7.9.7` or later (incl. `production` as of https://github.com/specify/specify7/commit/92c94292c6d70fb867994d88ca503ea56572ea8f) . This does not happen in `v7.9.6.2`.

**To Reproduce**

1. Go to https://ojsmnh20241003wb-production.test.specifysystems.org/specify/workbench/254/ (`v7.9.7` or `production`), logged in as `spadmin` in the Ichthyology collection
2. Validate the data set
3. See the following error:
	```
	{
	  "uploaderstatus": {
	    "operation": "validating",
	    "taskid": "26f94f3b-f6e8-42a8-812e-1ba8e7e2775e"
	  },
	  "taskstatus": "FAILURE",
	  "taskinfo": "ValueError('Multiple treedefitems found for rank Continent')"
	}
	```
5. Go to https://ojsmnh20241003wb-v7962.test.specifysystems.org/specify/workbench/254/ (`v7.9.6.2`), logged in as `spadmin` in the Ichthyology collection
6. Validate the same data set
7. See no error

**Expected behavior**
This data set mapping is valid and should be validated without any issues.

**Screenshots**

https://github.com/user-attachments/assets/b970376a-a888-43f6-b906-f70fd1c7805b

**Crash Report**
macOS, Windows
db: `ojsmnh_2024_10_03_WB`
user: `spadmin`
collection: `Ichthyology`

**Reported By**
Paul at OJSMNH

**Comment by grantfitzsimmons** [comment]
<img width="952" alt="image" src="https://github.com/user-attachments/assets/9eb89a39-7e1d-4be6-8bdd-7309ba45e8eb">

Just as before, this happens only in v7.9.7 or later (incl. `production` as of https://github.com/specify/specify7/commit/92c94292c6d70fb867994d88ca503ea56572ea8f) . This does not happen in v7.9.6.2.

**Comment by acwhite211** [comment]
It looks like this issue is just due to duplicate Geography Trees in the database.

![image](https://github.com/user-attachments/assets/a38efded-df5b-4ab1-9431-6779ca692629)
![image](https://github.com/user-attachments/assets/b13f8ea4-b9a9-4548-9d03-8f4e5d434898)

Some databases have had this issue of duplicate trees for a while, probably best to just correct the data.  This is an issue for matching the rank by name, because of the duplicates.  We can either remove these duplicates or come up with some scheme in the code to not throw an error and try to figure out which of the duplicates should be used.
