### ISSUE TITLE
Add a "Bulk Append" feature to Batch Edit

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5329]
**Requested by:** [Corinna at CSIRO](https://app.asana.com/0/1201972579963460/1206651505534021/f)

> Over the past few weeks, we’ve had multiple conversations with staff from different collections who have all expressed a desire for a bulk append option for Notes fields in various tables (`collectionobject`, `determination`, `preparation`).
> 
> That is they have a requirement to add something to an already existing Note through batch edit, to avoid having to do manual updates for each and every record. Is this something that could be added as a requirement for the S7 Batch Edit functionality development?

They want to add text in bulk to the end of a remarks field. For example, they might have the phrase "collected in this way" and want to append it to the end of 100 Collecting Event remarks fields at once, without manually editing each row.

**Comment by realVinayak** [comment]
We support %s along with custom formatters in batch-edit, that's all is needed + supports a lot of cases where you need to get data from related tables in the formatter -- also, think about it, you don't even need to export to a CSV for it. You just need to copy data from the "formatted" column to the remarks column (because %s will handle append). The superset of this issue would be to allow reusing formatters multiple times in a query.
