### ISSUE TITLE
Add special `Consolidated` COG Interactions behavior

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#5422]
When collection transactions involve a Collection Object that is part of a COG—such as loans, accessions, deaccessions, gifts for determination, or relocation for exhibition—Specify will identify and present information on other cataloged Collection Objects belonging to that COG.

If the other Collection Objects are physically attached to the Collection Object being transacted, they will also be included in the management transaction. This feature allows the user to update the transaction status of all Collection Objects within the COG.

* This logic is only necessary when the COG Type is `Consolidated`; it does not apply in other cases, such as when it is `Discrete` or `Drill Core`.

---

### User Interface Components

Record sets of COGs should be usable as the basis for a transaction just as record sets of COs are. 

Users should also be able to enter a list of delimiter-separated COG names to guide their interactions:

<img width="300" alt="image" src="https://github.com/user-attachments/assets/586c9a06-9cef-4533-b39a-241870b24fa5">

All sections expanded:
<img width="300" alt="image" src="https://github.com/user-attachments/assets/c62b007b-561f-4e17-922e-5144f5025dad">

Once entered, all loanable preparations associated with COs in that COG should be displayed in the following menu.

### COG Identification and Display

-  A new column should be added to the "Preparations" dialog to display the formatted table record preview for the COG, in addition to Cat #, Taxon, Object Type, Select, Available, and Unavailable.
- If there is not a formatter defined for the COG table, use the ID from the database

### Error Handling and Validation

-  Prevent proceeding with incomplete transactions (e.g., preparations must be loaned together as they are consolidated).

### Returning Loans

- The "Return Loan" dialog should also display a column with the formatted COG record in it for reference
- When one preparation from the COG is selected for return, other preparations in that COG should be automatically selected as well

**Comment by CarolineDenis** [comment]
Flow decision: 
- Click Interaction side menu 
- Click loan 
- Open record set drop down : there is now CO RS and COG RS 
- No Enter COG name block, only usual enter Cat Num 
- Enter a cat num 
- Click next 
- Dialog with prep row open 
- Select a row
- Click apply 
- Backend check if the prep used is in a CO that is in COG that has a type Consolidate 
- Only if this is the case, all the preps attached to all the COs in that COG are also being added to the Loan 
   When the backend checks if the CO is a part of a consolidated COG, it will also check if that COG is itself a part of a consolidated COG, in summary will check all the preps associated with consolidated COG recursively 
- Land on the loan page, either only the selected prep have been added (if CO wasn't a part of a consolidated COG) or all related preps have been added with the selected one (because it was a part of a consolidate) 
- ! it is possible that the user selects 1 prep that is a part of a consolidated COG and one that is independent or a part of an other type of COG 
- When deleting a prep in the subview, the backend will now also check if the prep is part of a CO that is a part of a consolidated COG (need recursive check as well) 
- If yes than all related preps are deleted with the one 
! the preps that are not a part of the consolidated COG will not be deleted
