### ISSUE TITLE
Cannot edit childCO in a COG 

### ISSUE THREAD

**Issue by emenslin** [specify/specify7#5481]
**Describe the bug**
If you edit a CO through the children subview in a COG the save button is not enabled and you can't save, if you make a change to the COG form to enable the save button it throws an out of date error. This might already be an existing issue but I could not find it. 

**To Reproduce**

1. Go to COG
2. Add ChildCO 
3. Expand CO 
4. Edit a field 
5. See save is not enabled 
6. Change something on the COG form 
7. Save 
8. See error 

**Expected behavior**
You should be able to edit a CO in the COG form.

**Screenshots**

https://github.com/user-attachments/assets/097250ce-6922-4303-aa3f-28c50db0775f

**Crash Report**

[Specify 7 Crash Report - 2024-12-17T16_47_13.357Z.txt](https://github.com/user-attachments/files/18168818/Specify.7.Crash.Report.-.2024-12-17T16_47_13.357Z.txt)

Please fill out the following information manually:
- OS: Windows 11
- Browser: Chrome
- Specify 7 Version: production
- Database Name: ojsmnh
- Collection name: fossil invertebrates
- User Name: spadmin
- URL: https://ojsmnh20241003wb-production.test.specifysystems.org/specify/

**Comment by melton-jason** [comment]
This is ultimately because some part of `one-to-one` relationships are not being properly supported.  

More specifically in this case: the change/saverequired event in the CollectionObject is not being propagated up to the CollectionObjectGroupJoin and CollectionObjectGroup resources. 

This behavior is handled via the the event handlers in `resourceApi.ts`: 

(The following is set based on the type of relationship)
https://github.com/specify/specify7/blob/b69dac305cd93466a93b2dea773174df5f14524f/specifyweb/frontend/js_src/lib/components/DataModel/resourceApi.ts#L36-L87

https://github.com/specify/specify7/blob/b69dac305cd93466a93b2dea773174df5f14524f/specifyweb/frontend/js_src/lib/components/DataModel/resourceApi.ts#L141-L146

For which the `saverequired` event is caught by the `useIsModified` hook: 
https://github.com/specify/specify7/blob/b69dac305cd93466a93b2dea773174df5f14524f/specifyweb/frontend/js_src/lib/hooks/useIsModified.tsx#L9-L46

I imagine most of the work for this fix would be investigating why the event(s) are not being propagated: the actual change would likely be a very small one
