### ISSUE TITLE
'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#589]
![Screenshot from 2020-01-20 09-27-52](https://user-images.githubusercontent.com/40512816/72746595-557ac180-3b67-11ea-8f66-006e4f465b1d.png)

```
Internal Server Error: /api/specify/workbench/1/
Traceback (most recent call last):
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 22, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 43, in _cache_controlled
    response = viewfunc(request, *args, **kw)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 30, in wrapped
    return view(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/views.py", line 44, in view
    return dispatch_func(request, *args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/api.py", line 108, in resource_dispatch
    model, id, version, data)
  File "/home/specify/Downloads/specify7/specify7/ve/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/home/specify/Downloads/specify7/specifyweb/specify/api.py", line 532, in put_resource
    return update_obj(collection, agent, name, id, version, data)
  File "/home/specify/Downloads/specify7/specifyweb/specify/api.py", line 540, in update_obj
    fk_info = handle_fk_fields(collection, agent, obj, data, auditlog.isAuditingFlds())
  File "/home/specify/Downloads/specify7/specifyweb/specify/api.py", line 435, in handle_fk_fields
    parent_obj=obj)
  File "/home/specify/Downloads/specify7/specifyweb/specify/api.py", line 541, in update_obj
    dependents_to_delete = fk_info[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
[20/Jan/2020 11:27:38] "PUT /api/specify/workbench/1/ HTTP/1.1" 500 6999
```

Seems to happen every time for every kind of shema mapping
Even though the issue is shown, the dataset is created and the user can see it after the page reload
Error happens after the user has specified the name and the description for the new dataset and clicks the action button

**Comment by maxxxxxdlp** [comment]
Same error when changing user group for a user

**Comment by benanhalt** [comment]
This isn't happening for me. Need more details to reproduce. Which database and which branch of Specify 7?

**Comment by maxxxxxdlp** [comment]
All the bugs were found in `develop`s branch of Specify7 with a newly created Botany database with default settings

MySQL 5.7
Ubuntu 19.10
Amazon Corretto 8

I will try to reproduce it myself and will post more information later

**Comment by yvonneekanim** [comment]
I got it in TestFish when I try to save changes made to an existing record

TypeError at /api/specify/collectionobject/1/
'NoneType' object has no attribute '__getitem__'

Request Method: PUT
Request URL: http://db3.biwebdbtest.nhm.ku.edu/api/specify/collectionobject/1/?recordsetid=1
Django Version: 1.10.2
Python Executable: /usr/bin/python
Python Version: 2.7.15
Python Path: ['/home/anhalt/servers/db3/Specify7/virtualenv/lib/python2.7/site-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/home/anhalt/servers/db3', '/home/anhalt/servers/db3/Specify7']
Server time: Thu, 19 Mar 2020 10:34:45 -0500
Installed Applications:
('django.contrib.sessions',
 'django.contrib.staticfiles',
 'django.contrib.contenttypes',
 'django.contrib.auth',
 'specifyweb.specify',
 'specifyweb.stored_queries',
 'specifyweb.businessrules',
 'specifyweb.express_search',
 'specifyweb.context',
 'specifyweb.attachment_gw',
 'specifyweb.frontend',
 'specifyweb.barvis',
 'specifyweb.report_runner',
 'specifyweb.interactions',
 'specifyweb.workbench',
 'specifyweb.notifications',
 'specifyweb.export',
 'specifyweb.raven_placeholder')
Installed Middleware:
('django.middleware.gzip.GZipMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'specifyweb.context.middleware.ContextMiddleware')


Traceback:  

File "/home/anhalt/servers/db3/Specify7/virtualenv/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/home/anhalt/servers/db3/Specify7/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/anhalt/servers/db3/Specify7/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/anhalt/servers/db3/Specify7/virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/views.py" in wrapped
  22.             return view(request, *args, **kwargs)

File "/home/anhalt/servers/db3/Specify7/virtualenv/lib/python2.7/site-packages/django/views/decorators/cache.py" in _cache_controlled
  43.             response = viewfunc(request, *args, **kw)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/views.py" in wrapped
  30.         return view(request, *args, **kwargs)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/views.py" in view
  44.             return dispatch_func(request, *args, **kwargs)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/api.py" in resource_dispatch
  108.                            model, id, version, data)

File "/home/anhalt/servers/db3/Specify7/virtualenv/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/api.py" in put_resource
  557.     return update_obj(collection, agent, name, id, version, data)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/api.py" in update_obj
  581.     handle_to_many(collection, agent, obj, data)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/api.py" in handle_to_many
  515.                                      parent_obj=obj)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/api.py" in update_obj
  578.     auditlog.update(obj, agent, parent_obj, dirty)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/auditlog.py" in update
  45.         self.log_action(auditcodes.UPDATE, obj, agent, parent_record, dirty_flds)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/auditlog.py" in log_action
  51.                 self._log_fld_update(vals, log_obj, agent)

File "/home/anhalt/servers/db3/Specify7/specifyweb/specify/auditlog.py" in _log_fld_update
  107.             oldvalue=vals['old_value'][:(2**16 - 1)],

Exception Type: TypeError at /api/specify/collectionobject/1/
Exception Value: 'NoneType' object has no attribute '__getitem__'
Request information:
USER: Specifyuser object

GET:
recordsetid = u'1'

POST: No POST data

FILES: No FILES data

COOKIES:
_cap = '1686113821547053371'
__unam = '757257a-168a5177e57-1911c903-6'
_ga = 'GA1.2.1938695282.1547053370'
sessionid = '4bqzypvql9kie85ephnwgihol04ivpih'
collection = '4'
affiliation = 'undergraduate-student'
https%3a%2f%2fhr.ku.edu%2fpsp%2fhrprd%2femployee%2fhrms%2frefresh = 'list:%20%3Ftab%3Dremoteunifieddashboard%7C%3Frp%3Dremoteunifieddashboard'
_gid = 'GA1.2.961742964.1584626339'
csrftoken = 'KqWyNpaTPrmNkjvUQDevYYC9gvApLPfzQutDYcgXx2LJ8AwslEYaRJVzXFEgll0I'
A-8080-PORTAL-PSJSESSIONID = 'QSbzFxd99IZiEOx4gxpoem_TqDlAfKGx!1134786716'

META:
CONTENT_LENGTH = '4272'
CONTENT_TYPE = 'application/json'
CONTEXT_DOCUMENT_ROOT = '/var/www/html'
CONTEXT_PREFIX = ''
CSRF_COOKIE = 'KqWyNpaTPrmNkjvUQDevYYC9gvApLPfzQutDYcgXx2LJ8AwslEYaRJVzXFEgll0I'
DOCUMENT_ROOT = '/var/www/html'
GATEWAY_INTERFACE = 'CGI/1.1'
HTTP_ACCEPT = 'application/json, text/javascript, */*; q=0.01'
HTTP_ACCEPT_ENCODING = 'gzip, deflate'
HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.9'
HTTP_CONNECTION = 'keep-alive'
HTTP_COOKIE = '_ga=GA1.2.1938695282.1547053370; _cap=1686113821547053371; collection=4; affiliation=undergraduate-student; __unam=757257a-168a5177e57-1911c903-6; _gid=GA1.2.961742964.1584626339; A-8080-PORTAL-PSJSESSIONID=QSbzFxd99IZiEOx4gxpoem_TqDlAfKGx!1134786716; https%3a%2f%2fhr.ku.edu%2fpsp%2fhrprd%2femployee%2fhrms%2frefresh=list:%20%3Ftab%3Dremoteunifieddashboard%7C%3Frp%3Dremoteunifieddashboard; csrftoken=KqWyNpaTPrmNkjvUQDevYYC9gvApLPfzQutDYcgXx2LJ8AwslEYaRJVzXFEgll0I; sessionid=4bqzypvql9kie85ephnwgihol04ivpih'
HTTP_HOST = 'db3.biwebdbtest.nhm.ku.edu'
HTTP_ORIGIN = 'http://db3.biwebdbtest.nhm.ku.edu'
HTTP_REFERER = 'http://db3.biwebdbtest.nhm.ku.edu/specify/view/collectionobject/1/?recordsetid=1'
HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36'
HTTP_X_CSRFTOKEN = 'KqWyNpaTPrmNkjvUQDevYYC9gvApLPfzQutDYcgXx2LJ8AwslEYaRJVzXFEgll0I'
HTTP_X_REQUESTED_WITH = 'XMLHttpRequest'
PATH_INFO = u'/api/specify/collectionobject/1/'
PATH_TRANSLATED = '/home/anhalt/servers/db3/specify.wsgi/api/specify/collectionobject/1/'
QUERY_STRING = 'recordsetid=1'
REMOTE_ADDR = '129.237.183.35'
REMOTE_PORT = '49917'
REQUEST_METHOD = 'PUT'
REQUEST_SCHEME = 'http'
REQUEST_URI = '/api/specify/collectionobject/1/?recordsetid=1'
SCRIPT_FILENAME = '/home/anhalt/servers/db3/specify.wsgi'
SCRIPT_NAME = u''
SERVER_ADDR = '10.101.225.56'
SERVER_ADMIN = '[no address given]'
SERVER_NAME = 'db3.biwebdbtest.nhm.ku.edu'
SERVER_PORT = '80'
SERVER_PROTOCOL = 'HTTP/1.1'
SERVER_SIGNATURE = '<address>Apache/2.4.29 (Ubuntu) Server at db3.biwebdbtest.nhm.ku.edu Port 80</address>\n'
SERVER_SOFTWARE = 'Apache/2.4.29 (Ubuntu)'
apache.version = 
mod_wsgi.application_group = 'db3.biwebdbtest.nhm.ku.edu|'
mod_wsgi.callable_object = 'application'
mod_wsgi.daemon_connects = '1'
mod_wsgi.daemon_restarts = '0'
mod_wsgi.daemon_start = '1584632084709410'
mod_wsgi.enable_sendfile = '0'
mod_wsgi.handler_script = ''
mod_wsgi.ignore_activity = '0'
mod_wsgi.listener_host = ''
mod_wsgi.listener_port = '80'
mod_wsgi.path_info = '/api/specify/collectionobject/1/'
mod_wsgi.process_group = 'db3'
mod_wsgi.queue_start = '1584632084709220'
mod_wsgi.request_handler = 'wsgi-script'
mod_wsgi.request_id = 'Yz6C6JbRXaY'
mod_wsgi.request_start = '1584632084708963'
mod_wsgi.script_name = ''
mod_wsgi.script_reloading = '1'
mod_wsgi.script_start = '1584632084709494'
mod_wsgi.thread_id = 7
mod_wsgi.thread_requests = 26L
mod_wsgi.total_requests = 127L
mod_wsgi.version = 
wsgi.errors = <mod_wsgi.Log object at 0x7f3563cb7350>
wsgi.file_wrapper = ''
wsgi.input = <mod_wsgi.Input object at 0x7f3563c25180>
wsgi.multiprocess = False
wsgi.multithread = True
wsgi.run_once = False
wsgi.url_scheme = 'http'
wsgi.version = 

Settings:
Using settings module specifyweb.settings
ABSOLUTE_URL_OVERRIDES = {}
ADMINS = 
ADMIN_MEDIA_PREFIX = '/static/admin/'
ALLOWED_HOSTS = ['*']
ALLOW_SPECIFY6_PASSWORDS = u'********************'
ALLOW_SUPPORT_LOGIN = True
ANONYMOUS_USER = None
APPEND_SLASH = True
AUTHENTICATION_BACKENDS = ['specifyweb.specify.support_login.SupportLoginBackend', 'django.contrib.auth.backends.ModelBackend']
AUTH_LDAP_SERVER_URI = None
AUTH_PASSWORD_VALIDATORS = u'********************'
AUTH_USER_MODEL = 'specify.Specifyuser'
CACHES = {u'default': {u'BACKEND': u'django.core.cache.backends.locmem.LocMemCache'}}
CACHE_MIDDLEWARE_ALIAS = u'default'
CACHE_MIDDLEWARE_KEY_PREFIX = u'********************'
CACHE_MIDDLEWARE_SECONDS = 600
CSRF_COOKIE_AGE = 31449600
CSRF_COOKIE_DOMAIN = None
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_NAME = u'csrftoken'
CSRF_COOKIE_PATH = u'/'
CSRF_COOKIE_SECURE = False
CSRF_FAILURE_VIEW = u'django.views.csrf.csrf_failure'
CSRF_HEADER_NAME = u'HTTP_X_CSRFTOKEN'
CSRF_TRUSTED_ORIGINS = []
DATABASES = {'default': {'ENGINE': 'specifyweb.hibernateboolsbackend.backends.mysql', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': u'TestFish', 'CONN_MAX_AGE': 0, 'TIME_ZONE': None, 'PORT': '', 'HOST': 'localhost', 'USER': 'MasterUser', 'TEST': {'COLLATION': None, 'CHARSET': None, 'NAME': None, 'MIRROR': None}, 'PASSWORD': u'********************', 'OPTIONS': {}}}
DATABASE_HOST = 'localhost'
DATABASE_NAME = u'TestFish'
DATABASE_PORT = ''
DATABASE_ROUTERS = []
DATA_UPLOAD_MAX_MEMORY_SIZE = 2621440
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000
DATETIME_FORMAT = u'N j, Y, P'
DATETIME_INPUT_FORMATS = [u'%Y-%m-%d %H:%M:%S', u'%Y-%m-%d %H:%M:%S.%f', u'%Y-%m-%d %H:%M', u'%Y-%m-%d', u'%m/%d/%Y %H:%M:%S', u'%m/%d/%Y %H:%M:%S.%f', u'%m/%d/%Y %H:%M', u'%m/%d/%Y', u'%m/%d/%y %H:%M:%S', u'%m/%d/%y %H:%M:%S.%f', u'%m/%d/%y %H:%M', u'%m/%d/%y']
DATE_FORMAT = u'N j, Y'
DATE_INPUT_FORMATS = [u'%Y-%m-%d', u'%m/%d/%Y', u'%m/%d/%y', u'%b %d %Y', u'%b %d, %Y', u'%d %b %Y', u'%d %b, %Y', u'%B %d %Y', u'%B %d, %Y', u'%d %B %Y', u'%d %B, %Y']
DEBUG = True
DEBUG_PROPAGATE_EXCEPTIONS = False
DECIMAL_SEPARATOR = u'.'
DEFAULT_CHARSET = u'utf-8'
DEFAULT_CONTENT_TYPE = u'text/html'
DEFAULT_EXCEPTION_REPORTER_FILTER = u'django.views.debug.SafeExceptionReporterFilter'
DEFAULT_FILE_STORAGE = u'django.core.files.storage.FileSystemStorage'
DEFAULT_FROM_EMAIL = u'webmaster@localhost'
DEFAULT_INDEX_TABLESPACE = u''
DEFAULT_TABLESPACE = u''
DEPOSITORY_DIR = '/home/anhalt/specify-depository'
DISALLOWED_USER_AGENTS = []
EMAIL_BACKEND = u'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = u'localhost'
EMAIL_HOST_PASSWORD = u'********************'
EMAIL_HOST_USER = u''
EMAIL_PORT = 25
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = u'********************'
EMAIL_SUBJECT_PREFIX = u'[Django] '
EMAIL_TIMEOUT = None
EMAIL_USE_SSL = False
EMAIL_USE_TLS = False
FILE_CHARSET = u'utf-8'
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None
FILE_UPLOAD_HANDLERS = [u'django.core.files.uploadhandler.MemoryFileUploadHandler', u'django.core.files.uploadhandler.TemporaryFileUploadHandler']
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
FILE_UPLOAD_PERMISSIONS = None
FILE_UPLOAD_TEMP_DIR = None
FIRST_DAY_OF_WEEK = 0
FIXTURE_DIRS = []
FORCE_SCRIPT_NAME = None
FORMAT_MODULE_PATH = None
IGNORABLE_404_URLS = []
INSTALLED_APPS = 
INTERNAL_IPS = []
JAVA_PATH = '/usr/bin/java'
LANGUAGES = [(u'af', u'Afrikaans'), (u'ar', u'Arabic'), (u'ast', u'Asturian'), (u'az', u'Azerbaijani'), (u'bg', u'Bulgarian'), (u'be', u'Belarusian'), (u'bn', u'Bengali'), (u'br', u'Breton'), (u'bs', u'Bosnian'), (u'ca', u'Catalan'), (u'cs', u'Czech'), (u'cy', u'Welsh'), (u'da', u'Danish'), (u'de', u'German'), (u'dsb', u'Lower Sorbian'), (u'el', u'Greek'), (u'en', u'English'), (u'en-au', u'Australian English'), (u'en-gb', u'British English'), (u'eo', u'Esperanto'), (u'es', u'Spanish'), (u'es-ar', u'Argentinian Spanish'), (u'es-co', u'Colombian Spanish'), (u'es-mx', u'Mexican Spanish'), (u'es-ni', u'Nicaraguan Spanish'), (u'es-ve', u'Venezuelan Spanish'), (u'et', u'Estonian'), (u'eu', u'Basque'), (u'fa', u'Persian'), (u'fi', u'Finnish'), (u'fr', u'French'), (u'fy', u'Frisian'), (u'ga', u'Irish'), (u'gd', u'Scottish Gaelic'), (u'gl', u'Galician'), (u'he', u'Hebrew'), (u'hi', u'Hindi'), (u'hr', u'Croatian'), (u'hsb', u'Upper Sorbian'), (u'hu', u'Hungarian'), (u'ia', u'Interlingua'), (u'id', u'Indonesian'), (u'io', u'Ido'), (u'is', u'Icelandic'), (u'it', u'Italian'), (u'ja', u'Japanese'), (u'ka', u'Georgian'), (u'kk', u'Kazakh'), (u'km', u'Khmer'), (u'kn', u'Kannada'), (u'ko', u'Korean'), (u'lb', u'Luxembourgish'), (u'lt', u'Lithuanian'), (u'lv', u'Latvian'), (u'mk', u'Macedonian'), (u'ml', u'Malayalam'), (u'mn', u'Mongolian'), (u'mr', u'Marathi'), (u'my', u'Burmese'), (u'nb', u'Norwegian Bokm\xe5l'), (u'ne', u'Nepali'), (u'nl', u'Dutch'), (u'nn', u'Norwegian Nynorsk'), (u'os', u'Ossetic'), (u'pa', u'Punjabi'), (u'pl', u'Polish'), (u'pt', u'Portuguese'), (u'pt-br', u'Brazilian Portuguese'), (u'ro', u'Romanian'), (u'ru', u'Russian'), (u'sk', u'Slovak'), (u'sl', u'Slovenian'), (u'sq', u'Albanian'), (u'sr', u'Serbian'), (u'sr-latn', u'Serbian Latin'), (u'sv', u'Swedish'), (u'sw', u'Swahili'), (u'ta', u'Tamil'), (u'te', u'Telugu'), (u'th', u'Thai'), (u'tr', u'Turkish'), (u'tt', u'Tatar'), (u'udm', u'Udmurt'), (u'uk', u'Ukrainian'), (u'ur', u'Urdu'), (u'vi', u'Vietnamese'), (u'zh-hans', u'Simplified Chinese'), (u'zh-hant', u'Traditional Chinese')]
LANGUAGES_BIDI = [u'he', u'ar', u'fa', u'ur']
LANGUAGE_CODE = 'en-us'
LANGUAGE_COOKIE_AGE = None
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_NAME = u'django_language'
LANGUAGE_COOKIE_PATH = u'/'
LOCALE_PATHS = []
LOGGING = {'loggers': {'specifyweb': {'handlers': ['logfile'], 'propagate': True, 'level': 'DEBUG'}, 'django.request': {'handlers': ['mail_admins', 'logfile'], 'propagate': True, 'level': 'DEBUG'}}, 'disable_existing_loggers': True, 'handlers': {'logfile': {'backupCount': 10, 'level': 'DEBUG', 'filename': u'/home/anhalt/logs/TestFish.log', 'formatter': 'standard', 'class': 'logging.handlers.RotatingFileHandler', 'maxBytes': 1048576}, 'console': {'class': 'logging.StreamHandler', 'level': 'DEBUG'}, 'mail_admins': {'class': 'django.utils.log.AdminEmailHandler', 'filters': ['require_debug_false'], 'level': 'ERROR'}}, 'formatters': {'standard': {'datefmt': '%d/%b/%Y %H:%M:%S', 'format': '[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)s] %(message)s'}}, 'version': 1, 'filters': {'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'}}}
LOGGING_CONFIG = u'logging.config.dictConfig'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = u'/accounts/login/'
LOGOUT_REDIRECT_URL = None
MANAGERS = 
MASTER_NAME = 'MasterUser'
MASTER_PASSWORD = u'********************'
MEDIA_ROOT = ''
MEDIA_URL = ''
MESSAGE_STORAGE = u'django.contrib.messages.storage.fallback.FallbackStorage'
MIDDLEWARE = None
MIDDLEWARE_CLASSES = 
MIGRATION_MODULES = {}
MONTH_DAY_FORMAT = u'F j'
NOTIFICATION_TTL_DAYS = 7
NUMBER_GROUPING = 0
PASSWORD_HASHERS = u'********************'
PASSWORD_RESET_TIMEOUT_DAYS = u'********************'
PREPEND_WWW = False
RAVEN_CONFIG = None
REPORT_RUNNER_HOST = 'localhost'
REPORT_RUNNER_PORT = '9999'
ROOT_URLCONF = 'specifyweb.urls'
RO_MODE = False
SA_DATABASE_URL = u'mysql://MasterUser:MasterPassword@localhost:3306/TestFish?charset=utf8'
SA_POOL_RECYCLE = 3600
SCHEMA_LANGUAGE = 'en'
SECRET_KEY = u'********************'
SECURE_BROWSER_XSS_FILTER = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_SECONDS = 0
SECURE_PROXY_SSL_HEADER = None
SECURE_REDIRECT_EXEMPT = []
SECURE_SSL_HOST = None
SECURE_SSL_REDIRECT = False
SERVER_EMAIL = u'root@localhost'
SESSION_CACHE_ALIAS = u'default'
SESSION_COOKIE_AGE = 1209600
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_NAME = u'sessionid'
SESSION_COOKIE_PATH = u'/'
SESSION_COOKIE_SECURE = False
SESSION_ENGINE = 'django.contrib.sessions.backends.file'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_FILE_PATH = None
SESSION_SAVE_EVERY_REQUEST = False
SESSION_SERIALIZER = u'django.contrib.sessions.serializers.JSONSerializer'
SETTINGS_MODULE = 'specifyweb.settings'
SHORT_DATETIME_FORMAT = u'm/d/Y P'
SHORT_DATE_FORMAT = u'm/d/Y'
SIGNING_BACKEND = u'django.core.signing.TimestampSigner'
SILENCED_SYSTEM_CHECKS = []
SITE_ID = 1
SPECIFY_CONFIG_DIR = '/home/anhalt/servers/db3/Specify6/config'
SPECIFY_THICK_CLIENT = '/home/anhalt/servers/db3/Specify6'
STATICFILES_DIRS = ('config', '/home/anhalt/servers/db3/Specify6/config')
STATICFILES_FINDERS = 
STATICFILES_STORAGE = u'django.contrib.staticfiles.storage.StaticFilesStorage'
STATIC_ROOT = ''
STATIC_URL = '/static/'
STATS_URL = None
SUPPORT_LOGIN_TTL = 300
TEMPLATES = [{'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.contrib.auth.context_processors.auth', 'django.template.context_processors.debug', 'django.template.context_processors.i18n', 'django.template.context_processors.media', 'django.template.context_processors.static', 'django.template.context_processors.tz', 'django.contrib.messages.context_processors.messages']}, 'BACKEND': 'django.template.backends.django.DjangoTemplates'}]
TESTING = False
TESTING_DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': 'specifytest', 'HOST': '127.0.0.1', 'USER': 'Master', 'PASSWORD': u'********************', 'PORT': '3307'}}
TEST_NON_SERIALIZED_APPS = []
TEST_RUNNER = u'django.test.runner.DiscoverRunner'
THICK_CLIENT_LOCATION = '/home/anhalt/servers/db3/Specify6'
THOUSAND_SEPARATOR = u','
TIME_FORMAT = u'P'
TIME_INPUT_FORMATS = [u'%H:%M:%S', u'%H:%M:%S.%f', u'%H:%M']
TIME_ZONE = 'America/Chicago'
USE_ETAGS = False
USE_I18N = True
USE_L10N = True
USE_THOUSAND_SEPARATOR = False
USE_TZ = False
USE_X_FORWARDED_HOST = False
USE_X_FORWARDED_PORT = False
VERSION = 'v7.3.1-74-g9c28b822(debug)'
WB_UPLOAD_LOG_DIR = '/home/anhalt/wbuploadlog'
WEB_ATTACHMENT_COLLECTION = 'KUFishvoucher'
WEB_ATTACHMENT_KEY = u'********************'
WEB_ATTACHMENT_REQUIRES_KEY_FOR_GET = u'********************'
WEB_ATTACHMENT_URL = None
WSGI_APPLICATION = None
X_FRAME_OPTIONS = u'SAMEORIGIN'
YEAR_MONTH_FORMAT = u'F Y'


You're seeing this error because you have DEBUG = True in your
Django settings file. Change that to False, and Django will
display a standard page generated by the handler for this status code.

**Comment by yvonneekanim** [comment]
I'm no longer getting the error

**Comment by timo11** [comment]
Also needed to check for None to avoid 'None' being inserted in auditlogfield recs instead of NULL. See #538.
