### ISSUE TITLE
User can open `Interactions` and `Forms` windows at the same time

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#593]
![Screenshot from 2020-01-21 07-13-14](https://user-images.githubusercontent.com/40512816/72817898-65ee7300-3c1f-11ea-974c-061e52630623.png)

Even though this should not be possible, user is able to open both `Interactions` and `Forms` selection windows at the same time

**Comment by benanhalt** [comment]
How did you get this to happen? For me both dialogs are modal, so as soon as one opens it is impossible to open the other.

**Comment by maxxxxxdlp** [comment]
Specify7 was laggy. I clicked on one button, with no response. Then another, with no response. After a while website, unfroze and both menus were open

I guess you can check manually whether one of those windows is open, so as not to open another one in such case

**Comment by benanhalt** [comment]
I think the underlying issue of the dialog lagging is the key. I've noticed that lag in the Data Entry task. I'm pretty sure it is because there is a complicated process to figure out which forms are actually available. The UI should probably be changed to immediately open the dialog with a loading message, and then populate it once the available forms are known.
