### ISSUE TITLE
Reduce salience of delete button.

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#642]

**Comment by benanhalt** [comment]
What say ye to the following form button designs? The save buttons are placed on the left, and the delete button is demoted to a link.

![Screenshot_2020-03-26_16-02-14](https://user-images.githubusercontent.com/287254/77696529-861e1380-6f7b-11ea-9f69-3a3461b58e6f.png)
![Screenshot_2020-03-26_16-02-38](https://user-images.githubusercontent.com/287254/77696534-89b19a80-6f7b-11ea-85bf-b875282b0950.png)
![Screenshot_2020-03-26_16-03-26](https://user-images.githubusercontent.com/287254/77696543-8cac8b00-6f7b-11ea-981b-e63bd165328e.png)

**Comment by norinespears** [comment]
I like keeping the Save button on the right but like where you are going with the delete button as a link.

**Comment by benanhalt** [comment]
My cursory googling of form design best practices suggests primary buttons should go on the left. But it doesn't really matter to me. :man_shrugging: 
https://adamsilver.io/articles/where-to-put-buttons-on-forms/

**Comment by norinespears** [comment]
I see where they are going - but their samples are all single-column forms far less complicated than ours - more comparable to a sign-up on a website. I think it may have immediately felt strange to me because it is different than what I am used to using -- Github for instance (see below the next comment box) or the attached in Insightly. Hmmm, hard to find other examples because many things are save-as-you-go with no 'save' button intact; Asana for instance. That's my 2 cents!
<img width="844" alt="Screen Shot 2020-03-26 at 4 19 29 PM" src="https://user-images.githubusercontent.com/61208178/77698242-4a387d80-6f7e-11ea-8721-10775ff029fe.png">

**Comment by benanhalt** [comment]
How about:
![Screenshot_2020-03-26_16-35-30](https://user-images.githubusercontent.com/287254/77699154-da2af700-6f7f-11ea-8058-6a64a0c3b3c5.png)

**Comment by norinespears** [comment]
That is what I had pictured in my head when Jim suggested moving it to the left -- but hopefully others will chime in with their opinions. 
Many thanks for your quick work on this!

**Comment by beach53** [comment]
Most likely action button to my mind should be large and located to the right bottom. (And maybe also on the right top so that people who just need to work with the top of the form do not need to scroll down to save.  That's a very handl placement, I have used it many times in another forms based web app. I hate the delete button on the right and save on the left, I can't think of anything more repulsive in terms of interaction design.  I would fight that one to my last Covid-19 breath.

**Comment by beach53** [comment]
Hold on, I am re-thinking this dying breath thing ...

**Comment by beach53** [comment]
![ngp form layout](https://user-images.githubusercontent.com/10891506/77699974-56720a00-6f81-11ea-9cb9-529db8607f6f.jpg)

This app uses the lower left corner as Ben has suggested for the main action.  Then the delete is at the lower right as a link not a button (less attractive), and the cancel is a link too, to the right of the Update button in the lower left corner.  I've used this app a lot for the last five years, and I have to say that I dont find it visually easier to find the button in the lower left to click on it.  I have a preference personally for the lower right corner for the main (likely) action.  So I am 65% for the lower right for SAVE and 35% for DELETE as a link.  Because we have the SAVE button in the lower right now, I wonder if it would be less disruptive to our trained users to leave it there and to move Delete as  link to the left.

**Comment by norinespears** [comment]
I like that app, but when was it last updated? BUT - point taken, you can find examples of both.

Sometimes what is right is what people are used to. Those in new territory working at home may appreciate the buttons in Sp 7 being in the same place as Sp 6 (the rule of least astonishment?)

**Comment by yvonneekanim** [comment]
The delete button isn't consistent. Sometimes it shows up as '*Delete' and other times just 'Delete'. It seems to be completely random

**Comment by benanhalt** [comment]
The asterisk indicates the record can't be deleted because other records are referencing it. If you click on it when there is an asterisk, you will get a dialog listing those references. Not sure that is the best way to do it, but that is how it works.

**Comment by norinespears** [comment]
Alison sent a screenshot of what she was referencing -- it is different than the forms we were discussing
![pastedImagebase640](https://user-images.githubusercontent.com/61208178/77959198-d1963180-729b-11ea-966c-d1d04cb59683.png)
, but I think still relevant.
