### ISSUE TITLE
User is asked to save query changes when no changes where made

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#687]
Similar to #570

Pressing the `Create KML` button makes it think that I made some changes. After that, generating a new record set or going to any other page would trigger this window

![Screen Shot 2020-06-25 at 2 41 57 PM](https://user-images.githubusercontent.com/40512816/85713502-0fde9980-b6af-11ea-99df-aa7b2c695d80.png)

**Comment by maxxxxxdlp** [comment]
Does not happen for "Create CSV"
Seems to happen because of this line: https://github.com/specify/specify7/blob/cd9890a040b72bb830dc691cba7c56cdda95920b/specifyweb/frontend/js_src/lib/querytask.js#L241

**Comment by benanhalt** [comment]
In this case it seems like the `captions` attribute is getting set on the query object just so it gets serialized and sent to the server. Rather than silencing the change event on the query, I would change the request at https://github.com/specify/specify7/blob/cd9890a040b72bb830dc691cba7c56cdda95920b/specifyweb/frontend/js_src/lib/querytask.js#L245 to serialize the query first and then add the captions data to that. Something like:
```
const data = query.toJSON();
data.captions = captions;
$.post(postUrl, JSON.stringify(data));
```
