### ISSUE TITLE
'Division' field name and picklist items missing 

### ISSUE THREAD

**Issue by yvonneekanim** [specify/specify7#735]
The division field caption and information in accession form doesn't show up
![Screenshot (134)](https://user-images.githubusercontent.com/28809154/94735377-48d27e00-0330-11eb-827f-8727a54f4663.png)

**Comment by maxxxxxdlp** [comment]
Seems like a forms issue

**Comment by benanhalt** [comment]
It's not a forms issue.There the division picklist is a special case that hasn't been implemented.

**Comment by maxxxxxdlp** [comment]
Added a special case for DivisionCBX in daed12a4
@benanhalt though, that did not fix the missing field label issue. Does that case have to be handled in localizeform.js?

It seems to be set to ` ` (whitespace) in the form definition
![Screen Shot 2021-08-02 at 6 57 16 PM](https://user-images.githubusercontent.com/40512816/127890073-95059ba1-8a84-4416-8e54-ba439a3d906a.png)

**Comment by benanhalt** [comment]
Yes. It seems there will need to be a special case in localizeform.js. It should detect the cell id being `divLabel` and in that case it should use the localized name of the division table. 

This is based on the Specify 6 code at https://github.com/specify/specify6/blob/fd30b3f64c0faab9a4fcc5c45eebc5cb61905920/src/edu/ku/brc/specify/datamodel/busrules/AccessionBusRules.java#L225-L229

**Comment by benanhalt** [comment]
It should probably also check that it is localizing an Accession form so that it doesn't mess up if someone uses "divLabel" on a different form. I would do the special case at https://github.com/specify/specify7/blob/production/specifyweb/frontend/js_src/lib/localizeform.js#L35. The variable `model which is in scope at that point should allow it determine if it is doing an Accession form.

**Comment by maxxxxxdlp** [comment]
I am not sure I quite get it. Where do I get the current cell name from? The label at [this](https://github.com/specify/specify7/blob/aa7d05cab7b418db3a802285d23f90b1acf7d175/specifyweb/frontend/js_src/lib/localizeform.js#L29) line is equal to `<label> </label>` (doesn't have a `for` prop). And then it returns at [this](https://github.com/specify/specify7/blob/aa7d05cab7b418db3a802285d23f90b1acf7d175/specifyweb/frontend/js_src/lib/localizeform.js#L33) line.

I only have access to the `cell` variable at [this](https://github.com/specify/specify7/blob/daed12a4d390b6dfc50af5376e3334d1fe5a3e7d/specifyweb/frontend/js_src/lib/specifyformcells.js#L48) point. Though, there is no way of getting the table name here

**Comment by benanhalt** [comment]
Okay. I see what you mean. In specifyformcells.js you need to add a property to the <label> element it is creating to hold the id attribute from the cell element from the form definition. I would use something like `data-specify-label-id` rather than `id`. Then you will be able to inspect that attribute in localizeform.js to see if it is equal to "divLabel" and if model is an Accession object. As for the early return because the label has text. Change the test to check if the text is all white space. That way the label can still be hard coded in the form definition.

**Comment by maxxxxxdlp** [comment]
Fixed in 50eab0d9
Ready for testing on the `issue-735` branch
