### ISSUE TITLE
Adding preparation on CO form creates a popup

### ISSUE THREAD

**Issue by drew-wallace** [specify/specify7#74]
I'm not sure why it does, since the form is on the main CO page anyway.

Also, if you cancel out of the popup, you can't delete the prep you added. If you try and save it gives an error.

**Comment by benanhalt** [comment]
It has to open a dialog for editing items in a grid view because the full form can be different than what is shown in the grid.

To remove a prep (or other item in a grid view) you have to edit the item with the pencil icon and choose *remove*. Maybe there should be a trash icon, too, but that might litter up the UI too much. IDK.

The error is `Cannot assign None: "Preparation.preptype" does not allow null values.` due to the prep type being left blank, meaning there is a bug in the validation system not recognizing that value as required.

**Comment by benanhalt** [comment]
I separated the validation bug into a new issue and will leave this issue as a design question as to whether the UI can be improved.

**Comment by benanhalt** [comment]
This is addressed with the redesign merge: bcbc32f7f7bf493eb8405fdcf72b4d22e1ecc966. Editing items in grid format no longer opens a new dialog.

**Comment by garrettgirard** [comment]
As been mentioned in the fix, this isn't really an issue anymore because with the new design, there isn't a popup for the subform, it just has an expand/collapse option.
