### ISSUE TITLE
Saving LARGE app resources causes exception due to auditing. (`"Data too long for column 'NewValue' at row 1"`)

### ISSUE THREAD

**Issue by benanhalt** [specify/specify7#829]
Issue #632 was fixed by truncating field values when saving them to the audit log. But the issue reoccurred when trying to save changes to a form that involved adding a unicode character. I suspect the truncation which is done in Python is counting the characters while the MySQL field limit is on the number of bytes. Since a unicode character can consist of multiple bytes the truncated value can still exceed the field size.

**Comment by benanhalt** [comment]
Here is the form that couldn't be saved.
[badform.xml.txt](https://github.com/specify/specify7/files/6511198/badform.xml.txt)

**Comment by grantfitzsimmons** [comment]
Still an issue. Reported by MCNB when editing large forms.

**Workaround:**
1. Delete the form app resource
2. Create a new one
3. Load the data
4. Save (no error, since it doesn't save the data to the audit log)
5. 
[Too_Big_invert_views.xml.zip](https://github.com/specify/specify7/files/14088116/Too_Big_invert_views.xml.zip)

**Comment by specifysoftware** [comment]
This issue has been mentioned on **Specify Community Forum**. There might be relevant details there:

https://discourse.specifysoftware.org/t/specify7-crashes-with-certain-edits-to-preparation-type-subview-def/1579/2
