### ISSUE TITLE
Prep Type filling in automatically with the first item in the prep type pick list

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#832]
When the prep subform is activated, it automatically fills in prep type with the first entry in the prep type pick list.
It should only fill in automatically if there is only one value in the pick list.
https://github.com/specify/specify7/issues/360

**Comment by norinespears** [comment]
Many have mentioned this, including Edinburgh

**Comment by beach53** [comment]
Seems EZ enough to leave the field blank

**Comment by norinespears** [comment]
Ben: if it is a required field there is no empty option so it has an automatic default

**Comment by norinespears** [comment]
Research: what happens to databases that already have a null value included?

**Comment by norinespears** [comment]
Decision - leave it not filled in with a value and let them choose.

**Comment by maxxxxxdlp** [comment]
Fixed. Required picklists now have a null value.
A null value is selected by default.
A null value in a required pick list would prevent saving.
Default non-null value can still be set using form definition

**Comment by mcruz-umich** [comment]
@maxxxxxdlp @benanhalt @beach53 

### My Running Versions
S7: v7.3.1-102-g7bbdcfe
S6: 6.8.00
Database: 6.8.00
Schema: 2.7

### Bug Description
When rendering a picklist, S7 auto-inserts a blank " " option that allows the user to clear out any previously selected value by writing |null| to the DB.
<img width="852" alt="image" src="https://user-images.githubusercontent.com/36455924/167230960-a1af1d7d-b577-474d-9a11-37fb25c35118.png">

However, in S6.8.0, no such blank option is auto-inserted. Therefore a |null| option must be manually added to the picklist so that the user can clear out any previously set value. The use-case is if the previously selected value was incorrect and the user needs to just clear it out.
<img width="771" alt="image" src="https://user-images.githubusercontent.com/36455924/167230948-e009fe44-47b8-4cc0-9ddc-a7ab7583e2b8.png">

So I added a |null| option to a picklist as shown here:
<img width="865" alt="image" src="https://user-images.githubusercontent.com/36455924/167230940-9e1589c6-98a4-4ee1-968a-ac83a9ac7372.png">

Now S6 renders a blank " " option and it can be used to clear out a previously selected value. It was confirmed that it writes |null| into the DB.
<img width="765" alt="image" src="https://user-images.githubusercontent.com/36455924/167230994-15640437-b0e0-4d29-b5c0-9a5deb5fe4ba.png">

However, in S7, the picklist now renders with two blank " " options.
One is the auto-inserted blank option from S7 and the other is the blank option that was explicitly put into the picklist via the picklist editor.
<img width="925" alt="image" src="https://user-images.githubusercontent.com/36455924/167231066-499fb4e8-0f2f-429d-9d14-09cc20d5e413.png">
