### ISSUE TITLE
Program appears to freeze if you select to import dataset twice

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#835]
If you select Import Dataset then rethink it and go back to the menu to choose something else, it won't let you choose import dataset again.  It just appears to freeze.  You can click close and get back to the import dataset page, but clicking the import dataset button should take you there as well.
![image](https://user-images.githubusercontent.com/12532430/120842653-9abc4b00-c532-11eb-8f2f-8a6a5865c9bb.png)

**Comment by benanhalt** [comment]
The problem is that the site is already on the import data set page. Clicking the button tells it to navigate to that page, so nothing happens. We should probably do an audit of dialog buttons that trigger a navigation action and make them also close the dialog. Currently we often just rely on navigation to close the dialog so it appears nothing has happened. (which it hasn't)

**Comment by maxxxxxdlp** [comment]
I find this behavior quite confusing too. It should either close the dialog or reload the page
Similar issue - https://github.com/specify/specify7/issues/734

**Comment by benanhalt** [comment]
It's pretty easy to do. Just wherever a dialog button triggers a navigation it should also do `$(this).dialog('close');` The main thing is just finding all the places that happens.

**Comment by maxxxxxdlp** [comment]
Okay, I can work on that as soon as we release 7.6
Also, I would like to go over the frontend/templates/backend and to extract the localization strings into some sorts of data structure
