### ISSUE TITLE
Validate XML Specify viewset definitions when uploading

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#884]
See https://github.com/specify/specify7/issues/499#issuecomment-882678323

**Comment by maxxxxxdlp** [comment]
Groundwork for this is done in https://github.com/specify/specify7/pull/2796

The XML syncer lib I wrote does validation when parsing, and links validation messages to a given XML element/attribute

Remaining things:
- Define a syncer spec for form validation
- Expose form validation errors in the UI (maybe in the form editor 🤞 )

**Comment by maxxxxxdlp** [comment]
This is fixed now.
To test:
- Open any form definition
- Open "XML editor"
- Any errors inside of `<views>` should be reported (wrong table name, wrong field name, missing required attribute, missing required XML child)
- Switch back to "Visual Editor"
- Open any form definition
- Any errors in the editor on the editor should be reported. Form preview should update in real time (as long as there are no syntax errors)

**Comment by chanulee1** [comment]
Two different errors triggered for unknown field name. Expected?
![image](https://user-images.githubusercontent.com/103299204/232154802-101124f2-f47f-4191-a882-439252b75b11.png)

"Name" field triggering error for weblink fields, special checkbox fields.

https://user-images.githubusercontent.com/103299204/232155852-18caca9d-c26b-4179-b3fd-7b130bc64114.mp4

\
Pasting attribute into subview cell brings user back to top of xml file. Does not happen when typing the attribute out. Also happens when commenting out cell types like subview, command, plugins. 

https://user-images.githubusercontent.com/103299204/232161353-5a4f6cd2-5f74-44d5-9c07-fe094606185e.mp4

https://coldfish-xml-editor.test.specifysystems.org/specify/resources/view-set/4/CollectionObject/CollectionObject

**Comment by maxxxxxdlp** [comment]
> Two different errors triggered for unknown field name. Expected?

It's a bug. Fixed

> "Name" field triggering error for weblink fields, special checkbox fields.

caused by the same bug as the one before

> Pasting attribute into subview cell brings user back to top of xml file. Does not happen when typing the attribute out. Also happens when commenting out cell types like subview, command, plugins.

This one was tricky to debug. Caused by a loading screen appearing for a few milliseconds when subview is displayed.

**Comment by chanulee1** [comment]
Looks like it's working great!
