### ISSUE TITLE
Error Messages getting cut off

### ISSUE THREAD

**Issue by tlammer** [specify/specify7#932]
![image](https://user-images.githubusercontent.com/12532430/131892923-c0414f1b-072c-4c85-9dd6-fdf26654fb4b.png)
Doesn't matter if I move the window or expand the window so there's room to see the error, I can't see the error.

**Comment by maxxxxxdlp** [comment]
Ideally, the spreadsheet libriary we are using should have handled this
Either way, I provided an ugly hack that should fix this issue

**Comment by tlammer** [comment]
still happening

**Comment by maxxxxxdlp** [comment]
Works fine for me. Tested on http://db1.biwebdbtest.nhm.ku.edu/
The comment box may still spawn outside the page for a few milliseconds, but there isn't much I can do about that, other then to design our own comment box instead of using the one provided by the spreadsheet libriary

https://user-images.githubusercontent.com/40512816/132047460-ca6beb4b-5749-479f-8ea2-877c30309ec1.mov

**Comment by tlammer** [comment]
Still happening for me on Chrome on a PC

**Comment by maxxxxxdlp** [comment]
Does it happen in an incognito tab?

**Comment by tlammer** [comment]
Yes.  And actually it is worse now than it was before because it seems to flicker if I haven't scrolled all the way over

**Comment by maxxxxxdlp** [comment]
@tlammer Can you test this again? Should be working better now
