### ISSUE TITLE
Running report "Datamax Jar Labels" results in 500 error

### ISSUE THREAD

**Issue by garrettgirard** [specify/specify7#95]
Bug in KUFish - master branch

Error:
Exception at /report_runner/run/
Field preptype not in table PrepType. Fields: ['isLoanable', 'name', 'timestampCreated', 'timestampModified', 'version', 'attributeDefs', 'collection', 'createdByAgent', 'modifiedByAgent']

**Comment by benanhalt** [comment]
I think this issue is specific to that database and caused by an invalid aggregator definition for *Preparation*. 

```xml
<format
        name="Preparation"
        title="Preparation"
        class="edu.ku.brc.specify.datamodel.Preparation"
        default="true"
        >
        <switch single="true">
            <fields>
                <field type="int">countAmt</field>
                <field sep=" " formatter="PrepType">prepType.prepType</field>
            </fields>
        </switch>
    </format>
```

The exception is that there is no *preptype* field in *PrepType*, which is true, so `prepType.prepType` in the above definition should be `prepType.name`.

I'm going to mark this as *invalid* since it is ultimately due to a configuration error. When we implement the UI for configuring formatters, it should check to prevent issues like this.
