### ISSUE TITLE
[a11y] Analyze all Specify 7 pages using Firefox's DevTools a11y tool

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#967]

**Comment by CarolineDenis** [comment]
Both Arc ToolKit and Firefox dev tool a11y have been used to verify Sp7 accessibility. 
They both identified the same accessibility issues, specifically problems with contrast and orphan label/input boxes. 

Arc ToolKit offers an easier-to-use graphical interface and detailed reports, while Firefox dev tool a11y offers built-in functionality and more flexibility for testing. 

On a personal level, I prefer the details provided by Arc ToolKit, also Arc Toolkit finds more issue than a11y. On the other hand a11y is easier to identify the issue at first glance and has a nice 'summary' tree for each page. 

The issues we addressed now are fixed in the PR (https://github.com/specify/specify7/pull/3463) 

I will add a TODO reminder in Sp calendar to make an accessibility check for every season.
